package io.infranexum.dcim.physical.application;

import io.infranexum.core.contracts.ContractVersion;
import io.infranexum.core.contracts.DomainIdentifier;
import io.infranexum.core.contracts.UuidV7Generator;
import io.infranexum.core.events.EventEnvelope;
import io.infranexum.core.events.EventSource;
import io.infranexum.core.events.EventType;
import io.infranexum.core.events.TransactionExecutionException;
import io.infranexum.core.events.TransactionalEventStore;
import io.infranexum.dcim.physical.domain.*;
import io.infranexum.dcim.physical.ports.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Clock;
import java.util.HexFormat;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** PGM-07-E05 application boundary for rack occupancy, equipment footprints, ports and cabling. */
public final class DcimPhysicalApplicationService {
    private static final ContractVersion EVENT_VERSION=ContractVersion.parse("1.0.0");
    private static final EventSource SOURCE=new EventSource("infranexum.dcim.physical");
    private final DcimPhysicalRepository repository; private final DcimPhysicalIdempotencyRepository idempotency;
    private final DcimPhysicalFeaturePolicy features; private final DcimPhysicalReferencePolicy references;
    private final TransactionalEventStore events; private final UuidV7Generator ids; private final Clock clock;
    public DcimPhysicalApplicationService(DcimPhysicalRepository repository,DcimPhysicalIdempotencyRepository idempotency,DcimPhysicalFeaturePolicy features,DcimPhysicalReferencePolicy references,TransactionalEventStore events,UuidV7Generator ids,Clock clock){this.repository=Objects.requireNonNull(repository,"repository");this.idempotency=Objects.requireNonNull(idempotency,"idempotency");this.features=Objects.requireNonNull(features,"features");this.references=Objects.requireNonNull(references,"references");this.events=Objects.requireNonNull(events,"events");this.ids=Objects.requireNonNull(ids,"ids");this.clock=Objects.requireNonNull(clock,"clock");}

    public EquipmentModel createModel(CreateEquipmentModelCommand c,String idem,PhysicalCommandContext ctx){requireEnabled();Objects.requireNonNull(c,"command");references.requireManufacturer(c.manufacturerPartnerId(),c.organizationId());String fp=fingerprint("model",c);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayModel(prior.orElseThrow(),fp,"model.create");if(repository.modelCodeExists(c.organizationId(),c.manufacturerPartnerId(),c.code()))throw conflict("DCIM_MODEL_DUPLICATE","model code already exists for manufacturer");EquipmentModel model=EquipmentModel.draft(ids.next(),c.organizationId(),c.manufacturerPartnerId(),c.code(),c.displayName(),c.formFactor(),c.rackUnits(),c.widthMm(),c.depthMm(),c.weightKg(),c.portTemplates(),c.description(),ctx.actorId(),ctx.reason(),clock.instant());repository.insertModel(model);tx.append(event("dcim.equipment_model.created.v1",model.id(),model.organizationId(),ctx,"\"manufacturer_partner_id\":\""+model.manufacturerPartnerId()+"\",\"version\":"+model.version()));remember(idem,fp,"model.create",model.id());return model;});}
    public Rack createRack(CreateRackCommand c,String idem,PhysicalCommandContext ctx){requireEnabled();Objects.requireNonNull(c,"command");references.requireScope(c.organizationId(),c.subdivisionId());references.requireActiveRoom(c.roomId(),c.organizationId(),c.subdivisionId());String fp=fingerprint("rack",c);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayRack(prior.orElseThrow(),fp,"rack.create");if(repository.rackCount()>=features.rackLimit())throw conflict("DCIM_RACK_QUOTA","rack quota reached");if(repository.rackCodeExists(c.roomId(),c.code()))throw conflict("DCIM_RACK_DUPLICATE","rack code already exists in room");Rack rack=Rack.draft(ids.next(),c.organizationId(),c.subdivisionId(),c.roomId(),c.code(),c.displayName(),c.heightU(),c.widthMm(),c.depthMm(),ctx.actorId(),ctx.reason(),clock.instant());repository.insertRack(rack);tx.append(event("dcim.rack.created.v1",rack.id(),rack.organizationId(),ctx,"\"room_id\":\""+rack.roomId()+"\",\"version\":"+rack.version()));remember(idem,fp,"rack.create",rack.id());return rack;});}
    public EquipmentModel changeModelStatus(DomainIdentifier id,long expectedVersion,PhysicalStatus target,String idem,PhysicalCommandContext ctx){requireEnabled();String fp=fingerprint("model.status",id,expectedVersion,target);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayModel(prior.orElseThrow(),fp,"model.status");EquipmentModel current=requireModel(id);if(current.version()!=expectedVersion)throw conflict("VERSION_CONFLICT","equipment model version changed");EquipmentModel changed=current.changeStatus(target,ctx.actorId(),ctx.reason(),clock.instant());repository.updateModel(changed,expectedVersion);tx.append(event("dcim.equipment_model."+target.wireValue()+".v1",changed.id(),changed.organizationId(),ctx,"\\\"version\\\":"+changed.version()));remember(idem,fp,"model.status",changed.id());return changed;});}
    public Rack changeRackStatus(DomainIdentifier id,long expectedVersion,PhysicalStatus target,String idem,PhysicalCommandContext ctx){requireEnabled();String fp=fingerprint("rack.status",id,expectedVersion,target);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayRack(prior.orElseThrow(),fp,"rack.status");Rack current=requireRack(id);if(current.version()!=expectedVersion)throw conflict("VERSION_CONFLICT","rack version changed");if((target==PhysicalStatus.DECOMMISSIONED||target==PhysicalStatus.ARCHIVED)&&!repository.equipment(current.organizationId(),current.id(),1).isEmpty())throw conflict("DCIM_RACK_NOT_EMPTY","rack must be empty before decommission/archive");Rack changed=current.changeStatus(target,ctx.actorId(),ctx.reason(),clock.instant());repository.updateRack(changed,expectedVersion);tx.append(event("dcim.rack."+target.wireValue()+".v1",changed.id(),changed.organizationId(),ctx,"\\\"version\\\":"+changed.version()));remember(idem,fp,"rack.status",changed.id());return changed;});}

    public Equipment install(InstallEquipmentCommand c,String idem,PhysicalCommandContext ctx){requireEnabled();Objects.requireNonNull(c,"command");references.requireScope(c.organizationId(),c.subdivisionId());references.requireRsotObject(c.rsotObjectId(),c.organizationId());references.requireItamAssetIfPresent(c.itamAssetId(),c.organizationId());String fp=fingerprint("install",c);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayEquipment(prior.orElseThrow(),fp,"equipment.install");Rack rack=requireRack(c.rackId());EquipmentModel model=requireModel(c.modelId());sameScope(c.organizationId(),c.subdivisionId(),rack);if(model.status()!=PhysicalStatus.ACTIVE)throw conflict("DCIM_MODEL_INACTIVE","equipment model must be active");if(rack.status()!=PhysicalStatus.ACTIVE)throw conflict("DCIM_RACK_INACTIVE","rack must be active");if(model.widthMm()>rack.widthMm()||model.depthMm()>rack.depthMm())throw conflict("DCIM_FOOTPRINT_INCOMPATIBLE","equipment footprint exceeds rack dimensions");repository.lockRackForOccupancy(rack.id());int endU=Math.addExact(c.startU(),model.rackUnits()-1);if(endU>rack.heightU())throw conflict("DCIM_RACK_U_OUT_OF_RANGE","equipment footprint exceeds rack height");if(repository.footprintOccupied(rack.id(),c.startU(),endU,null))throw conflict("DCIM_RACK_POSITION_OCCUPIED","requested rack units are occupied");if(c.serialNumber()!=null&&!c.serialNumber().isBlank()&&repository.serialExists(c.serialNumber()))throw conflict("DCIM_SERIAL_DUPLICATE","equipment serial number already exists");long requestedPorts=model.portTemplates().stream().mapToLong(PortTemplate::count).sum();if(repository.portCount()+requestedPorts>features.portLimit())throw conflict("DCIM_PORT_QUOTA","port quota reached");Equipment equipment=Equipment.installed(ids.next(),c.organizationId(),c.subdivisionId(),rack.id(),model.id(),c.rsotObjectId(),c.itamAssetId(),c.serialNumber(),c.assetTag(),c.startU(),c.face(),ctx.actorId(),ctx.reason(),clock.instant());List<PhysicalPort> ports=model.portTemplates().stream().flatMap(t->java.util.stream.IntStream.rangeClosed(1,t.count()).mapToObj(i->new PhysicalPort(ids.next(),c.organizationId(),equipment.id(),t.portName(i),t.kind(),t.media(),t.connector(),false))).toList();repository.insertEquipment(equipment,ports);tx.append(event("dcim.equipment.installed.v1",equipment.id(),equipment.organizationId(),ctx,"\"rack_id\":\""+rack.id()+"\",\"model_id\":\""+model.id()+"\",\"start_u\":"+equipment.startU()+",\"end_u\":"+endU));remember(idem,fp,"equipment.install",equipment.id());return equipment;});}
    public Equipment moveEquipment(DomainIdentifier id,long expectedVersion,DomainIdentifier rackId,int startU,String face,String idem,PhysicalCommandContext ctx){requireEnabled();String fp=fingerprint("move",id,expectedVersion,rackId,startU,face);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayEquipment(prior.orElseThrow(),fp,"equipment.move");Equipment current=requireEquipment(id);if(current.version()!=expectedVersion)throw conflict("VERSION_CONFLICT","equipment version changed");Rack rack=requireRack(rackId);sameScope(current.organizationId(),current.subdivisionId(),rack);EquipmentModel model=requireModel(current.modelId());repository.lockRackForOccupancy(rack.id());int endU=Math.addExact(startU,model.rackUnits()-1);if(endU>rack.heightU())throw conflict("DCIM_RACK_U_OUT_OF_RANGE","equipment footprint exceeds rack height");if(repository.footprintOccupied(rack.id(),startU,endU,current.id()))throw conflict("DCIM_RACK_POSITION_OCCUPIED","requested rack units are occupied");Equipment changed=current.move(rack.id(),startU,face,ctx.actorId(),ctx.reason(),clock.instant());repository.updateEquipment(changed,expectedVersion);tx.append(event("dcim.equipment.moved.v1",changed.id(),changed.organizationId(),ctx,"\"rack_id\":\""+rack.id()+"\",\"start_u\":"+startU));remember(idem,fp,"equipment.move",changed.id());return changed;});}
    public Equipment changeEquipmentStatus(DomainIdentifier id,long expectedVersion,PhysicalStatus target,String idem,PhysicalCommandContext ctx){requireEnabled();String fp=fingerprint("equipment.status",id,expectedVersion,target);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayEquipment(prior.orElseThrow(),fp,"equipment.status");Equipment current=requireEquipment(id);if(current.version()!=expectedVersion)throw conflict("VERSION_CONFLICT","equipment version changed");if((target==PhysicalStatus.DECOMMISSIONED||target==PhysicalStatus.ARCHIVED)&&repository.equipmentHasActiveCable(id))throw conflict("DCIM_EQUIPMENT_CABLED","disconnect active cables before decommissioning equipment");Equipment changed=current.changeStatus(target,ctx.actorId(),ctx.reason(),clock.instant());repository.updateEquipment(changed,expectedVersion);tx.append(event("dcim.equipment."+target.wireValue()+".v1",changed.id(),changed.organizationId(),ctx,"\"version\":"+changed.version()));remember(idem,fp,"equipment.status",changed.id());return changed;});}
    public CableConnection connect(ConnectPortsCommand c,String idem,PhysicalCommandContext ctx){requireEnabled();references.requireScope(c.organizationId(),c.subdivisionId());String fp=fingerprint("connect",c);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayCable(prior.orElseThrow(),fp,"cable.connect");if(repository.activeConnectionCount()>=features.connectionLimit())throw conflict("DCIM_CONNECTION_QUOTA","connection quota reached");PhysicalPort a=requirePort(c.portAId()),b=requirePort(c.portBId());repository.lockPortsForConnection(a.id(),b.id());a=requirePort(c.portAId());b=requirePort(c.portBId());if(!a.organizationId().equals(c.organizationId())||!b.organizationId().equals(c.organizationId()))throw conflict("DCIM_SCOPE_MISMATCH","ports belong to another organization");if(a.equipmentId().equals(b.equipmentId()))throw conflict("DCIM_LOOPBACK_CABLE_FORBIDDEN","cable endpoints must belong to different equipment");if(repository.portConnected(a.id())||repository.portConnected(b.id()))throw conflict("DCIM_PORT_ALREADY_CONNECTED","one or both ports are already connected");if(a.kind()!=b.kind())throw conflict("DCIM_PORT_KIND_MISMATCH","port kinds are incompatible");if(!a.media().equals(b.media())||!a.connector().equals(b.connector()))throw conflict("DCIM_PORT_MEDIA_MISMATCH","port media or connectors are incompatible");CableConnection cable=CableConnection.active(ids.next(),c.organizationId(),c.subdivisionId(),a.id(),b.id(),c.label(),a.media(),a.connector(),ctx.actorId(),ctx.reason(),clock.instant());repository.insertCable(cable);tx.append(event("dcim.cable.connected.v1",cable.id(),cable.organizationId(),ctx,"\"port_a_id\":\""+a.id()+"\",\"port_b_id\":\""+b.id()+"\""));remember(idem,fp,"cable.connect",cable.id());return cable;});}
    public CableConnection disconnect(DomainIdentifier id,long expectedVersion,String idem,PhysicalCommandContext ctx){requireEnabled();String fp=fingerprint("disconnect",id,expectedVersion);return execute(tx->{Optional<DcimPhysicalIdempotencyRepository.Record> prior=idempotency.find(idem);if(prior.isPresent())return replayCable(prior.orElseThrow(),fp,"cable.disconnect");CableConnection current=requireCable(id);if(current.version()!=expectedVersion)throw conflict("VERSION_CONFLICT","cable version changed");CableConnection changed=current.disconnect(ctx.actorId(),ctx.reason(),clock.instant());repository.updateCable(changed,expectedVersion);tx.append(event("dcim.cable.disconnected.v1",changed.id(),changed.organizationId(),ctx,"\"version\":"+changed.version()));remember(idem,fp,"cable.disconnect",changed.id());return changed;});}

    public EquipmentModel model(DomainIdentifier id){requireEnabled();return requireModel(id);} public Rack rack(DomainIdentifier id){requireEnabled();return requireRack(id);} public Equipment equipment(DomainIdentifier id){requireEnabled();return requireEquipment(id);} public CableConnection cable(DomainIdentifier id){requireEnabled();return requireCable(id);} public List<EquipmentModel> models(DomainIdentifier org,int limit){requireEnabled();return repository.models(org,bounded(limit));} public List<Rack> racks(DomainIdentifier org,DomainIdentifier room,int limit){requireEnabled();return repository.racks(org,room,bounded(limit));} public List<Equipment> equipment(DomainIdentifier org,DomainIdentifier rack,int limit){requireEnabled();return repository.equipment(org,rack,bounded(limit));} public List<PhysicalPort> ports(DomainIdentifier equipmentId){requireEnabled();return repository.ports(equipmentId);} public List<CableConnection> cables(DomainIdentifier org,int limit){requireEnabled();return repository.cables(org,bounded(limit));}

    private void sameScope(DomainIdentifier org,DomainIdentifier sub,Rack rack){if(!rack.organizationId().equals(org)||!rack.subdivisionId().equals(sub))throw conflict("DCIM_SCOPE_MISMATCH","rack belongs to another governance scope");}
    private int bounded(int limit){if(limit<1||limit>500)throw new IllegalArgumentException("limit must be 1..500");return limit;}
    private EquipmentModel requireModel(DomainIdentifier id){return repository.model(id).orElseThrow(()->new DcimPhysicalNotFoundException("equipment model"));} private Rack requireRack(DomainIdentifier id){return repository.rack(id).orElseThrow(()->new DcimPhysicalNotFoundException("rack"));} private Equipment requireEquipment(DomainIdentifier id){return repository.equipment(id).orElseThrow(()->new DcimPhysicalNotFoundException("equipment"));} private PhysicalPort requirePort(DomainIdentifier id){return repository.port(id).orElseThrow(()->new DcimPhysicalNotFoundException("port"));} private CableConnection requireCable(DomainIdentifier id){return repository.cable(id).orElseThrow(()->new DcimPhysicalNotFoundException("cable"));}
    private EquipmentModel replayModel(DcimPhysicalIdempotencyRepository.Record r,String fp,String op){checkReplay(r,fp,op);return requireModel(r.resultId());} private Rack replayRack(DcimPhysicalIdempotencyRepository.Record r,String fp,String op){checkReplay(r,fp,op);return requireRack(r.resultId());} private Equipment replayEquipment(DcimPhysicalIdempotencyRepository.Record r,String fp,String op){checkReplay(r,fp,op);return requireEquipment(r.resultId());} private CableConnection replayCable(DcimPhysicalIdempotencyRepository.Record r,String fp,String op){checkReplay(r,fp,op);return requireCable(r.resultId());} private void checkReplay(DcimPhysicalIdempotencyRepository.Record r,String fp,String op){if(!r.operation().equals(op)||!r.payloadSha256().equals(fp))throw conflict("IDEMPOTENCY_CONFLICT","idempotency key was used with another payload");} private void remember(String key,String fp,String op,DomainIdentifier result){idempotency.insert(new DcimPhysicalIdempotencyRepository.Record(validKey(key),fp,op,result,clock.instant()));}
    private void requireEnabled(){if(!features.physicalEnabled())throw conflict("DCIM_PHYSICAL_CAPABILITY_UNAVAILABLE","DCIM physical infrastructure capability is unavailable");}
    private EventEnvelope event(String type,DomainIdentifier aggregateId,DomainIdentifier org,PhysicalCommandContext ctx,String fields){return new EventEnvelope(ids.next(),new EventType(type),EVENT_VERSION,clock.instant(),SOURCE,ctx.correlationId(),aggregateId,"{\"id\":\""+aggregateId+"\",\"organization_id\":\""+org+"\","+fields+"}");}
    private static String validKey(String v){String x=Objects.requireNonNull(v,"idempotencyKey").strip();if(x.length()<8||x.length()>200||!x.matches("[A-Za-z0-9._:-]+"))throw new IllegalArgumentException("idempotencyKey must contain 8..200 safe characters");return x;} private static DcimPhysicalConflictException conflict(String code,String message){return new DcimPhysicalConflictException(code,message);} private static String fingerprint(Object... values){try{MessageDigest d=MessageDigest.getInstance("SHA-256");for(Object v:values){d.update(String.valueOf(v).getBytes(StandardCharsets.UTF_8));d.update((byte)0);}return HexFormat.of().formatHex(d.digest());}catch(NoSuchAlgorithmException e){throw new IllegalStateException("SHA-256 unavailable",e);}}
    private <T>T execute(io.infranexum.core.events.TransactionalWork<T> work){try{return events.execute(work).value();}catch(TransactionExecutionException failure){Throwable c=failure.getCause();if(c instanceof DcimPhysicalConflictException x)throw x;if(c instanceof DcimPhysicalNotFoundException x)throw x;if(c instanceof IllegalArgumentException x)throw x;throw failure;}}
}
