BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_NOTIFICATION_STATE PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_NOTIFICATION_OUTBOX PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
