BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_API_IDEMP (
    SCOPE_KEY VARCHAR2(64 CHAR) NOT NULL,
    OPERATION_NAME VARCHAR2(160 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(200 CHAR) NOT NULL,
    REQUEST_SHA256 CHAR(64 CHAR) NOT NULL,
    STATE VARCHAR2(20 CHAR) NOT NULL,
    HTTP_STATUS NUMBER(3) NULL,
    CONTENT_TYPE VARCHAR2(160 CHAR) NULL,
    ETAG VARCHAR2(256 CHAR) NULL,
    LOCATION VARCHAR2(1024 CHAR) NULL,
    RESPONSE_BODY_B64 CLOB NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INX_API_IDEMP PRIMARY KEY(SCOPE_KEY,OPERATION_NAME,IDEMPOTENCY_KEY),
    CONSTRAINT CK_INX_API_IDEMP_STATE CHECK (STATE IN (''IN_PROGRESS'',''COMPLETED'',''INDETERMINATE''))
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_API_IDEMP_UPDATED ON INFRANEXUM_CORE_API_IDEMP(UPDATED_AT)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
