BEGIN EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_DCIM_FACILITY (
 ID VARCHAR2(36 CHAR) PRIMARY KEY, FACILITY_KIND VARCHAR2(16 CHAR) NOT NULL,
 ORGANIZATION_ID VARCHAR2(36 CHAR) NOT NULL, SUBDIVISION_ID VARCHAR2(36 CHAR) NOT NULL,
 PARENT_ID VARCHAR2(36 CHAR), SCOPE_ID VARCHAR2(36 CHAR) NOT NULL,
 CODE VARCHAR2(64 CHAR) NOT NULL, DISPLAY_NAME VARCHAR2(128 CHAR) NOT NULL, LIFECYCLE_STATUS VARCHAR2(16 CHAR) NOT NULL,
 ADDRESS_LINE_1 VARCHAR2(128 CHAR), ADDRESS_LINE_2 VARCHAR2(128 CHAR), POSTAL_CODE VARCHAR2(16 CHAR), CITY VARCHAR2(64 CHAR),
 COUNTRY_CODE CHAR(2 CHAR), TIMEZONE VARCHAR2(64 CHAR), LATITUDE NUMBER(10,7), LONGITUDE NUMBER(10,7), FLOOR_COUNT NUMBER(10), LEVEL_NUMBER NUMBER(10),
 AREA_M2 NUMBER(14,3), LEVEL_HEIGHT_M NUMBER(10,3), CAPACITY_KW NUMBER(14,3), ACCESS_RESTRICTION VARCHAR2(16 CHAR), ZONE_TYPE VARCHAR2(32 CHAR), DESCRIPTION VARCHAR2(4096 CHAR),
 VERSION NUMBER(19) DEFAULT 1 NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 CREATED_BY VARCHAR2(36 CHAR) NOT NULL, UPDATED_BY VARCHAR2(36 CHAR) NOT NULL, LAST_REASON VARCHAR2(1024 CHAR) NOT NULL,
 CONSTRAINT UQ_INX_DCIM_FAC_SCOPE UNIQUE(FACILITY_KIND,SCOPE_ID,CODE),
 CONSTRAINT FK_INX_DCIM_FAC_PARENT FOREIGN KEY(PARENT_ID) REFERENCES INFRANEXUM_DCIM_FACILITY(ID),
 CONSTRAINT CK_INX_DCIM_FAC_KIND CHECK (FACILITY_KIND IN (''SITE'',''BUILDING'',''FLOOR'',''ROOM'',''ZONE'')),
 CONSTRAINT CK_INX_DCIM_FAC_CODE CHECK (REGEXP_LIKE(CODE,''^[A-Z0-9][A-Z0-9_-]{2,63}$'')),
 CONSTRAINT CK_INX_DCIM_FAC_STATUS CHECK (LIFECYCLE_STATUS IN (''DRAFT'',''ACTIVE'',''SUSPENDED'',''MAINTENANCE'',''LOCKED'',''INACTIVE'',''ARCHIVED'',''DELETED'')),
 CONSTRAINT CK_INX_DCIM_FAC_GEO CHECK ((LATITUDE IS NULL OR LATITUDE BETWEEN -90 AND 90) AND (LONGITUDE IS NULL OR LONGITUDE BETWEEN -180 AND 180)),
 CONSTRAINT CK_INX_DCIM_FAC_POS CHECK ((FLOOR_COUNT IS NULL OR FLOOR_COUNT>0) AND (AREA_M2 IS NULL OR AREA_M2>0) AND (LEVEL_HEIGHT_M IS NULL OR LEVEL_HEIGHT_M>0) AND (CAPACITY_KW IS NULL OR CAPACITY_KW>0)),
 CONSTRAINT CK_INX_DCIM_FAC_ACCESS CHECK (ACCESS_RESTRICTION IS NULL OR ACCESS_RESTRICTION IN (''open'',''restricted'',''secure'')),
 CONSTRAINT CK_INX_DCIM_FAC_ZONE CHECK (ZONE_TYPE IS NULL OR ZONE_TYPE IN (''cooling'',''power_distribution'',''airflow'',''security'')),
 CONSTRAINT CK_INX_DCIM_FAC_SITE CHECK ((FACILITY_KIND<>''SITE'') OR (PARENT_ID IS NULL AND ADDRESS_LINE_1 IS NOT NULL AND POSTAL_CODE IS NOT NULL AND CITY IS NOT NULL AND COUNTRY_CODE IS NOT NULL AND TIMEZONE IS NOT NULL)),
 CONSTRAINT CK_INX_DCIM_FAC_SITE_FIELDS CHECK ((FACILITY_KIND=''SITE'') OR (ADDRESS_LINE_1 IS NULL AND ADDRESS_LINE_2 IS NULL AND POSTAL_CODE IS NULL AND CITY IS NULL AND COUNTRY_CODE IS NULL AND TIMEZONE IS NULL)),
 CONSTRAINT CK_INX_DCIM_FAC_BUILDING CHECK ((FACILITY_KIND<>''BUILDING'') OR FLOOR_COUNT IS NOT NULL),
 CONSTRAINT CK_INX_DCIM_FAC_FLOOR CHECK ((FACILITY_KIND<>''FLOOR'') OR LEVEL_NUMBER IS NOT NULL),
 CONSTRAINT CK_INX_DCIM_FAC_ROOM CHECK ((FACILITY_KIND<>''ROOM'') OR AREA_M2 IS NOT NULL),
 CONSTRAINT CK_INX_DCIM_FAC_ZONE_REQ CHECK ((FACILITY_KIND<>''ZONE'') OR ZONE_TYPE IS NOT NULL),
 CONSTRAINT CK_INX_DCIM_FAC_KIND_FIELDS CHECK ((FACILITY_KIND=''BUILDING'' OR FLOOR_COUNT IS NULL) AND (FACILITY_KIND=''FLOOR'' OR (LEVEL_NUMBER IS NULL AND LEVEL_HEIGHT_M IS NULL)) AND (FACILITY_KIND IN (''BUILDING'',''FLOOR'',''ROOM'') OR AREA_M2 IS NULL) AND (FACILITY_KIND IN (''FLOOR'',''ROOM'') OR CAPACITY_KW IS NULL) AND (FACILITY_KIND=''ROOM'' OR ACCESS_RESTRICTION IS NULL) AND (FACILITY_KIND=''ZONE'' OR ZONE_TYPE IS NULL) AND (FACILITY_KIND IN (''SITE'',''BUILDING'') OR (LATITUDE IS NULL AND LONGITUDE IS NULL))),
 CONSTRAINT CK_INX_DCIM_FAC_CHILD CHECK ((FACILITY_KIND=''SITE'') OR PARENT_ID IS NOT NULL), CONSTRAINT CK_INX_DCIM_FAC_VER CHECK (VERSION>=1), CONSTRAINT CK_INX_DCIM_FAC_TIME CHECK (UPDATED_AT>=CREATED_AT))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_DCIM_FAC_ORG_KIND ON INFRANEXUM_DCIM_FACILITY(ORGANIZATION_ID,SUBDIVISION_ID,FACILITY_KIND,LIFECYCLE_STATUS,ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_DCIM_FAC_PARENT ON INFRANEXUM_DCIM_FACILITY(PARENT_ID,FACILITY_KIND,LIFECYCLE_STATUS,ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_DCIM_FAC_DEDUP (IDEMPOTENCY_KEY VARCHAR2(200 CHAR) PRIMARY KEY, PAYLOAD_SHA256 CHAR(64 CHAR) NOT NULL, OPERATION_NAME VARCHAR2(80 CHAR) NOT NULL, FACILITY_ID VARCHAR2(36 CHAR) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, CONSTRAINT FK_INX_DCIM_FAC_DEDUP FOREIGN KEY(FACILITY_ID) REFERENCES INFRANEXUM_DCIM_FACILITY(ID), CONSTRAINT CK_INX_DCIM_FAC_HASH CHECK (REGEXP_LIKE(PAYLOAD_SHA256,''^[0-9a-f]{64}$'')))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_DCIM_FAC_DEDUP ON INFRANEXUM_DCIM_FAC_DEDUP(CREATED_AT)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
