-- PGM-04-E02 / ADR-0029 remediation: drop only forbidden IAM -> Organization physical FKs.
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_IAM_USER_MEMBERSHIP DROP CONSTRAINT FK_INX_IAM_MEM_ORG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-2443 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_IAM_USER_MEMBERSHIP DROP CONSTRAINT FK_INX_IAM_MEM_SUB'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-2443 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_IAM_GROUP DROP CONSTRAINT FK_INX_IAM_GROUP_ORG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-2443 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_IAM_PERMISSION DROP CONSTRAINT FK_INX_IAM_PERM_ORG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-2443 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_IAM_ROLE DROP CONSTRAINT FK_INX_IAM_ROLE_ORG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-2443 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_IAM_ROLE_ASSIGNMENT DROP CONSTRAINT FK_INX_IAM_RA_ORG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-2443 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_IAM_ROLE_ASSIGNMENT DROP CONSTRAINT FK_INX_IAM_RA_SUB'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-2443 THEN RAISE; END IF; END;/
