BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_WORKER_TASK DROP CONSTRAINT CK_INX_WORKER_CORRELATION_V7';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_WORKER_TASK DROP COLUMN CORRELATION_ID';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -904 THEN RAISE; END IF;
END;
/
