DECLARE
  model_count NUMBER; cable_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO model_count FROM INFRANEXUM_DCIM_MODEL WHERE EQUIPMENT_CATEGORY<>'OTHER' OR EQUIPMENT_TYPE<>'OTHER_EQUIPMENT' OR MANUFACTURER_REFERENCE IS NOT NULL OR RACK_UNITS=0 OR WIDTH_MM=0 OR DEPTH_MM=0 OR WEIGHT_KG=0;
  SELECT COUNT(*) INTO cable_count FROM INFRANEXUM_DCIM_CABLE WHERE CABLE_TYPE<>'OTHER' OR LENGTH_METERS<>1 OR MANUFACTURER_PARTNER_ID IS NOT NULL OR MANUFACTURER_REFERENCE IS NOT NULL;
  IF model_count>0 OR cable_count>0 THEN RAISE_APPLICATION_ERROR(-20040,'rollback would discard DCIM taxonomy/cable metadata; migrate or export affected records first'); END IF;
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_CABLE DROP CONSTRAINT CK_INX_DCIM_CABLE_TYPE';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_CABLE DROP CONSTRAINT CK_INX_DCIM_CABLE_VENDOR_REF';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_CABLE DROP CONSTRAINT CK_INX_DCIM_CABLE_LENGTH';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_CABLE DROP COLUMN MANUFACTURER_REFERENCE';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_CABLE DROP COLUMN MANUFACTURER_PARTNER_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_CABLE DROP COLUMN LENGTH_METERS';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_CABLE DROP COLUMN CABLE_TYPE';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL DROP CONSTRAINT CK_INX_DCIM_MODEL_RACK_DIMS';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL DROP CONSTRAINT CK_INX_DCIM_MODEL_TAXONOMY';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL DROP CONSTRAINT CK_INX_DCIM_MODEL_TYPE';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL DROP CONSTRAINT CK_INX_DCIM_MODEL_CATEGORY';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL DROP CONSTRAINT CK_INX_DCIM_MODEL_DIMS';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL ADD CONSTRAINT CK_INX_DCIM_MODEL_DIMS CHECK(RACK_UNITS BETWEEN 1 AND 100 AND WIDTH_MM BETWEEN 1 AND 5000 AND DEPTH_MM BETWEEN 1 AND 5000 AND WEIGHT_KG>0)';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL DROP COLUMN MANUFACTURER_REFERENCE';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL DROP COLUMN EQUIPMENT_TYPE';
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_DCIM_MODEL DROP COLUMN EQUIPMENT_CATEGORY';
END;
/
