BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_IAM_SOD_CONSTRAINT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_IAM_ACCESS_POLICY_CONDITION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_IAM_ACCESS_POLICY_RULE CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_IAM_ACCESS_POLICY CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
