DECLARE
  entry_count NUMBER;
  tombstone_count NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM INFRANEXUM_CORE_AUDIT_ENTRY' INTO entry_count;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM INFRANEXUM_CORE_AUDIT_PURGE_TOMBSTONE' INTO tombstone_count;
  IF entry_count > 0 OR tombstone_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20005, 'rollback 0005 refused: audit evidence exists');
  END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_INX_AUDIT_ENTRY_IMMUTABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_INX_AUDIT_TOMB_IMMUTABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_CORE_AUDIT_PURGE_TOMBSTONE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_CORE_AUDIT_ENTRY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_CORE_AUDIT_CHAIN_HEAD'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
