BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_IAM_LOCAL_SESSION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_IAM_LOCAL_ACCOUNT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
