import test from 'node:test';import assert from 'node:assert/strict';import { readFile } from 'node:fs/promises';
import { DcimPhysicalClient } from '../../src/applications/web/public/assets/dcim-physical.mjs';
import { availableCablePorts, equipmentTypesForCategory, readPortTemplates } from '../../src/applications/web/public/assets/dcim-physical-workspace.mjs';
const U='019ffbda-1301-7111-8101-000000000001';
function response(payload,status=200,headers={}){return {ok:status>=200&&status<300,status,headers:{get:n=>headers[String(n).toLowerCase()]??null},async json(){return payload;}};}
test('DCIM physical client is capability gated and exposes models racks equipment ports and cables',async()=>{assert.throws(()=>new DcimPhysicalClient({apiBaseUrl:'/api',dcimPhysicalEnabled:false}),/disabled/);const calls=[];const c=new DcimPhysicalClient({apiBaseUrl:'/api',dcimPhysicalEnabled:true},{fetchFunction:async(url,opts)=>{calls.push([url,opts]);return response([]);},cookieProvider:()=> 'INX_XSRF=csrf'});await c.taxonomy(U);await c.models(U);await c.racks(U,null);await c.equipment(U,null);await c.ports(U);await c.cables(U);assert.deepEqual(calls.map(x=>x[0]),['/api/v1/dcim/equipment-taxonomy?organization_id='+U,'/api/v1/dcim/equipment-models?organization_id='+U+'&offset=0&limit=200','/api/v1/dcim/racks?organization_id='+U+'&limit=200','/api/v1/dcim/equipment?organization_id='+U+'&limit=200','/api/v1/dcim/equipment/'+U+'/ports?offset=0&limit=200','/api/v1/dcim/cables?organization_id='+U+'&limit=200']);});
test('DCIM physical mutations enforce CSRF idempotency and If-Match',async()=>{let request;const c=new DcimPhysicalClient({apiBaseUrl:'/api',dcimPhysicalEnabled:true},{cookieProvider:()=> 'INX_XSRF=token',fetchFunction:async(url,opts)=>{request={url,opts};return response({id:U});}});await c.equipmentStatus(U,2,'maintenance','planned maintenance','dcim-eq-maint-0001');assert.equal(request.opts.headers['X-CSRF-Token'],'token');assert.equal(request.opts.headers['Idempotency-Key'],'dcim-eq-maint-0001');assert.equal(request.opts.headers['If-Match'],'"ver-2"');});
test('DCIM physical workspace contains governed selects and no raw UUID inputs',async()=>{const source=await readFile(new URL('../../src/applications/web/public/assets/dcim-physical-workspace.mjs',import.meta.url),'utf8');for(const n of ['manufacturerPartnerId','equipmentAId','portAId','equipmentBId','portBId','rackId','modelId','rsotObjectId','itamAssetId'])assert.match(source,new RegExp(`sel\\('${n}'`));assert.match(source,/function sel\([^)]*\).*<select name=/s);assert.doesNotMatch(source,/input[^>]+name=["'](?:manufacturerPartnerId|rackId|modelId|rsotObjectId|itamAssetId|portAId|portBId)["']/);assert.match(source,/dcim-physical-extension/);assert.match(source,/wireAsyncForm/);assert.match(source,/wireAsyncAction/);});

test('DCIM physical workspace exposes model/rack lifecycle and equipment move with governed selectors',async()=>{const source=await readFile(new URL('../../src/applications/web/public/assets/dcim-physical-workspace.mjs',import.meta.url),'utf8');assert.match(source,/lifecycleControls\('model'\)/);assert.match(source,/lifecycleControls\('rack'\)/);assert.match(source,/dcim-\$\{kind\}-activate/);assert.match(source,/dcim-\$\{kind\}-archive/);assert.match(source,/dcim-equipment-move-form/);assert.match(source,/sel\('destinationRackId'/);assert.match(source,/c\.modelStatus\(/);assert.match(source,/c\.rackStatus\(/);assert.match(source,/c\.move\(/);assert.doesNotMatch(source,/operator transition|operator disconnect/);});

test('DCIM physical client exposes continuation headers without changing payload shape',async()=>{const c=new DcimPhysicalClient({apiBaseUrl:'/api',dcimPhysicalEnabled:true},{fetchFunction:async()=>response([{id:U}],200,{'x-page-limit':'1','x-next-cursor':U}),cookieProvider:()=> 'INX_XSRF=csrf'});const result=await c.racks(U,null,1);assert.deepEqual(result.payload,[{id:U}]);assert.deepEqual(result.pagination,{limit:1,nextCursor:U,nextOffset:null,hasNext:true});});


test('DCIM equipment model supports dependent taxonomy, automatic code and repeated heterogeneous port templates',async()=>{const source=await readFile(new URL('../../src/applications/web/public/assets/dcim-physical-workspace.mjs',import.meta.url),'utf8');assert.match(source,/sel\('category'/);assert.match(source,/sel\('equipmentType'/);assert.match(source,/fillEquipmentTypes/);assert.match(source,/data-dcim-port-template/);assert.match(source,/data-remove-port-template/);assert.doesNotMatch(source,/inp\('code'/);const values={namePrefix:'eth',count:'4',kind:'network',media:'copper',connector:'rj45'};const row={querySelector:(selector)=>({value:values[selector.match(/name="([^"]+)/)?.[1]]})};const form={querySelectorAll:()=>[row]};assert.deepEqual(readPortTemplates(form),[{namePrefix:'eth',count:4,kind:'network',media:'copper',connector:'rj45'}]);const taxonomy={categories:[{value:'server',types:[{value:'physical_server'},{value:'virtual_machine'}]},{value:'network',types:[{value:'router'}]}]};assert.deepEqual(equipmentTypesForCategory(taxonomy,'server').map(x=>x.value),['physical_server','virtual_machine']);assert.deepEqual(equipmentTypesForCategory(taxonomy,'network').map(x=>x.value),['router']);});

test('DCIM cable form models explicit equipment/port endpoints and governed cable metadata',async()=>{const source=await readFile(new URL('../../src/applications/web/public/assets/dcim-physical-workspace.mjs',import.meta.url),'utf8');for(const field of ['equipmentAId','portAId','equipmentBId','portBId','cableType','lengthMeters','manufacturerReference'])assert.match(source,new RegExp(field));assert.match(source,/fillCablePorts/);assert.match(source,/manufacturer is required when a manufacturer reference is provided/);const freeA={id:'pa',equipmentId:'eq-a',connected:false},usedA={id:'used',equipmentId:'eq-a',connected:true},freeB={id:'pb',equipmentId:'eq-b',connected:false};assert.deepEqual(availableCablePorts([freeA,usedA,freeB],'eq-a'),[freeA]);assert.deepEqual(availableCablePorts([freeA,usedA,freeB],'eq-b'),[freeB]);});
