-- InfraNexum migration 0036: durable outbound notification outbox, DLQ and endpoint suspension for Oracle.
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_NOTIFICATION_OUTBOX (
    DELIVERY_ID CHAR(36 CHAR) NOT NULL,
    ENDPOINT_KEY VARCHAR2(80 CHAR) NOT NULL,
    EVENT_ID VARCHAR2(200 CHAR) NOT NULL,
    EVENT_TYPE VARCHAR2(128 CHAR) NOT NULL,
    PAYLOAD_JSON CLOB NOT NULL,
    PAYLOAD_SHA256 CHAR(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT ''PENDING'' NOT NULL,
    ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
    AVAILABLE_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    LEASE_OWNER VARCHAR2(160 CHAR) NULL,
    LEASE_UNTIL TIMESTAMP WITH TIME ZONE NULL,
    DELIVERED_AT TIMESTAMP WITH TIME ZONE NULL,
    LAST_FAILURE VARCHAR2(64 CHAR) NULL,
    REPLAY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_REPLAYED_AT TIMESTAMP WITH TIME ZONE NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INX_NOTIF_OUTBOX PRIMARY KEY(DELIVERY_ID),
    CONSTRAINT UQ_INX_NOTIF_EVENT UNIQUE(ENDPOINT_KEY,EVENT_ID),
    CONSTRAINT CK_INX_NOTIF_ID CHECK (SUBSTR(DELIVERY_ID,15,1)=''7'' AND SUBSTR(DELIVERY_ID,20,1) IN (''8'',''9'',''a'',''b'')),
    CONSTRAINT CK_INX_NOTIF_KEY CHECK (REGEXP_LIKE(ENDPOINT_KEY,''^[a-z0-9][a-z0-9._-]{2,79}$'')),
    CONSTRAINT CK_INX_NOTIF_EID CHECK (REGEXP_LIKE(EVENT_ID,''^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$'')),
    CONSTRAINT CK_INX_NOTIF_ETYPE CHECK (REGEXP_LIKE(EVENT_TYPE,''^[a-z][a-z0-9]*(\.[a-z0-9]+|_[a-z0-9]+|-[a-z0-9]+){1,15}$'')),
    CONSTRAINT CK_INX_NOTIF_HASH CHECK (REGEXP_LIKE(PAYLOAD_SHA256,''^[0-9a-f]{64}$'')),
    CONSTRAINT CK_INX_NOTIF_STATUS CHECK (STATUS IN (''PENDING'',''IN_FLIGHT'',''DELIVERED'',''DEAD_LETTER'')),
    CONSTRAINT CK_INX_NOTIF_COUNT CHECK (ATTEMPTS>=0 AND REPLAY_COUNT>=0),
    CONSTRAINT CK_INX_NOTIF_LEASE CHECK ((STATUS=''IN_FLIGHT'' AND LEASE_OWNER IS NOT NULL AND LEASE_UNTIL IS NOT NULL) OR (STATUS<>''IN_FLIGHT'' AND LEASE_OWNER IS NULL AND LEASE_UNTIL IS NULL)),
    CONSTRAINT CK_INX_NOTIF_DONE CHECK ((STATUS=''DELIVERED'' AND DELIVERED_AT IS NOT NULL) OR (STATUS<>''DELIVERED'' AND DELIVERED_AT IS NULL)),
    CONSTRAINT CK_INX_NOTIF_REPLAY CHECK ((REPLAY_COUNT=0 AND LAST_REPLAYED_AT IS NULL) OR REPLAY_COUNT>0),
    CONSTRAINT CK_INX_NOTIF_JSON CHECK (PAYLOAD_JSON IS JSON)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_NOTIF_DISPATCH ON INFRANEXUM_NOTIFICATION_OUTBOX(STATUS,AVAILABLE_AT,CREATED_AT,DELIVERY_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_NOTIF_DLQ ON INFRANEXUM_NOTIFICATION_OUTBOX(ENDPOINT_KEY,STATUS,CREATED_AT,DELIVERY_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_NOTIFICATION_STATE (
    ENDPOINT_KEY VARCHAR2(80 CHAR) NOT NULL,
    CONSECUTIVE_DEAD_LETTERS NUMBER(10) DEFAULT 0 NOT NULL,
    SUSPENDED_UNTIL TIMESTAMP WITH TIME ZONE NULL,
    LAST_SUCCESS_AT TIMESTAMP WITH TIME ZONE NULL,
    LAST_FAILURE_AT TIMESTAMP WITH TIME ZONE NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INX_NOTIF_STATE PRIMARY KEY(ENDPOINT_KEY),
    CONSTRAINT CK_INX_NOTIF_ST_KEY CHECK (REGEXP_LIKE(ENDPOINT_KEY,''^[a-z0-9][a-z0-9._-]{2,79}$'')),
    CONSTRAINT CK_INX_NOTIF_ST_FAIL CHECK (CONSECUTIVE_DEAD_LETTERS>=0)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_NOTIF_SUSPEND ON INFRANEXUM_NOTIFICATION_STATE(SUSPENDED_UNTIL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
