-- InfraNexum migration 0001: Core schema history for Oracle.
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_SCHEMA_HISTORY (
        MIGRATION_ID VARCHAR2(32 CHAR) PRIMARY KEY,
        LOGICAL_CHECKSUM CHAR(64 CHAR) NOT NULL,
        APPLICATION_VERSION VARCHAR2(64 CHAR) NOT NULL,
        APPLIED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
        APPLIED_BY VARCHAR2(255 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
