BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_INTEGRATION_STATE CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_INTEGRATION_INBOX CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
