BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_FAC_DEDUP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_FACILITY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
