-- InfraNexum migration 0033: durable connector webhook inbox, DLQ and suspension state for Oracle.
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_INTEGRATION_INBOX (
    DELIVERY_ID CHAR(36 CHAR) NOT NULL,
    CONNECTOR_KEY VARCHAR2(80 CHAR) NOT NULL,
    EXTERNAL_DELIVERY_ID VARCHAR2(200 CHAR) NOT NULL,
    PAYLOAD_JSON CLOB NOT NULL,
    PAYLOAD_SHA256 CHAR(64 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) DEFAULT ''PENDING'' NOT NULL,
    ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
    RECEIVED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    AVAILABLE_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    LEASE_OWNER VARCHAR2(160 CHAR) NULL,
    LEASE_UNTIL TIMESTAMP WITH TIME ZONE NULL,
    PROCESSED_AT TIMESTAMP WITH TIME ZONE NULL,
    LAST_FAILURE VARCHAR2(1024 CHAR) NULL,
    REPLAY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_REPLAYED_AT TIMESTAMP WITH TIME ZONE NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INX_INT_INBOX PRIMARY KEY(DELIVERY_ID),
    CONSTRAINT UQ_INX_INT_EXTERNAL UNIQUE(CONNECTOR_KEY,EXTERNAL_DELIVERY_ID),
    CONSTRAINT CK_INX_INT_ID CHECK (SUBSTR(DELIVERY_ID,15,1)=''7'' AND SUBSTR(DELIVERY_ID,20,1) IN (''8'',''9'',''a'',''b'')),
    CONSTRAINT CK_INX_INT_KEY CHECK (REGEXP_LIKE(CONNECTOR_KEY,''^[a-z0-9][a-z0-9._-]{2,79}$'')),
    CONSTRAINT CK_INX_INT_HASH CHECK (REGEXP_LIKE(PAYLOAD_SHA256,''^[0-9a-f]{64}$'')),
    CONSTRAINT CK_INX_INT_STATUS CHECK (STATUS IN (''PENDING'',''IN_FLIGHT'',''PROCESSED'',''DEAD_LETTER'')),
    CONSTRAINT CK_INX_INT_COUNT CHECK (ATTEMPTS>=0 AND REPLAY_COUNT>=0),
    CONSTRAINT CK_INX_INT_LEASE CHECK ((STATUS=''IN_FLIGHT'' AND LEASE_OWNER IS NOT NULL AND LEASE_UNTIL IS NOT NULL) OR (STATUS<>''IN_FLIGHT'' AND LEASE_OWNER IS NULL AND LEASE_UNTIL IS NULL)),
    CONSTRAINT CK_INX_INT_DONE CHECK ((STATUS=''PROCESSED'' AND PROCESSED_AT IS NOT NULL) OR (STATUS<>''PROCESSED'' AND PROCESSED_AT IS NULL)),
    CONSTRAINT CK_INX_INT_REPLAY CHECK ((REPLAY_COUNT=0 AND LAST_REPLAYED_AT IS NULL) OR REPLAY_COUNT>0),
    CONSTRAINT CK_INX_INT_JSON CHECK (PAYLOAD_JSON IS JSON)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_INT_DISPATCH ON INFRANEXUM_INTEGRATION_INBOX(STATUS,AVAILABLE_AT,RECEIVED_AT,DELIVERY_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_INT_DLQ ON INFRANEXUM_INTEGRATION_INBOX(CONNECTOR_KEY,STATUS,RECEIVED_AT,DELIVERY_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_INTEGRATION_STATE (
    CONNECTOR_KEY VARCHAR2(80 CHAR) NOT NULL,
    CONSECUTIVE_DEAD_LETTERS NUMBER(10) DEFAULT 0 NOT NULL,
    SUSPENDED_UNTIL TIMESTAMP WITH TIME ZONE NULL,
    LAST_SUCCESS_AT TIMESTAMP WITH TIME ZONE NULL,
    LAST_FAILURE_AT TIMESTAMP WITH TIME ZONE NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INX_INT_STATE PRIMARY KEY(CONNECTOR_KEY),
    CONSTRAINT CK_INX_INT_STATE_KEY CHECK (REGEXP_LIKE(CONNECTOR_KEY,''^[a-z0-9][a-z0-9._-]{2,79}$'')),
    CONSTRAINT CK_INX_INT_STATE_FAIL CHECK (CONSECUTIVE_DEAD_LETTERS>=0)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_INT_SUSPEND ON INFRANEXUM_INTEGRATION_STATE(SUSPENDED_UNTIL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
