-- InfraNexum migration 0003: transactional inbox reservation state for Oracle 19c/26ai.
DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'INFRANEXUM_CORE_INBOX_RECEIPT' AND COLUMN_NAME = 'STATUS';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT
            ADD (STATUS VARCHAR2(16 CHAR) DEFAULT ''COMPLETED'')';
    END IF;
END;
/

UPDATE INFRANEXUM_CORE_INBOX_RECEIPT
SET STATUS = 'COMPLETED'
WHERE STATUS IS NULL;

ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT
    MODIFY (STATUS DEFAULT 'COMPLETED' NOT NULL, COMPLETED_AT NULL);

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT DROP CONSTRAINT CK_INX_INBOX_COMPLETED';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT DROP CONSTRAINT CK_INX_INBOX_STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT
    ADD CONSTRAINT CK_INX_INBOX_STATUS CHECK (STATUS IN ('PROCESSING', 'COMPLETED'));

ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT
    ADD CONSTRAINT CK_INX_INBOX_COMPLETED CHECK (
        (STATUS = 'PROCESSING' AND COMPLETED_AT IS NULL)
        OR (STATUS = 'COMPLETED' AND COMPLETED_AT IS NOT NULL AND COMPLETED_AT >= RECEIVED_AT)
    );

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_INBOX_PROCESSING
        ON INFRANEXUM_CORE_INBOX_RECEIPT (STATUS, RECEIVED_AT, CONSUMER_NAME)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
