CREATE SCHEMA IF NOT EXISTS infranexum_iam;
CREATE TABLE IF NOT EXISTS infranexum_iam.iam_user (
 id UUID PRIMARY KEY, login VARCHAR(128) NOT NULL UNIQUE, email VARCHAR(320) NULL UNIQUE, display_name VARCHAR(200) NOT NULL,
 status VARCHAR(16) NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, deleted_at TIMESTAMPTZ NULL,
 CONSTRAINT ck_inx_iam_user_status CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','DELETED')),
 CONSTRAINT ck_inx_iam_user_deleted CHECK ((status='DELETED' AND deleted_at IS NOT NULL) OR (status<>'DELETED' AND deleted_at IS NULL)),
 CONSTRAINT ck_inx_iam_user_uuidv7 CHECK (SUBSTRING(id::TEXT FROM 15 FOR 1)='7' AND SUBSTRING(id::TEXT FROM 20 FOR 1) IN ('8','9','a','b'))
);
CREATE INDEX IF NOT EXISTS ix_inx_iam_user_status ON infranexum_iam.iam_user(status,login);
CREATE TABLE IF NOT EXISTS infranexum_iam.user_membership (
 id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES infranexum_iam.iam_user(id), organization_id UUID NOT NULL REFERENCES infranexum_org.organization(id),
 subdivision_id UUID NULL, effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL, revoked_at TIMESTAMPTZ NULL,
 CONSTRAINT fk_inx_iam_membership_sub FOREIGN KEY(organization_id,subdivision_id) REFERENCES infranexum_org.subdivision(organization_id,id),
 CONSTRAINT ck_inx_iam_membership_period CHECK (effective_to IS NULL OR effective_to>effective_from),
 CONSTRAINT ck_inx_iam_membership_revoke CHECK (revoked_at IS NULL OR revoked_at>=effective_from),
 CONSTRAINT ck_inx_iam_membership_uuidv7 CHECK (SUBSTRING(id::TEXT FROM 15 FOR 1)='7' AND SUBSTRING(id::TEXT FROM 20 FOR 1) IN ('8','9','a','b'))
);
CREATE INDEX IF NOT EXISTS ix_inx_iam_membership_effective ON infranexum_iam.user_membership(user_id,organization_id,subdivision_id,effective_from,effective_to,revoked_at);
CREATE TABLE IF NOT EXISTS infranexum_iam.iam_group (
 id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES infranexum_org.organization(id), code VARCHAR(96) NOT NULL, display_name VARCHAR(200) NOT NULL,
 system_group BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, deleted_at TIMESTAMPTZ NULL,
 UNIQUE(organization_id,code), CONSTRAINT uq_inx_iam_group_org_id UNIQUE(organization_id,id),
 CONSTRAINT ck_inx_iam_group_self_uuidv7 CHECK (SUBSTRING(id::TEXT FROM 15 FOR 1)='7' AND SUBSTRING(id::TEXT FROM 20 FOR 1) IN ('8','9','a','b'))
);
CREATE INDEX IF NOT EXISTS ix_inx_iam_group_active ON infranexum_iam.iam_group(organization_id,deleted_at,code);
CREATE TABLE IF NOT EXISTS infranexum_iam.group_user_member (
 organization_id UUID NOT NULL, group_id UUID NOT NULL, user_id UUID NOT NULL REFERENCES infranexum_iam.iam_user(id), created_at TIMESTAMPTZ NOT NULL,
 PRIMARY KEY(group_id,user_id), CONSTRAINT fk_inx_iam_gum_group FOREIGN KEY(organization_id,group_id) REFERENCES infranexum_iam.iam_group(organization_id,id)
);
CREATE TABLE IF NOT EXISTS infranexum_iam.group_group_member (
 organization_id UUID NOT NULL, parent_group_id UUID NOT NULL, child_group_id UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL,
 PRIMARY KEY(parent_group_id,child_group_id),
 CONSTRAINT fk_inx_iam_ggm_parent FOREIGN KEY(organization_id,parent_group_id) REFERENCES infranexum_iam.iam_group(organization_id,id),
 CONSTRAINT fk_inx_iam_ggm_child FOREIGN KEY(organization_id,child_group_id) REFERENCES infranexum_iam.iam_group(organization_id,id),
 CONSTRAINT ck_inx_iam_ggm_self CHECK (parent_group_id<>child_group_id)
);
CREATE INDEX IF NOT EXISTS ix_inx_iam_ggm_child ON infranexum_iam.group_group_member(organization_id,child_group_id,parent_group_id);
CREATE TABLE IF NOT EXISTS infranexum_iam.permission (
 id UUID PRIMARY KEY, organization_id UUID NULL REFERENCES infranexum_org.organization(id), code VARCHAR(160) NOT NULL, resource_type VARCHAR(64) NOT NULL, action_name VARCHAR(64) NOT NULL,
 sensitivity VARCHAR(16) NOT NULL, scope_kind VARCHAR(16) NOT NULL, system_defined BOOLEAN NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMPTZ NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL, deleted_at TIMESTAMPTZ NULL,
 CONSTRAINT ck_inx_iam_perm_sensitivity CHECK (sensitivity IN ('NORMAL','ELEVATED','CRITICAL')),
 CONSTRAINT ck_inx_iam_perm_scope CHECK (scope_kind IN ('PLATFORM','ORGANIZATION','SUBDIVISION')),
 CONSTRAINT ck_inx_iam_perm_owner CHECK ((system_defined AND organization_id IS NULL) OR (NOT system_defined AND organization_id IS NOT NULL)),
 CONSTRAINT ck_inx_iam_perm_uuidv7 CHECK (SUBSTRING(id::TEXT FROM 15 FOR 1)='7' AND SUBSTRING(id::TEXT FROM 20 FOR 1) IN ('8','9','a','b'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_inx_iam_perm_system_code ON infranexum_iam.permission(code) WHERE organization_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_inx_iam_perm_org_code ON infranexum_iam.permission(organization_id,code) WHERE organization_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS infranexum_iam.role (
 id UUID PRIMARY KEY, organization_id UUID NULL REFERENCES infranexum_org.organization(id), code VARCHAR(160) NOT NULL, display_name VARCHAR(200) NOT NULL,
 scope_kind VARCHAR(16) NOT NULL, system_role BOOLEAN NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, deleted_at TIMESTAMPTZ NULL,
 CONSTRAINT ck_inx_iam_role_scope CHECK (scope_kind IN ('PLATFORM','ORGANIZATION','SUBDIVISION')),
 CONSTRAINT ck_inx_iam_role_owner CHECK ((system_role AND organization_id IS NULL) OR (NOT system_role AND organization_id IS NOT NULL)),
 CONSTRAINT ck_inx_iam_role_uuidv7 CHECK (SUBSTRING(id::TEXT FROM 15 FOR 1)='7' AND SUBSTRING(id::TEXT FROM 20 FOR 1) IN ('8','9','a','b'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_inx_iam_role_system_code ON infranexum_iam.role(code) WHERE organization_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_inx_iam_role_org_code ON infranexum_iam.role(organization_id,code) WHERE organization_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS infranexum_iam.role_permission (
 role_id UUID NOT NULL REFERENCES infranexum_iam.role(id), permission_id UUID NOT NULL REFERENCES infranexum_iam.permission(id), PRIMARY KEY(role_id,permission_id)
);
CREATE TABLE IF NOT EXISTS infranexum_iam.role_assignment (
 id UUID PRIMARY KEY, role_id UUID NOT NULL REFERENCES infranexum_iam.role(id), actor_type VARCHAR(16) NOT NULL, actor_id UUID NOT NULL,
 scope_kind VARCHAR(16) NOT NULL, organization_id UUID NULL REFERENCES infranexum_org.organization(id), subdivision_id UUID NULL,
 effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NULL, revoked_at TIMESTAMPTZ NULL, revoked_by UUID NULL REFERENCES infranexum_iam.iam_user(id),
 CONSTRAINT fk_inx_iam_ra_sub FOREIGN KEY(organization_id,subdivision_id) REFERENCES infranexum_org.subdivision(organization_id,id),
 CONSTRAINT ck_inx_iam_ra_actor CHECK (actor_type IN ('USER','GROUP')),
 CONSTRAINT ck_inx_iam_ra_scope CHECK ((scope_kind='PLATFORM' AND organization_id IS NULL AND subdivision_id IS NULL) OR (scope_kind='ORGANIZATION' AND organization_id IS NOT NULL AND subdivision_id IS NULL) OR (scope_kind='SUBDIVISION' AND organization_id IS NOT NULL AND subdivision_id IS NOT NULL)),
 CONSTRAINT ck_inx_iam_ra_period CHECK (effective_to IS NULL OR effective_to>effective_from),
 CONSTRAINT ck_inx_iam_ra_revoke CHECK ((revoked_at IS NULL AND revoked_by IS NULL) OR (revoked_at IS NOT NULL AND revoked_by IS NOT NULL AND revoked_at>=effective_from)),
 CONSTRAINT ck_inx_iam_ra_uuidv7 CHECK (SUBSTRING(id::TEXT FROM 15 FOR 1)='7' AND SUBSTRING(id::TEXT FROM 20 FOR 1) IN ('8','9','a','b'))
);
CREATE INDEX IF NOT EXISTS ix_inx_iam_ra_effective ON infranexum_iam.role_assignment(actor_type,actor_id,effective_from,effective_to,revoked_at);
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-100a-7f29-a955-ede38a191ddb',NULL,'iam.group.add_group','iam_group','add_group','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-100b-751f-a299-30a6e959c43a',NULL,'iam.group.add_member','iam_group','add_member','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-100c-7b12-837f-c7092580b8c8',NULL,'iam.group.assign_role','iam_group','assign_role','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-100d-7cf5-ad75-1e90362d4d83',NULL,'iam.group.create','iam_group','create','ELEVATED','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-100e-73eb-a3d6-eb3e8c6e87a6',NULL,'iam.group.delete','iam_group','delete','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-100f-78b3-967b-293669395f36',NULL,'iam.group.read','iam_group','read','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1010-778a-9cbe-4b73398322c6',NULL,'iam.group.remove_group','iam_group','remove_group','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1011-708e-885c-b18dabda0fab',NULL,'iam.group.remove_member','iam_group','remove_member','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1012-72cd-b4af-1e879247ef57',NULL,'iam.group.search','iam_group','search','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1013-75ff-a4cb-020e6f4d8533',NULL,'iam.group.update','iam_group','update','ELEVATED','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1014-7ebd-9259-b7b085837853',NULL,'iam.permission.assign','iam_permission','assign','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1015-798e-8895-f97645984547',NULL,'iam.permission.create','iam_permission','create','ELEVATED','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1016-787b-b716-e916d915b013',NULL,'iam.permission.delete','iam_permission','delete','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1017-7858-aa58-c33aa4f51454',NULL,'iam.permission.evaluate','iam_permission','evaluate','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1018-7296-9c4c-4c6ab4a1cc0f',NULL,'iam.permission.manage_sensitivity','iam_permission','manage_sensitivity','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1019-7c12-b6aa-5a1a2e1cb112',NULL,'iam.permission.read','iam_permission','read','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-101a-7691-ba24-36832e97b46e',NULL,'iam.permission.revoke','iam_permission','revoke','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-101b-7df8-b4c7-c352944c1f5c',NULL,'iam.permission.search','iam_permission','search','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-101c-76a7-b3cd-fd5678dd7951',NULL,'iam.permission.update','iam_permission','update','ELEVATED','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-101d-7887-b1fc-94261abb3577',NULL,'iam.role.assign','iam_role','assign','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-101e-7056-bbe9-7ee611cf6752',NULL,'iam.role.create','iam_role','create','ELEVATED','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-101f-74ad-8b17-26590f281033',NULL,'iam.role.delete','iam_role','delete','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1020-7362-a31f-cabfd123adc8',NULL,'iam.role.manage_composite','iam_role','manage_composite','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1021-7626-a12b-623c45defa75',NULL,'iam.role.read','iam_role','read','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1022-7ece-ab5f-a30001423c0e',NULL,'iam.role.search','iam_role','search','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1023-768a-a71c-8d30dece5af5',NULL,'iam.role.unassign','iam_role','unassign','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1024-7c1f-a0de-9db1d321be8e',NULL,'iam.role.update','iam_role','update','ELEVATED','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1025-7023-b7ad-e8a656c3e144',NULL,'iam.role.view_sensitive_permissions','iam_role','view_sensitive_permissions','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1026-72aa-9253-3b1f8599ae0a',NULL,'iam.user.activate','iam_user','activate','NORMAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1027-7c73-9e9c-40e9393139a1',NULL,'iam.user.assign_role','iam_user','assign_role','CRITICAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1028-77e6-a975-32c805099097',NULL,'iam.user.create','iam_user','create','ELEVATED','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1029-7f54-9930-22eb69ba276d',NULL,'iam.user.delete','iam_user','delete','CRITICAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-102a-71cf-9a08-0eb2dfae5190',NULL,'iam.user.manage_membership','iam_user','manage_membership','CRITICAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-102b-7f64-b76a-2a9955b12b81',NULL,'iam.user.read','iam_user','read','NORMAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-102c-772c-b71f-065dff97c61a',NULL,'iam.user.reset_credentials','iam_user','reset_credentials','CRITICAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-102d-71f0-afbc-dc0a594ecfb4',NULL,'iam.user.search','iam_user','search','NORMAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-102e-7e03-8f9a-60712ef91a6a',NULL,'iam.user.suspend','iam_user','suspend','CRITICAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-102f-7f57-8096-a1c936602012',NULL,'iam.user.update','iam_user','update','ELEVATED','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1030-76ea-8118-081a1428d3ac',NULL,'organization.archive','organization','archive','NORMAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1031-75ec-96f8-6f9cbc41b2b9',NULL,'organization.create','organization','create','ELEVATED','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1032-7978-b88f-de6d7803a261',NULL,'organization.rename_code','organization','rename_code','NORMAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1033-7d76-a558-c703616cddae',NULL,'organization.subdivision.assign_manager','organization_subdivision','assign_manager','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1034-79c3-adf4-05c72c6ee3ea',NULL,'organization.subdivision.change_visibility','organization_subdivision','change_visibility','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1035-7d6e-b497-b5d4ebdf10fb',NULL,'organization.subdivision.create','organization_subdivision','create','ELEVATED','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1036-767e-9c04-5871df14f482',NULL,'organization.subdivision.delete','organization_subdivision','delete','CRITICAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1037-7729-9c4e-46fe98da3322',NULL,'organization.subdivision.read','organization_subdivision','read','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1038-74be-afa4-f3145555995b',NULL,'organization.subdivision.search','organization_subdivision','search','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1039-797c-86a5-ba72c4516949',NULL,'organization.subdivision.transfer','organization_subdivision','transfer','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-103a-7ab6-9998-5cd19c3a7837',NULL,'organization.subdivision.update','organization_subdivision','update','ELEVATED','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-103b-7c79-ae65-7a1ce9e0f6cc',NULL,'organization.subdivision.view_resources','organization_subdivision','view_resources','NORMAL','ORGANIZATION',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-103c-7d93-907a-532acf73eb21',NULL,'organization.suspend','organization','suspend','CRITICAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-103d-71bd-a97e-0c5665acad6d',NULL,'platform.capability.read','platform_capability','read','NORMAL','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.permission(id,organization_id,code,resource_type,action_name,sensitivity,scope_kind,system_defined,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-103e-7672-86e1-1c0c6fd677dd',NULL,'platform.profile.read','platform_profile','read','ELEVATED','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.role(id,organization_id,code,display_name,scope_kind,system_role,active,created_at,updated_at,deleted_at) VALUES ('019ffbda-1001-7e80-9ec8-7580467e9a85',NULL,'system.platform_admin','Platform administrator','PLATFORM',TRUE,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.role_permission(role_id,permission_id) SELECT '019ffbda-1001-7e80-9ec8-7580467e9a85',id FROM infranexum_iam.permission WHERE system_defined=TRUE ON CONFLICT DO NOTHING;
INSERT INTO infranexum_iam.iam_user(id,login,email,display_name,status,created_at,updated_at,deleted_at) SELECT id,username,NULL,display_name,CASE WHEN status='ACTIVE' THEN 'ACTIVE' ELSE 'SUSPENDED' END,created_at,updated_at,NULL FROM infranexum_iam.local_account ON CONFLICT (id) DO NOTHING;
INSERT INTO infranexum_iam.role_assignment(id,role_id,actor_type,actor_id,scope_kind,organization_id,subdivision_id,effective_from,effective_to,revoked_at,revoked_by) SELECT id,'019ffbda-1001-7e80-9ec8-7580467e9a85','USER',id,'PLATFORM',NULL,NULL,created_at,NULL,NULL,NULL FROM infranexum_iam.local_account ON CONFLICT (id) DO NOTHING;
