package io.infranexum.identity.access.domain;

/** Approved draft.21 IAM permission codes used by the PGM-03-E03 enforcement boundary. */
public final class PermissionCodes {
    private PermissionCodes() {}
    public static final String USER_CREATE="iam.user.create", USER_READ="iam.user.read", USER_UPDATE="iam.user.update", USER_DELETE="iam.user.delete", USER_SUSPEND="iam.user.suspend", USER_ACTIVATE="iam.user.activate", USER_ASSIGN_ROLE="iam.user.assign_role", USER_MANAGE_MEMBERSHIP="iam.user.manage_membership", USER_SEARCH="iam.user.search";
    public static final String GROUP_CREATE="iam.group.create", GROUP_READ="iam.group.read", GROUP_UPDATE="iam.group.update", GROUP_DELETE="iam.group.delete", GROUP_ADD_MEMBER="iam.group.add_member", GROUP_REMOVE_MEMBER="iam.group.remove_member", GROUP_ADD_GROUP="iam.group.add_group", GROUP_REMOVE_GROUP="iam.group.remove_group", GROUP_ASSIGN_ROLE="iam.group.assign_role", GROUP_SEARCH="iam.group.search";
    public static final String ROLE_CREATE="iam.role.create", ROLE_READ="iam.role.read", ROLE_UPDATE="iam.role.update", ROLE_DELETE="iam.role.delete", ROLE_ASSIGN="iam.role.assign", ROLE_UNASSIGN="iam.role.unassign", ROLE_SEARCH="iam.role.search";
    public static final String PERMISSION_CREATE="iam.permission.create", PERMISSION_READ="iam.permission.read", PERMISSION_UPDATE="iam.permission.update", PERMISSION_DELETE="iam.permission.delete", PERMISSION_SEARCH="iam.permission.search", PERMISSION_ASSIGN="iam.permission.assign", PERMISSION_REVOKE="iam.permission.revoke", PERMISSION_EVALUATE="iam.permission.evaluate";
    public static final String PLATFORM_PROFILE_READ="platform.profile.read", PLATFORM_CAPABILITY_READ="platform.capability.read";
    public static final String INTEGRATIONS_CONNECTOR_READ="integrations.connector.read", INTEGRATIONS_CONNECTOR_RESUME="integrations.connector.resume", INTEGRATIONS_DLQ_READ="integrations.dlq.read", INTEGRATIONS_DLQ_REPLAY="integrations.dlq.replay";
    public static final String INTEGRATIONS_NOTIFICATION_READ="integrations.notification.read", INTEGRATIONS_NOTIFICATION_PUBLISH="integrations.notification.publish", INTEGRATIONS_NOTIFICATION_REPLAY="integrations.notification.replay", INTEGRATIONS_NOTIFICATION_RESUME="integrations.notification.resume";
    public static final String INTEGRATIONS_SYNC_READ="integrations.sync.read", INTEGRATIONS_SYNC_EXECUTE="integrations.sync.execute", INTEGRATIONS_SYNC_COMPENSATE="integrations.sync.compensate";
    public static final String RSOT_SCHEMA_CREATE="rsot.schema.create", RSOT_SCHEMA_READ="rsot.schema.read", RSOT_SCHEMA_UPDATE="rsot.schema.update", RSOT_SCHEMA_DEPRECATE="rsot.schema.deprecate", RSOT_SCHEMA_PUBLISH="rsot.schema.publish", RSOT_READ="rsot.read", RSOT_AUDIT="rsot.audit";
    public static final String ITAM_PARTNER_READ="itam.partner.read", ITAM_PARTNER_CREATE="itam.partner.create", ITAM_PARTNER_UPDATE="itam.partner.update", ITAM_PARTNER_APPROVE="itam.partner.approve", ITAM_PARTNER_SUSPEND="itam.partner.suspend", ITAM_AUDIT_READ="itam.audit.read";
    public static final String ITAM_ASSET_READ="itam.asset.read", ITAM_ASSET_CREATE="itam.asset.create", ITAM_ASSET_UPDATE="itam.asset.update";
    public static final String ITAM_WARRANTY_READ="itam.warranty.read", ITAM_WARRANTY_MANAGE="itam.warranty.manage";
    public static final String ITAM_SUPPORT_COVERAGE_READ="itam.support_coverage.read", ITAM_SUPPORT_COVERAGE_MANAGE="itam.support_coverage.manage", ITAM_SUPPORT_CATALOG_MANAGE="itam.support_catalog.manage";
    public static final String ITAM_LICENSE_READ="itam.license.read", ITAM_LICENSE_MANAGE="itam.license.manage";
    public static final String DCIM_SITE_READ="dcim.site.read", DCIM_SITE_CREATE="dcim.site.create", DCIM_SITE_UPDATE="dcim.site.update", DCIM_SITE_ARCHIVE="dcim.site.archive", DCIM_SITE_DELETE="dcim.site.delete", DCIM_SITE_AUDIT="dcim.site.audit";
    public static final String DCIM_BUILDING_READ="dcim.building.read", DCIM_BUILDING_CREATE="dcim.building.create", DCIM_BUILDING_UPDATE="dcim.building.update", DCIM_BUILDING_ARCHIVE="dcim.building.archive", DCIM_BUILDING_DELETE="dcim.building.delete";
    public static final String DCIM_FLOOR_READ="dcim.floor.read", DCIM_FLOOR_CREATE="dcim.floor.create", DCIM_FLOOR_UPDATE="dcim.floor.update", DCIM_FLOOR_ARCHIVE="dcim.floor.archive", DCIM_FLOOR_DELETE="dcim.floor.delete";
    public static final String DCIM_ROOM_READ="dcim.room.read", DCIM_ROOM_CREATE="dcim.room.create", DCIM_ROOM_UPDATE="dcim.room.update", DCIM_ROOM_LOCK="dcim.room.lock", DCIM_ROOM_ARCHIVE="dcim.room.archive", DCIM_ROOM_DELETE="dcim.room.delete";
    public static final String DCIM_ZONE_READ="dcim.zone.read", DCIM_ZONE_CREATE="dcim.zone.create", DCIM_ZONE_UPDATE="dcim.zone.update", DCIM_ZONE_DELETE="dcim.zone.delete";
    public static final String DCIM_MODEL_READ="dcim.model.read", DCIM_MODEL_CREATE="dcim.model.create", DCIM_MODEL_UPDATE="dcim.model.update", DCIM_MODEL_ARCHIVE="dcim.model.archive";
    public static final String DCIM_RACK_READ="dcim.rack.read", DCIM_RACK_CREATE="dcim.rack.create", DCIM_RACK_UPDATE="dcim.rack.update", DCIM_RACK_DECOMMISSION="dcim.rack.decommission";
    public static final String DCIM_EQUIPMENT_READ="dcim.equipment.read", DCIM_EQUIPMENT_CREATE="dcim.equipment.create", DCIM_EQUIPMENT_UPDATE="dcim.equipment.update", DCIM_EQUIPMENT_MOVE="dcim.equipment.move", DCIM_EQUIPMENT_DECOMMISSION="dcim.equipment.decommission";
    public static final String DCIM_PORT_READ="dcim.port.read", DCIM_CABLE_READ="dcim.cable.read", DCIM_CABLE_CREATE="dcim.cable.create", DCIM_CABLE_DISCONNECT="dcim.cable.disconnect";
    public static final String DDI_IPAM_READ="ddi.ipam.read", DDI_IPAM_VRF_CREATE="ddi.ipam.vrf.create", DDI_IPAM_VRF_UPDATE="ddi.ipam.vrf.update", DDI_IPAM_VLAN_CREATE="ddi.ipam.vlan.create", DDI_IPAM_VLAN_UPDATE="ddi.ipam.vlan.update", DDI_IPAM_NETWORK_CREATE="ddi.ipam.network.create", DDI_IPAM_NETWORK_UPDATE="ddi.ipam.network.update", DDI_IPAM_POOL_CREATE="ddi.ipam.pool.create", DDI_IPAM_ADDRESS_READ="ddi.ipam.address.read", DDI_IPAM_ADDRESS_ALLOCATE="ddi.ipam.address.allocate", DDI_IPAM_ADDRESS_RELEASE="ddi.ipam.address.release", DDI_IPAM_AUDIT_READ="ddi.ipam.audit.read";
    public static final String ORGANIZATION_CREATE="organization.create", ORGANIZATION_SUSPEND="organization.suspend";
    public static final String SUBDIVISION_CREATE="organization.subdivision.create", SUBDIVISION_READ="organization.subdivision.read", SUBDIVISION_SEARCH="organization.subdivision.search", SUBDIVISION_UPDATE="organization.subdivision.update", SUBDIVISION_DELETE="organization.subdivision.delete", SUBDIVISION_VIEW_RESOURCES="organization.subdivision.view_resources";
}
