package io.infranexum.server.ddi;

import io.infranexum.ddi.ipam.domain.*;
import jakarta.validation.constraints.*;
import java.time.Instant;

final class IpamApiModels {private IpamApiModels(){}
 record CreateVrfRequest(@NotBlank String organizationId,@NotBlank @Size(max=64) String code,@NotBlank @Size(max=160) String displayName,@Size(max=128) String routeDistinguisher,@NotBlank @Size(min=2,max=1024) String reason){}
 record CreateVlanRequest(@NotBlank String organizationId,String siteId,@Min(1) @Max(4094) Integer vlanId,@Min(1) @Max(16777215) Long vni,@NotBlank @Size(max=160) String name,@NotBlank @Size(min=2,max=1024) String reason){}
 record CreateNetworkRequest(@NotBlank String organizationId,String subdivisionId,String siteId,@NotBlank String vrfId,String vlanId,String parentNetworkId,@NotBlank String kind,@NotBlank @Size(max=64) String cidr,@Size(max=160) String usage,@Size(max=64) String trustLevel,@NotBlank @Size(min=2,max=1024) String reason){}
 record UpdateNetworkRequest(String vlanId,@Size(max=160) String usage,@Size(max=64) String trustLevel,@NotBlank @Size(min=2,max=1024) String reason){}
 record CreatePoolRequest(@NotBlank String organizationId,@NotBlank String networkId,@NotBlank @Size(max=45) String startAddress,@NotBlank @Size(max=45) String endAddress,@NotBlank @Size(max=160) String name,@NotBlank @Size(min=2,max=1024) String reason){}
 record AllocateAddressRequest(@NotBlank String organizationId,@NotBlank String vrfId,@NotBlank String networkId,String poolId,@Size(max=45) String requestedAddress,boolean reservation,@Size(max=253) String hostname,String rsotObjectId,String dcimEquipmentId,@Size(max=512) String purpose,@NotBlank @Size(min=2,max=1024) String reason){}
 record StatusRequest(@NotBlank String targetStatus,@NotBlank @Size(min=2,max=1024) String reason){} record ReasonRequest(@NotBlank @Size(min=2,max=1024) String reason){}
 record VrfResponse(String id,String organizationId,String code,String displayName,String routeDistinguisher,String status,long version,Instant createdAt,Instant updatedAt){static VrfResponse from(IpamVrf x){return new VrfResponse(x.id().toString(),x.organizationId().toString(),x.code(),x.displayName(),x.routeDistinguisher(),x.status().wireValue(),x.version(),x.createdAt(),x.updatedAt());}}
 record VlanResponse(String id,String organizationId,String siteId,Integer vlanId,Long vni,String name,String status,long version,Instant createdAt,Instant updatedAt){static VlanResponse from(IpamVlan x){return new VlanResponse(x.id().toString(),x.organizationId().toString(),x.siteId()==null?null:x.siteId().toString(),x.vlanId(),x.vni(),x.name(),x.status().wireValue(),x.version(),x.createdAt(),x.updatedAt());}}
 record NetworkResponse(String id,String organizationId,String subdivisionId,String siteId,String vrfId,String vlanId,String parentNetworkId,String kind,String cidr,String usage,String trustLevel,String status,String addressCount,long version,Instant createdAt,Instant updatedAt){static NetworkResponse from(IpamNetwork x){return new NetworkResponse(x.id().toString(),x.organizationId().toString(),s(x.subdivisionId()),s(x.siteId()),x.vrfId().toString(),s(x.vlanId()),s(x.parentNetworkId()),x.kind().wireValue(),x.cidr().value(),x.usage(),x.trustLevel(),x.status().wireValue(),x.addressCount().toString(),x.version(),x.createdAt(),x.updatedAt());}}
 record PoolResponse(String id,String organizationId,String networkId,String startAddress,String endAddress,String name,String status,long version,Instant createdAt,Instant updatedAt){static PoolResponse from(IpamPool x){return new PoolResponse(x.id().toString(),x.organizationId().toString(),x.networkId().toString(),x.startAddress(),x.endAddress(),x.name(),x.status().wireValue(),x.version(),x.createdAt(),x.updatedAt());}}
 record AddressResponse(String id,String organizationId,String vrfId,String networkId,String poolId,String address,String status,String hostname,String rsotObjectId,String dcimEquipmentId,String purpose,long version,Instant createdAt,Instant updatedAt){static AddressResponse from(IpamAddress x){return new AddressResponse(x.id().toString(),x.organizationId().toString(),x.vrfId().toString(),x.networkId().toString(),s(x.poolId()),x.address(),x.status().wireValue(),x.hostname(),s(x.rsotObjectId()),s(x.dcimEquipmentId()),x.purpose(),x.version(),x.createdAt(),x.updatedAt());}}
 private static String s(io.infranexum.core.contracts.DomainIdentifier id){return id==null?null:id.toString();}
}
