package io.infranexum.server.ddi;

import static io.infranexum.server.ddi.IpamApiModels.*;
import io.infranexum.core.contracts.*;
import io.infranexum.ddi.ipam.application.*;
import io.infranexum.ddi.ipam.domain.*;
import io.infranexum.identity.access.domain.*;
import io.infranexum.server.http.ApiPagination;
import io.infranexum.server.identity.LocalAuthenticationFilter;
import io.infranexum.server.identityaccess.*;
import io.infranexum.server.observability.CorrelationContext;
import jakarta.servlet.http.*;
import jakarta.validation.Valid;
import java.util.*;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;

/** Organization-scoped HTTP boundary for PGM-08-E01 IPAM. */
@RestController @ConditionalOnProperty(name="infranexum.ddi.ipam-api-enabled",havingValue="true") @RequestMapping("/api/v1/ddi/ipam")
public final class IpamController {private final IpamApplicationService service;private final ScopedAuthorizationGuard auth;private final UuidV7Generator ids;public IpamController(IpamApplicationService s,ScopedAuthorizationGuard a,@Qualifier("correlationIdentifiers") UuidV7Generator i){service=Objects.requireNonNull(s);auth=Objects.requireNonNull(a);ids=Objects.requireNonNull(i);}
 @GetMapping("/vrfs") ResponseEntity<List<VrfResponse>> vrfs(@RequestParam(name="organization_id") String org,@RequestParam(required=false) String cursor,@RequestParam(defaultValue="100") int limit,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(org);require(q,p,PermissionCodes.DDI_IPAM_READ,o,"ddi-vrf","collection");var page=service.vrfs(o,nid(cursor),limit);return ApiPagination.cursor(page.items().stream().map(VrfResponse::from).toList(),text(page.nextCursor()),limit);}
 @PostMapping("/vrfs") ResponseEntity<VrfResponse> createVrf(@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody CreateVrfRequest b,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(b.organizationId());require(q,p,PermissionCodes.DDI_IPAM_VRF_CREATE,o,"ddi-vrf","collection");var x=service.createVrf(new CreateVrfCommand(o,b.code(),b.displayName(),b.routeDistinguisher()),ctx(q,b.reason(),idem));return response(VrfResponse.from(x),x.version(),HttpStatus.CREATED);}
 @PostMapping("/vrfs/{id}/status") ResponseEntity<VrfResponse> vrfStatus(@PathVariable String id,@RequestHeader(HttpHeaders.IF_MATCH) String etag,@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody StatusRequest b,HttpServletRequest q,HttpServletResponse p){var x=service.vrf(id(id));require(q,p,PermissionCodes.DDI_IPAM_VRF_UPDATE,x.organizationId(),"ddi-vrf",x.id().toString());var y=service.changeVrfStatus(x.id(),version(etag),IpamStatus.parse(b.targetStatus()),ctx(q,b.reason(),idem));return response(VrfResponse.from(y),y.version(),HttpStatus.OK);}
 @GetMapping("/vlans") ResponseEntity<List<VlanResponse>> vlans(@RequestParam(name="organization_id") String org,@RequestParam(required=false) String cursor,@RequestParam(defaultValue="100") int limit,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(org);require(q,p,PermissionCodes.DDI_IPAM_READ,o,"ddi-vlan","collection");var page=service.vlans(o,nid(cursor),limit);return ApiPagination.cursor(page.items().stream().map(VlanResponse::from).toList(),text(page.nextCursor()),limit);}
 @PostMapping("/vlans") ResponseEntity<VlanResponse> createVlan(@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody CreateVlanRequest b,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(b.organizationId());require(q,p,PermissionCodes.DDI_IPAM_VLAN_CREATE,o,"ddi-vlan","collection");var x=service.createVlan(new CreateVlanCommand(o,nid(b.siteId()),b.vlanId(),b.vni(),b.name()),ctx(q,b.reason(),idem));return response(VlanResponse.from(x),x.version(),HttpStatus.CREATED);}
 @PostMapping("/vlans/{id}/status") ResponseEntity<VlanResponse> vlanStatus(@PathVariable String id,@RequestHeader(HttpHeaders.IF_MATCH) String etag,@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody StatusRequest b,HttpServletRequest q,HttpServletResponse p){var x=service.vlan(id(id));require(q,p,PermissionCodes.DDI_IPAM_VLAN_UPDATE,x.organizationId(),"ddi-vlan",x.id().toString());var y=service.changeVlanStatus(x.id(),version(etag),IpamStatus.parse(b.targetStatus()),ctx(q,b.reason(),idem));return response(VlanResponse.from(y),y.version(),HttpStatus.OK);}
 @GetMapping("/networks") ResponseEntity<List<NetworkResponse>> networks(@RequestParam(name="organization_id") String org,@RequestParam(name="vrf_id",required=false) String vrf,@RequestParam(required=false) String cursor,@RequestParam(defaultValue="100") int limit,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(org);require(q,p,PermissionCodes.DDI_IPAM_READ,o,"ddi-network","collection");var page=service.networks(o,nid(vrf),nid(cursor),limit);return ApiPagination.cursor(page.items().stream().map(NetworkResponse::from).toList(),text(page.nextCursor()),limit);}
 @PostMapping("/networks") ResponseEntity<NetworkResponse> createNetwork(@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody CreateNetworkRequest b,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(b.organizationId());require(q,p,PermissionCodes.DDI_IPAM_NETWORK_CREATE,o,"ddi-network","collection");var x=service.createNetwork(new CreateNetworkCommand(o,nid(b.subdivisionId()),nid(b.siteId()),id(b.vrfId()),nid(b.vlanId()),nid(b.parentNetworkId()),NetworkKind.parse(b.kind()),b.cidr(),b.usage(),b.trustLevel()),ctx(q,b.reason(),idem));return response(NetworkResponse.from(x),x.version(),HttpStatus.CREATED);}
 @PatchMapping("/networks/{id}") ResponseEntity<NetworkResponse> updateNetwork(@PathVariable String id,@RequestHeader(HttpHeaders.IF_MATCH) String etag,@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody UpdateNetworkRequest b,HttpServletRequest q,HttpServletResponse p){var x=service.network(id(id));require(q,p,PermissionCodes.DDI_IPAM_NETWORK_UPDATE,x.organizationId(),"ddi-network",x.id().toString());var y=service.updateNetwork(x.id(),version(etag),new UpdateNetworkCommand(nid(b.vlanId()),b.usage(),b.trustLevel()),ctx(q,b.reason(),idem));return response(NetworkResponse.from(y),y.version(),HttpStatus.OK);}
 @PostMapping("/networks/{id}/status") ResponseEntity<NetworkResponse> networkStatus(@PathVariable String id,@RequestHeader(HttpHeaders.IF_MATCH) String etag,@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody StatusRequest b,HttpServletRequest q,HttpServletResponse p){var x=service.network(id(id));require(q,p,PermissionCodes.DDI_IPAM_NETWORK_UPDATE,x.organizationId(),"ddi-network",x.id().toString());var y=service.changeNetworkStatus(x.id(),version(etag),IpamStatus.parse(b.targetStatus()),ctx(q,b.reason(),idem));return response(NetworkResponse.from(y),y.version(),HttpStatus.OK);}
 @GetMapping("/networks/{id}/pools") ResponseEntity<List<PoolResponse>> pools(@PathVariable String id,@RequestParam(required=false) String cursor,@RequestParam(defaultValue="100") int limit,HttpServletRequest q,HttpServletResponse p){var n=service.network(id(id));require(q,p,PermissionCodes.DDI_IPAM_READ,n.organizationId(),"ddi-pool","collection");var page=service.pools(n.id(),nid(cursor),limit);return ApiPagination.cursor(page.items().stream().map(PoolResponse::from).toList(),text(page.nextCursor()),limit);}
 @PostMapping("/pools") ResponseEntity<PoolResponse> createPool(@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody CreatePoolRequest b,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(b.organizationId());require(q,p,PermissionCodes.DDI_IPAM_POOL_CREATE,o,"ddi-pool","collection");var x=service.createPool(new CreatePoolCommand(o,id(b.networkId()),b.startAddress(),b.endAddress(),b.name()),ctx(q,b.reason(),idem));return response(PoolResponse.from(x),x.version(),HttpStatus.CREATED);}
 @GetMapping("/addresses") ResponseEntity<List<AddressResponse>> addresses(@RequestParam(name="organization_id") String org,@RequestParam(name="vrf_id",required=false) String vrf,@RequestParam(name="network_id",required=false) String net,@RequestParam(required=false) String cursor,@RequestParam(defaultValue="100") int limit,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(org);require(q,p,PermissionCodes.DDI_IPAM_ADDRESS_READ,o,"ddi-address","collection");var page=service.addresses(o,nid(vrf),nid(net),nid(cursor),limit);return ApiPagination.cursor(page.items().stream().map(AddressResponse::from).toList(),text(page.nextCursor()),limit);}
 @PostMapping("/addresses") ResponseEntity<AddressResponse> allocate(@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody AllocateAddressRequest b,HttpServletRequest q,HttpServletResponse p){DomainIdentifier o=id(b.organizationId());require(q,p,PermissionCodes.DDI_IPAM_ADDRESS_ALLOCATE,o,"ddi-address","collection");var x=service.allocate(new AllocateAddressCommand(o,id(b.vrfId()),id(b.networkId()),nid(b.poolId()),b.requestedAddress(),b.reservation(),b.hostname(),nid(b.rsotObjectId()),nid(b.dcimEquipmentId()),b.purpose()),ctx(q,b.reason(),idem));return response(AddressResponse.from(x),x.version(),HttpStatus.CREATED);}
 @PostMapping("/addresses/{id}/release") ResponseEntity<AddressResponse> release(@PathVariable String id,@RequestHeader(HttpHeaders.IF_MATCH) String etag,@RequestHeader("Idempotency-Key") String idem,@Valid @RequestBody ReasonRequest b,HttpServletRequest q,HttpServletResponse p){var x=service.address(id(id));require(q,p,PermissionCodes.DDI_IPAM_ADDRESS_RELEASE,x.organizationId(),"ddi-address",x.id().toString());var y=service.release(x.id(),version(etag),ctx(q,b.reason(),idem));return response(AddressResponse.from(y),y.version(),HttpStatus.OK);}
 private void require(HttpServletRequest q,HttpServletResponse p,String perm,DomainIdentifier org,String type,String target){auth.require(q,p,perm,AuthorizationScope.organization(org),type,target);}private IpamCommandContext ctx(HttpServletRequest q,String reason,String idem){DomainIdentifier actor=(DomainIdentifier)q.getAttribute(LocalAuthenticationFilter.ACCOUNT_ATTRIBUTE);DomainIdentifier corr=CorrelationContext.identifier(q).orElseGet(ids::next);return new IpamCommandContext(actor,corr,reason,idem);}private static DomainIdentifier id(String v){return DomainIdentifier.parse(v);}private static DomainIdentifier nid(String v){return v==null||v.isBlank()?null:id(v);}private static String text(DomainIdentifier v){return v==null?null:v.toString();}private static long version(String e){if(e==null||!e.matches("\"ver-[1-9][0-9]*\""))throw new IllegalArgumentException("If-Match must be a strong ver-N ETag");return Long.parseLong(e.substring(5,e.length()-1));}private static <T>ResponseEntity<T> response(T body,long v,HttpStatus status){return ResponseEntity.status(status).eTag("\"ver-"+v+"\"").body(body);}}
