package io.infranexum.server.ddi;

import io.infranexum.adapters.persistence.jdbc.*;
import io.infranexum.core.contracts.DomainIdentifier;
import io.infranexum.ddi.ipam.domain.IpamConflictException;
import io.infranexum.ddi.ipam.ports.IpamReferencePolicy;
import io.infranexum.dcim.facility.domain.*;
import io.infranexum.organization.domain.*;
import java.util.Objects;

/** Resolves all DDI/IPAM weak references against their authoritative contexts. */
public final class IpamReferencePolicyAdapter implements IpamReferencePolicy {private final JdbcOrganizationRepository organizations;private final JdbcSubdivisionRepository subdivisions;private final JdbcFacilityRepository facilities;private final JdbcRsotRepository rsot;private final JdbcDcimPhysicalRepository physical;public IpamReferencePolicyAdapter(JdbcOrganizationRepository o,JdbcSubdivisionRepository s,JdbcFacilityRepository f,JdbcRsotRepository r,JdbcDcimPhysicalRepository p){organizations=Objects.requireNonNull(o);subdivisions=Objects.requireNonNull(s);facilities=Objects.requireNonNull(f);rsot=Objects.requireNonNull(r);physical=Objects.requireNonNull(p);}@Override public void requireOrganization(DomainIdentifier org){var x=organizations.findById(org).orElseThrow(()->bad("DDI_ORGANIZATION_INVALID","organization does not exist"));if(x.state()!=OrganizationState.ACTIVE)throw bad("DDI_ORGANIZATION_INACTIVE","organization must be active");}@Override public void requireSubdivisionIfPresent(DomainIdentifier org,DomainIdentifier sub){if(sub==null)return;var x=subdivisions.findById(org,sub).orElseThrow(()->bad("DDI_SUBDIVISION_INVALID","subdivision does not exist in organization"));if(x.state()!=SubdivisionState.ACTIVE)throw bad("DDI_SUBDIVISION_INACTIVE","subdivision must be active");}@Override public void requireSiteIfPresent(DomainIdentifier org,DomainIdentifier sub,DomainIdentifier site){if(site==null)return;var x=facilities.findById(site).orElseThrow(()->bad("DDI_SITE_INVALID","site does not exist"));if(x.kind()!=FacilityKind.SITE||x.status()!=FacilityStatus.ACTIVE||!x.organizationId().equals(org)||(sub!=null&&!x.subdivisionId().equals(sub)))throw bad("DDI_SITE_INVALID","site must be active and belong to requested scope");}@Override public void requireRsotIfPresent(DomainIdentifier org,DomainIdentifier id){if(id==null)return;var x=rsot.findCanonicalObject(id).orElseThrow(()->bad("DDI_RSOT_INVALID","RSOT object does not exist"));if(!x.organizationId().equals(org))throw bad("DDI_SCOPE_MISMATCH","RSOT object belongs to another organization");}@Override public void requireDcimEquipmentIfPresent(DomainIdentifier org,DomainIdentifier id){if(id==null)return;var x=physical.equipment(id).orElseThrow(()->bad("DDI_DCIM_EQUIPMENT_INVALID","DCIM equipment does not exist"));if(!x.organizationId().equals(org))throw bad("DDI_SCOPE_MISMATCH","DCIM equipment belongs to another organization");}private static IpamConflictException bad(String c,String m){return new IpamConflictException(c,m);}}
