-- Add durable request correlation metadata to background tasks.
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_WORKER_TASK ADD (CORRELATION_ID VARCHAR2(36 CHAR))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_WORKER_TASK DROP CONSTRAINT CK_INX_WORKER_CORRELATION_V7';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

ALTER TABLE INFRANEXUM_CORE_WORKER_TASK ADD CONSTRAINT CK_INX_WORKER_CORRELATION_V7 CHECK (
  CORRELATION_ID IS NULL
  OR REGEXP_LIKE(CORRELATION_ID, '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$')
);
