-- InfraNexum migration 0002: Core-local transactional outbox and inbox for Oracle 19c/26ai.
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_OUTBOX_EVENT (
        EVENT_ID CHAR(36 CHAR) PRIMARY KEY,
        EVENT_TYPE VARCHAR2(200 CHAR) NOT NULL,
        SCHEMA_VERSION VARCHAR2(32 CHAR) NOT NULL,
        OCCURRED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
        EVENT_SOURCE VARCHAR2(255 CHAR) NOT NULL,
        CORRELATION_ID CHAR(36 CHAR) NOT NULL,
        CAUSATION_ID CHAR(36 CHAR) NULL,
        PAYLOAD_JSON CLOB NOT NULL,
        STATUS VARCHAR2(16 CHAR) DEFAULT ''PENDING'' NOT NULL,
        ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
        AVAILABLE_AT TIMESTAMP WITH TIME ZONE NOT NULL,
        LEASE_OWNER VARCHAR2(160 CHAR) NULL,
        LEASE_UNTIL TIMESTAMP WITH TIME ZONE NULL,
        PUBLISHED_AT TIMESTAMP WITH TIME ZONE NULL,
        LAST_FAILURE VARCHAR2(1024 CHAR) NULL,
        CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT CK_INX_OUTBOX_EVENT_ID CHECK (
            REGEXP_LIKE(EVENT_ID, ''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')
        ),
        CONSTRAINT CK_INX_OUTBOX_CORREL_ID CHECK (
            REGEXP_LIKE(CORRELATION_ID, ''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')
        ),
        CONSTRAINT CK_INX_OUTBOX_CAUS_ID CHECK (
            CAUSATION_ID IS NULL OR REGEXP_LIKE(CAUSATION_ID, ''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')
        ),
        CONSTRAINT CK_INX_OUTBOX_EVENT_TYPE CHECK (
            REGEXP_LIKE(EVENT_TYPE, ''^[a-z][a-z0-9]*(\.[a-z][a-z0-9-]*){2,7}\.v[1-9][0-9]*$'')
        ),
        CONSTRAINT CK_INX_OUTBOX_SCHEMA_VER CHECK (
            REGEXP_LIKE(SCHEMA_VERSION, ''^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'')
        ),
        CONSTRAINT CK_INX_OUTBOX_SOURCE CHECK (LENGTH(TRIM(EVENT_SOURCE)) > 0),
        CONSTRAINT CK_INX_OUTBOX_PAYLOAD CHECK (PAYLOAD_JSON IS JSON),
        CONSTRAINT CK_INX_OUTBOX_STATUS CHECK (STATUS IN (''PENDING'', ''IN_FLIGHT'', ''PUBLISHED'', ''DEAD_LETTER'')),
        CONSTRAINT CK_INX_OUTBOX_ATTEMPTS CHECK (ATTEMPTS >= 0),
        CONSTRAINT CK_INX_OUTBOX_LEASE CHECK (
            (STATUS = ''IN_FLIGHT'' AND LEASE_OWNER IS NOT NULL AND LEASE_UNTIL IS NOT NULL)
            OR (STATUS <> ''IN_FLIGHT'' AND LEASE_OWNER IS NULL AND LEASE_UNTIL IS NULL)
        ),
        CONSTRAINT CK_INX_OUTBOX_PUBLISHED CHECK (
            (STATUS = ''PUBLISHED'' AND PUBLISHED_AT IS NOT NULL)
            OR (STATUS <> ''PUBLISHED'' AND PUBLISHED_AT IS NULL)
        )
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_OUTBOX_DISPATCH
        ON INFRANEXUM_CORE_OUTBOX_EVENT (STATUS, AVAILABLE_AT, OCCURRED_AT, EVENT_ID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_OUTBOX_LEASE
        ON INFRANEXUM_CORE_OUTBOX_EVENT (LEASE_UNTIL, STATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_INBOX_RECEIPT (
        CONSUMER_NAME VARCHAR2(160 CHAR) NOT NULL,
        EVENT_ID CHAR(36 CHAR) NOT NULL,
        EVENT_TYPE VARCHAR2(200 CHAR) NOT NULL,
        PAYLOAD_SHA256 CHAR(64 CHAR) NOT NULL,
        RECEIVED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
        COMPLETED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
        CONSTRAINT PK_INX_INBOX_RECEIPT PRIMARY KEY (CONSUMER_NAME, EVENT_ID),
        CONSTRAINT CK_INX_INBOX_EVENT_ID CHECK (
            REGEXP_LIKE(EVENT_ID, ''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')
        ),
        CONSTRAINT CK_INX_INBOX_EVENT_TYPE CHECK (
            REGEXP_LIKE(EVENT_TYPE, ''^[a-z][a-z0-9]*(\.[a-z][a-z0-9-]*){2,7}\.v[1-9][0-9]*$'')
        ),
        CONSTRAINT CK_INX_INBOX_COMPLETED CHECK (COMPLETED_AT >= RECEIVED_AT),
        CONSTRAINT CK_INX_INBOX_SHA256 CHECK (REGEXP_LIKE(PAYLOAD_SHA256, ''^[0-9a-f]{64}$''))
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_INBOX_COMPLETED
        ON INFRANEXUM_CORE_INBOX_RECEIPT (COMPLETED_AT, CONSUMER_NAME)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
