-- InfraNexum migration 0038: durable connector synchronization runs and checkpoints for Oracle.
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_SYNC_STATE (
    CONNECTOR_KEY VARCHAR2(80 CHAR) NOT NULL,
    CURRENT_REVISION NUMBER(19) DEFAULT 0 NOT NULL,
    CURSOR_VALUE VARCHAR2(2048 CHAR) NULL,
    CURSOR_SHA256 CHAR(64 CHAR) NOT NULL,
    ACTIVE_RUN_ID CHAR(36 CHAR) NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INX_SYNC_STATE PRIMARY KEY(CONNECTOR_KEY),
    CONSTRAINT CK_INX_SYNC_STATE_KEY CHECK (REGEXP_LIKE(CONNECTOR_KEY,''^[a-z0-9][a-z0-9._-]{2,79}$'')),
    CONSTRAINT CK_INX_SYNC_STATE_REV CHECK (CURRENT_REVISION>=0),
    CONSTRAINT CK_INX_SYNC_STATE_HASH CHECK (REGEXP_LIKE(CURSOR_SHA256,''^[0-9a-f]{64}$''))
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_SYNC_RUN (
    RUN_ID CHAR(36 CHAR) NOT NULL,
    CONNECTOR_KEY VARCHAR2(80 CHAR) NOT NULL,
    PROVIDER VARCHAR2(80 CHAR) NOT NULL,
    DIRECTION VARCHAR2(20 CHAR) NOT NULL,
    ROLLBACK_STRATEGY VARCHAR2(24 CHAR) NOT NULL,
    STATUS VARCHAR2(24 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(200 CHAR) NOT NULL,
    REQUEST_SHA256 CHAR(64 CHAR) NOT NULL,
    REQUESTED_FIELDS VARCHAR2(4096 CHAR) NOT NULL,
    PROPAGATE_DELETIONS NUMBER(1) NOT NULL,
    MAX_BATCHES NUMBER(3) NOT NULL,
    INITIAL_REVISION NUMBER(19) NOT NULL,
    LAST_CHECKPOINT_REVISION NUMBER(19) NOT NULL,
    FAILURE_CODE VARCHAR2(64 CHAR) NULL,
    ACTOR_ID CHAR(36 CHAR) NOT NULL,
    CORRELATION_ID CHAR(36 CHAR) NOT NULL,
    STARTED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE NULL,
    COMPENSATION_CHECKPOINT_REVISION NUMBER(19) NULL,
    CONSTRAINT PK_INX_SYNC_RUN PRIMARY KEY(RUN_ID),
    CONSTRAINT UQ_INX_SYNC_RUN_IDEM UNIQUE(CONNECTOR_KEY,IDEMPOTENCY_KEY),
    CONSTRAINT CK_INX_SYNC_RUN_ID CHECK (SUBSTR(RUN_ID,15,1)=''7'' AND SUBSTR(RUN_ID,20,1) IN (''8'',''9'',''a'',''b'')),
    CONSTRAINT CK_INX_SYNC_RUN_KEY CHECK (REGEXP_LIKE(CONNECTOR_KEY,''^[a-z0-9][a-z0-9._-]{2,79}$'')),
    CONSTRAINT CK_INX_SYNC_PROVIDER CHECK (REGEXP_LIKE(PROVIDER,''^[a-z][a-z0-9-]{0,79}$'')),
    CONSTRAINT CK_INX_SYNC_DIRECTION CHECK (DIRECTION IN (''INBOUND'',''OUTBOUND'',''BIDIRECTIONAL'')),
    CONSTRAINT CK_INX_SYNC_ROLLBACK CHECK (ROLLBACK_STRATEGY IN (''LOCAL_CHECKPOINT'',''REMOTE_COMPENSATION'',''DUAL_COMPENSATION'',''MANUAL'')),
    CONSTRAINT CK_INX_SYNC_STATUS CHECK (STATUS IN (''RUNNING'',''PAUSED'',''SUCCEEDED'',''FAILED'',''COMPENSATING'',''COMPENSATED'',''COMPENSATION_FAILED'')),
    CONSTRAINT CK_INX_SYNC_IDEM CHECK (REGEXP_LIKE(IDEMPOTENCY_KEY,''^[A-Za-z0-9._:-]{8,200}$'')),
    CONSTRAINT CK_INX_SYNC_REQ_HASH CHECK (REGEXP_LIKE(REQUEST_SHA256,''^[0-9a-f]{64}$'')),
    CONSTRAINT CK_INX_SYNC_BATCHES CHECK (MAX_BATCHES BETWEEN 1 AND 100),
    CONSTRAINT CK_INX_SYNC_REVISIONS CHECK (INITIAL_REVISION>=0 AND LAST_CHECKPOINT_REVISION>=INITIAL_REVISION),
    CONSTRAINT CK_INX_SYNC_FAILURE CHECK (FAILURE_CODE IS NULL OR REGEXP_LIKE(FAILURE_CODE,''^[A-Z0-9_:-]{1,64}$''))
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_SYNC_RUN_CONNECTOR ON INFRANEXUM_SYNC_RUN(CONNECTOR_KEY,STARTED_AT,RUN_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_SYNC_RUN_STATUS ON INFRANEXUM_SYNC_RUN(STATUS,UPDATED_AT,RUN_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_SYNC_CHECKPOINT (
    CHECKPOINT_ID CHAR(36 CHAR) NOT NULL,
    CONNECTOR_KEY VARCHAR2(80 CHAR) NOT NULL,
    RUN_ID CHAR(36 CHAR) NOT NULL,
    REVISION NUMBER(19) NOT NULL,
    KIND VARCHAR2(16 CHAR) NOT NULL,
    CURSOR_VALUE VARCHAR2(2048 CHAR) NULL,
    CURSOR_SHA256 CHAR(64 CHAR) NOT NULL,
    PROCESSED_COUNT NUMBER(19) NOT NULL,
    CHANGED_COUNT NUMBER(19) NOT NULL,
    REJECTED_COUNT NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INX_SYNC_CHECKPOINT PRIMARY KEY(CHECKPOINT_ID),
    CONSTRAINT FK_INX_SYNC_CHECKPOINT_RUN FOREIGN KEY(RUN_ID) REFERENCES INFRANEXUM_SYNC_RUN(RUN_ID),
    CONSTRAINT UQ_INX_SYNC_CHECKPOINT_REV UNIQUE(CONNECTOR_KEY,REVISION),
    CONSTRAINT CK_INX_SYNC_CHECKPOINT_ID CHECK (SUBSTR(CHECKPOINT_ID,15,1)=''7'' AND SUBSTR(CHECKPOINT_ID,20,1) IN (''8'',''9'',''a'',''b'')),
    CONSTRAINT CK_INX_SYNC_CHECKPOINT_KEY CHECK (REGEXP_LIKE(CONNECTOR_KEY,''^[a-z0-9][a-z0-9._-]{2,79}$'')),
    CONSTRAINT CK_INX_SYNC_CHECKPOINT_REV CHECK (REVISION>=1),
    CONSTRAINT CK_INX_SYNC_CHECKPOINT_KIND CHECK (KIND IN (''PROGRESS'',''COMPENSATION'')),
    CONSTRAINT CK_INX_SYNC_CHECKPOINT_HASH CHECK (REGEXP_LIKE(CURSOR_SHA256,''^[0-9a-f]{64}$'')),
    CONSTRAINT CK_INX_SYNC_CHECKPOINT_COUNTS CHECK (PROCESSED_COUNT>=0 AND CHANGED_COUNT>=0 AND REJECTED_COUNT>=0 AND CHANGED_COUNT+REJECTED_COUNT<=PROCESSED_COUNT)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_SYNC_CHECKPOINT_RUN ON INFRANEXUM_SYNC_CHECKPOINT(RUN_ID,REVISION)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
