DELETE FROM INFRANEXUM_IAM_ROLE_PERMISSION WHERE PERMISSION_ID IN (SELECT ID FROM INFRANEXUM_IAM_PERMISSION WHERE ORGANIZATION_ID IS NULL AND CODE IN ('itam.asset.read','itam.asset.create','itam.asset.update'));
DELETE FROM INFRANEXUM_IAM_PERMISSION WHERE ORGANIZATION_ID IS NULL AND CODE IN ('itam.asset.read','itam.asset.create','itam.asset.update');
