BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_CORE_SCHEMA_PROFILE_MEMBER CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_CORE_SCHEMA_PROFILE CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_CORE_SCHEMA_REGISTRY CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
