package io.infranexum.dcim.physical.domain;

import io.infranexum.core.contracts.DomainIdentifier;
import java.time.Instant;
import java.util.Objects;

/** Auditable point-to-point physical cable connection between two DCIM ports. */
public final class CableConnection {
    private final DomainIdentifier id,organizationId,subdivisionId,portAId,portBId,createdBy,updatedBy; private final String label,media,connector,lastReason; private final PhysicalStatus status; private final long version; private final Instant createdAt,updatedAt;
    private CableConnection(DomainIdentifier id,DomainIdentifier org,DomainIdentifier sub,DomainIdentifier a,DomainIdentifier b,String label,String media,String connector,PhysicalStatus status,long version,Instant createdAt,Instant updatedAt,DomainIdentifier createdBy,DomainIdentifier updatedBy,String reason){this.id=Objects.requireNonNull(id,"id");this.organizationId=Objects.requireNonNull(org,"organizationId");this.subdivisionId=Objects.requireNonNull(sub,"subdivisionId");this.portAId=Objects.requireNonNull(a,"portAId");this.portBId=Objects.requireNonNull(b,"portBId");if(a.equals(b))throw new IllegalArgumentException("cable endpoints must differ");this.label=text(label,"label",1,128);this.media=text(media,"media",1,32).toLowerCase();this.connector=text(connector,"connector",1,32).toLowerCase();this.status=Objects.requireNonNull(status,"status");if(version<1)throw new IllegalArgumentException("version must be positive");this.version=version;this.createdAt=Objects.requireNonNull(createdAt,"createdAt");this.updatedAt=Objects.requireNonNull(updatedAt,"updatedAt");this.createdBy=Objects.requireNonNull(createdBy,"createdBy");this.updatedBy=Objects.requireNonNull(updatedBy,"updatedBy");this.lastReason=text(reason,"lastReason",2,1024);}
    public static CableConnection active(DomainIdentifier id,DomainIdentifier org,DomainIdentifier sub,DomainIdentifier a,DomainIdentifier b,String label,String media,String connector,DomainIdentifier actor,String reason,Instant now){return new CableConnection(id,org,sub,a,b,label,media,connector,PhysicalStatus.ACTIVE,1,now,now,actor,actor,reason);} public static CableConnection restore(DomainIdentifier id,DomainIdentifier org,DomainIdentifier sub,DomainIdentifier a,DomainIdentifier b,String label,String media,String connector,PhysicalStatus status,long version,Instant createdAt,Instant updatedAt,DomainIdentifier createdBy,DomainIdentifier updatedBy,String reason){return new CableConnection(id,org,sub,a,b,label,media,connector,status,version,createdAt,updatedAt,createdBy,updatedBy,reason);} public CableConnection disconnect(DomainIdentifier actor,String reason,Instant now){if(status!=PhysicalStatus.ACTIVE)throw new DcimPhysicalConflictException("DCIM_CABLE_NOT_ACTIVE","only active cable can be disconnected");return new CableConnection(id,organizationId,subdivisionId,portAId,portBId,label,media,connector,PhysicalStatus.DECOMMISSIONED,version+1,createdAt,now,createdBy,actor,reason);}
    public DomainIdentifier id(){return id;} public DomainIdentifier organizationId(){return organizationId;} public DomainIdentifier subdivisionId(){return subdivisionId;} public DomainIdentifier portAId(){return portAId;} public DomainIdentifier portBId(){return portBId;} public String label(){return label;} public String media(){return media;} public String connector(){return connector;} public PhysicalStatus status(){return status;} public long version(){return version;} public Instant createdAt(){return createdAt;} public Instant updatedAt(){return updatedAt;} public DomainIdentifier createdBy(){return createdBy;} public DomainIdentifier updatedBy(){return updatedBy;} public String lastReason(){return lastReason;} private static String text(String v,String f,int min,int max){String x=Objects.requireNonNull(v,f).strip();if(x.length()<min||x.length()>max||x.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException(f+" invalid");return x;}
}
