package io.infranexum.dcim.physical.domain;

import io.infranexum.core.contracts.DomainIdentifier;
import java.time.Instant;
import java.util.Objects;

/** Installed DCIM equipment instance with immutable model and governed rack footprint. */
public final class Equipment {
    private final DomainIdentifier id,organizationId,subdivisionId,rackId,modelId,rsotObjectId,itamAssetId,createdBy,updatedBy; private final String serialNumber,assetTag,face,lastReason; private final int startU; private final PhysicalStatus status; private final long version; private final Instant createdAt,updatedAt;
    private Equipment(DomainIdentifier id,DomainIdentifier org,DomainIdentifier sub,DomainIdentifier rack,DomainIdentifier model,DomainIdentifier rsot,DomainIdentifier itam,String serial,String assetTag,int startU,String face,PhysicalStatus status,long version,Instant createdAt,Instant updatedAt,DomainIdentifier createdBy,DomainIdentifier updatedBy,String reason){this.id=Objects.requireNonNull(id,"id");this.organizationId=Objects.requireNonNull(org,"organizationId");this.subdivisionId=Objects.requireNonNull(sub,"subdivisionId");this.rackId=Objects.requireNonNull(rack,"rackId");this.modelId=Objects.requireNonNull(model,"modelId");this.rsotObjectId=Objects.requireNonNull(rsot,"rsotObjectId");this.itamAssetId=itam;this.serialNumber=nullable(serial,128);this.assetTag=nullable(assetTag,128);if(startU<1||startU>100)throw new IllegalArgumentException("startU must be 1..100");this.startU=startU;this.face=face(face);this.status=Objects.requireNonNull(status,"status");if(version<1)throw new IllegalArgumentException("version must be positive");this.version=version;this.createdAt=Objects.requireNonNull(createdAt,"createdAt");this.updatedAt=Objects.requireNonNull(updatedAt,"updatedAt");this.createdBy=Objects.requireNonNull(createdBy,"createdBy");this.updatedBy=Objects.requireNonNull(updatedBy,"updatedBy");this.lastReason=text(reason,"lastReason",2,1024);}
    public static Equipment installed(DomainIdentifier id,DomainIdentifier org,DomainIdentifier sub,DomainIdentifier rack,DomainIdentifier model,DomainIdentifier rsot,DomainIdentifier itam,String serial,String assetTag,int startU,String face,DomainIdentifier actor,String reason,Instant now){return new Equipment(id,org,sub,rack,model,rsot,itam,serial,assetTag,startU,face,PhysicalStatus.ACTIVE,1,now,now,actor,actor,reason);} public static Equipment restore(DomainIdentifier id,DomainIdentifier org,DomainIdentifier sub,DomainIdentifier rack,DomainIdentifier model,DomainIdentifier rsot,DomainIdentifier itam,String serial,String assetTag,int startU,String face,PhysicalStatus status,long version,Instant createdAt,Instant updatedAt,DomainIdentifier createdBy,DomainIdentifier updatedBy,String reason){return new Equipment(id,org,sub,rack,model,rsot,itam,serial,assetTag,startU,face,status,version,createdAt,updatedAt,createdBy,updatedBy,reason);} public Equipment move(DomainIdentifier rack,int newStartU,String newFace,DomainIdentifier actor,String reason,Instant now){if(status==PhysicalStatus.DECOMMISSIONED||status==PhysicalStatus.ARCHIVED)throw new DcimPhysicalConflictException("DCIM_EQUIPMENT_IMMUTABLE","retired equipment cannot move");return new Equipment(id,organizationId,subdivisionId,rack,modelId,rsotObjectId,itamAssetId,serialNumber,assetTag,newStartU,newFace,status,version+1,createdAt,now,createdBy,actor,reason);} public Equipment changeStatus(PhysicalStatus target,DomainIdentifier actor,String reason,Instant now){if(status==PhysicalStatus.ARCHIVED)throw new DcimPhysicalConflictException("DCIM_EQUIPMENT_IMMUTABLE","archived equipment is immutable");return new Equipment(id,organizationId,subdivisionId,rackId,modelId,rsotObjectId,itamAssetId,serialNumber,assetTag,startU,face,target,version+1,createdAt,now,createdBy,actor,reason);}
    public DomainIdentifier id(){return id;} public DomainIdentifier organizationId(){return organizationId;} public DomainIdentifier subdivisionId(){return subdivisionId;} public DomainIdentifier rackId(){return rackId;} public DomainIdentifier modelId(){return modelId;} public DomainIdentifier rsotObjectId(){return rsotObjectId;} public DomainIdentifier itamAssetId(){return itamAssetId;} public String serialNumber(){return serialNumber;} public String assetTag(){return assetTag;} public int startU(){return startU;} public String face(){return face;} public PhysicalStatus status(){return status;} public long version(){return version;} public Instant createdAt(){return createdAt;} public Instant updatedAt(){return updatedAt;} public DomainIdentifier createdBy(){return createdBy;} public DomainIdentifier updatedBy(){return updatedBy;} public String lastReason(){return lastReason;} private static String face(String v){String x=text(v,"face",4,5).toLowerCase();if(!x.equals("front")&&!x.equals("rear"))throw new IllegalArgumentException("face must be front or rear");return x;} private static String nullable(String v,int max){return v==null||v.isBlank()?null:text(v,"value",1,max);} private static String text(String v,String f,int min,int max){String x=Objects.requireNonNull(v,f).strip();if(x.length()<min||x.length()>max||x.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException(f+" invalid");return x;}
}
