package io.infranexum.dcim.physical.domain;

import io.infranexum.core.contracts.DomainIdentifier;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Objects;

/** Canonical multi-manufacturer DCIM equipment footprint and port model. */
public final class EquipmentModel {
    private final DomainIdentifier id, organizationId, manufacturerPartnerId, createdBy, updatedBy;
    private final String code, displayName, formFactor, description, lastReason;
    private final int rackUnits, widthMm, depthMm;
    private final BigDecimal weightKg;
    private final List<PortTemplate> portTemplates;
    private final PhysicalStatus status;
    private final long version;
    private final Instant createdAt, updatedAt;
    private EquipmentModel(DomainIdentifier id,DomainIdentifier organizationId,DomainIdentifier manufacturerPartnerId,String code,String displayName,String formFactor,int rackUnits,int widthMm,int depthMm,BigDecimal weightKg,List<PortTemplate> portTemplates,PhysicalStatus status,String description,long version,Instant createdAt,Instant updatedAt,DomainIdentifier createdBy,DomainIdentifier updatedBy,String lastReason){
        this.id=Objects.requireNonNull(id,"id");this.organizationId=Objects.requireNonNull(organizationId,"organizationId");this.manufacturerPartnerId=Objects.requireNonNull(manufacturerPartnerId,"manufacturerPartnerId");this.code=token(code,"code",3,64);this.displayName=text(displayName,"displayName",3,128);this.formFactor=token(formFactor,"formFactor",2,32);if(rackUnits<1||rackUnits>100)throw new IllegalArgumentException("rackUnits must be 1..100");if(widthMm<1||widthMm>5000||depthMm<1||depthMm>5000)throw new IllegalArgumentException("model dimensions are invalid");this.rackUnits=rackUnits;this.widthMm=widthMm;this.depthMm=depthMm;this.weightKg=positive(weightKg,"weightKg");this.portTemplates=List.copyOf(Objects.requireNonNull(portTemplates,"portTemplates"));if(this.portTemplates.isEmpty())throw new IllegalArgumentException("at least one port template is required");long ports=this.portTemplates.stream().mapToLong(PortTemplate::count).sum();if(ports>2048)throw new IllegalArgumentException("equipment model port count exceeds 2048");this.status=Objects.requireNonNull(status,"status");this.description=nullable(description,4096);if(version<1)throw new IllegalArgumentException("version must be positive");this.version=version;this.createdAt=Objects.requireNonNull(createdAt,"createdAt");this.updatedAt=Objects.requireNonNull(updatedAt,"updatedAt");this.createdBy=Objects.requireNonNull(createdBy,"createdBy");this.updatedBy=Objects.requireNonNull(updatedBy,"updatedBy");this.lastReason=text(lastReason,"lastReason",2,1024);
    }
    public static EquipmentModel draft(DomainIdentifier id,DomainIdentifier organizationId,DomainIdentifier manufacturerPartnerId,String code,String displayName,String formFactor,int rackUnits,int widthMm,int depthMm,BigDecimal weightKg,List<PortTemplate> templates,String description,DomainIdentifier actor,String reason,Instant now){return new EquipmentModel(id,organizationId,manufacturerPartnerId,code,displayName,formFactor,rackUnits,widthMm,depthMm,weightKg,templates,PhysicalStatus.DRAFT,description,1,now,now,actor,actor,reason);}
    public static EquipmentModel restore(DomainIdentifier id,DomainIdentifier organizationId,DomainIdentifier manufacturerPartnerId,String code,String displayName,String formFactor,int rackUnits,int widthMm,int depthMm,BigDecimal weightKg,List<PortTemplate> templates,PhysicalStatus status,String description,long version,Instant createdAt,Instant updatedAt,DomainIdentifier createdBy,DomainIdentifier updatedBy,String lastReason){return new EquipmentModel(id,organizationId,manufacturerPartnerId,code,displayName,formFactor,rackUnits,widthMm,depthMm,weightKg,templates,status,description,version,createdAt,updatedAt,createdBy,updatedBy,lastReason);}
    public EquipmentModel changeStatus(PhysicalStatus target,DomainIdentifier actor,String reason,Instant now){if(status==PhysicalStatus.ARCHIVED)throw new DcimPhysicalConflictException("DCIM_MODEL_IMMUTABLE","archived model is immutable");if(target==PhysicalStatus.MAINTENANCE)throw new DcimPhysicalConflictException("DCIM_MODEL_STATUS_INVALID","equipment models do not enter maintenance");return new EquipmentModel(id,organizationId,manufacturerPartnerId,code,displayName,formFactor,rackUnits,widthMm,depthMm,weightKg,portTemplates,target,description,version+1,createdAt,now,createdBy,actor,reason);}
    public DomainIdentifier id(){return id;} public DomainIdentifier organizationId(){return organizationId;} public DomainIdentifier manufacturerPartnerId(){return manufacturerPartnerId;} public String code(){return code;} public String displayName(){return displayName;} public String formFactor(){return formFactor;} public int rackUnits(){return rackUnits;} public int widthMm(){return widthMm;} public int depthMm(){return depthMm;} public BigDecimal weightKg(){return weightKg;} public List<PortTemplate> portTemplates(){return portTemplates;} public PhysicalStatus status(){return status;} public String description(){return description;} public long version(){return version;} public Instant createdAt(){return createdAt;} public Instant updatedAt(){return updatedAt;} public DomainIdentifier createdBy(){return createdBy;} public DomainIdentifier updatedBy(){return updatedBy;} public String lastReason(){return lastReason;}
    private static BigDecimal positive(BigDecimal v,String f){if(v==null||v.signum()<=0)throw new IllegalArgumentException(f+" must be positive");return v.stripTrailingZeros();} private static String token(String v,String f,int min,int max){String x=text(v,f,min,max);if(!x.matches("[A-Za-z0-9][A-Za-z0-9._-]*"))throw new IllegalArgumentException(f+" is invalid");return x;} private static String text(String v,String f,int min,int max){String x=Objects.requireNonNull(v,f).strip();if(x.length()<min||x.length()>max||x.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException(f+" length/content is invalid");return x;} private static String nullable(String v,int max){if(v==null||v.isBlank())return null;return text(v,"description",1,max);}
}
