package io.infranexum.dcim.physical.domain;

import io.infranexum.core.contracts.DomainIdentifier;
import java.time.Instant;
import java.util.Objects;

/** Rack aggregate owning vertical U occupancy boundaries. */
public final class Rack {
    private final DomainIdentifier id,organizationId,subdivisionId,roomId,createdBy,updatedBy; private final String code,displayName,lastReason; private final int heightU,widthMm,depthMm; private final PhysicalStatus status; private final long version; private final Instant createdAt,updatedAt;
    private Rack(DomainIdentifier id,DomainIdentifier organizationId,DomainIdentifier subdivisionId,DomainIdentifier roomId,String code,String displayName,int heightU,int widthMm,int depthMm,PhysicalStatus status,long version,Instant createdAt,Instant updatedAt,DomainIdentifier createdBy,DomainIdentifier updatedBy,String reason){this.id=Objects.requireNonNull(id,"id");this.organizationId=Objects.requireNonNull(organizationId,"organizationId");this.subdivisionId=Objects.requireNonNull(subdivisionId,"subdivisionId");this.roomId=Objects.requireNonNull(roomId,"roomId");this.code=text(code,"code",3,64);this.displayName=text(displayName,"displayName",3,128);if(heightU<1||heightU>100)throw new IllegalArgumentException("heightU must be 1..100");if(widthMm<1||widthMm>5000||depthMm<1||depthMm>5000)throw new IllegalArgumentException("rack dimensions invalid");this.heightU=heightU;this.widthMm=widthMm;this.depthMm=depthMm;this.status=Objects.requireNonNull(status,"status");if(version<1)throw new IllegalArgumentException("version must be positive");this.version=version;this.createdAt=Objects.requireNonNull(createdAt,"createdAt");this.updatedAt=Objects.requireNonNull(updatedAt,"updatedAt");this.createdBy=Objects.requireNonNull(createdBy,"createdBy");this.updatedBy=Objects.requireNonNull(updatedBy,"updatedBy");this.lastReason=text(reason,"lastReason",2,1024);}
    public static Rack draft(DomainIdentifier id,DomainIdentifier org,DomainIdentifier subdivision,DomainIdentifier room,String code,String name,int heightU,int widthMm,int depthMm,DomainIdentifier actor,String reason,Instant now){return new Rack(id,org,subdivision,room,code,name,heightU,widthMm,depthMm,PhysicalStatus.DRAFT,1,now,now,actor,actor,reason);} public static Rack restore(DomainIdentifier id,DomainIdentifier org,DomainIdentifier subdivision,DomainIdentifier room,String code,String name,int heightU,int widthMm,int depthMm,PhysicalStatus status,long version,Instant createdAt,Instant updatedAt,DomainIdentifier createdBy,DomainIdentifier updatedBy,String reason){return new Rack(id,org,subdivision,room,code,name,heightU,widthMm,depthMm,status,version,createdAt,updatedAt,createdBy,updatedBy,reason);} public Rack changeStatus(PhysicalStatus target,DomainIdentifier actor,String reason,Instant now){if(status==PhysicalStatus.ARCHIVED)throw new DcimPhysicalConflictException("DCIM_RACK_IMMUTABLE","archived rack is immutable");return new Rack(id,organizationId,subdivisionId,roomId,code,displayName,heightU,widthMm,depthMm,target,version+1,createdAt,now,createdBy,actor,reason);}
    public DomainIdentifier id(){return id;} public DomainIdentifier organizationId(){return organizationId;} public DomainIdentifier subdivisionId(){return subdivisionId;} public DomainIdentifier roomId(){return roomId;} public String code(){return code;} public String displayName(){return displayName;} public int heightU(){return heightU;} public int widthMm(){return widthMm;} public int depthMm(){return depthMm;} public PhysicalStatus status(){return status;} public long version(){return version;} public Instant createdAt(){return createdAt;} public Instant updatedAt(){return updatedAt;} public DomainIdentifier createdBy(){return createdBy;} public DomainIdentifier updatedBy(){return updatedBy;} public String lastReason(){return lastReason;} private static String text(String v,String f,int min,int max){String x=Objects.requireNonNull(v,f).strip();if(x.length()<min||x.length()>max||x.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException(f+" invalid");return x;}
}
