ALTER TABLE INFRANEXUM_INTEGRATION_INBOX ADD (PAYLOAD_RAW CLOB);
UPDATE INFRANEXUM_INTEGRATION_INBOX SET PAYLOAD_RAW = PAYLOAD_JSON WHERE PAYLOAD_RAW IS NULL;
ALTER TABLE INFRANEXUM_INTEGRATION_INBOX MODIFY (PAYLOAD_RAW NOT NULL);
