-- InfraNexum migration 0005: append-only Core Audit for Oracle.
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_AUDIT_CHAIN_HEAD (
    SCOPE_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SCOPE_ID VARCHAR2(160 CHAR) NOT NULL,
    LAST_SEQUENCE NUMBER(19) DEFAULT 0 NOT NULL,
    HEAD_HASH CHAR(64 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INX_AUDIT_CHAIN_HEAD PRIMARY KEY (SCOPE_TYPE, SCOPE_ID),
    CONSTRAINT CK_INX_AUDIT_HEAD_SEQ CHECK (LAST_SEQUENCE >= 0),
    CONSTRAINT CK_INX_AUDIT_HEAD_HASH CHECK (REGEXP_LIKE(HEAD_HASH, ''^[0-9a-f]{64}$''))
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_AUDIT_ENTRY (
    SCOPE_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SCOPE_ID VARCHAR2(160 CHAR) NOT NULL,
    SEQUENCE_NO NUMBER(19) NOT NULL,
    AUDIT_ID VARCHAR2(36 CHAR) NOT NULL,
    ACTOR_ID VARCHAR2(160 CHAR) NOT NULL,
    ACTOR_TYPE VARCHAR2(160 CHAR) NOT NULL,
    ACTION_NAME VARCHAR2(160 CHAR) NOT NULL,
    TARGET_TYPE VARCHAR2(160 CHAR) NOT NULL,
    TARGET_ID VARCHAR2(160 CHAR) NOT NULL,
    AUTHORIZATION_DECISION VARCHAR2(32 CHAR) NOT NULL,
    OCCURRED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CORRELATION_ID VARCHAR2(36 CHAR),
    RESULT_NAME VARCHAR2(32 CHAR) NOT NULL,
    ORIGIN_NAME VARCHAR2(512 CHAR) NOT NULL,
    REASON_TEXT VARCHAR2(1024 CHAR),
    CLIENT_IP VARCHAR2(64 CHAR),
    USER_AGENT VARCHAR2(512 CHAR),
    METADATA_JSON CLOB NOT NULL,
    SENSITIVITY VARCHAR2(32 CHAR) NOT NULL,
    PREVIOUS_HASH CHAR(64 CHAR) NOT NULL,
    ENTRY_HASH CHAR(64 CHAR) NOT NULL,
    IMMUTABLE_FLAG CHAR(1 CHAR) DEFAULT ''Y'' NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INX_AUDIT_ENTRY PRIMARY KEY (SCOPE_TYPE, SCOPE_ID, SEQUENCE_NO),
    CONSTRAINT UQ_INX_AUDIT_ID UNIQUE (AUDIT_ID),
    CONSTRAINT CK_INX_AUDIT_SEQ CHECK (SEQUENCE_NO >= 1),
    CONSTRAINT CK_INX_AUDIT_ID_V7 CHECK (SUBSTR(AUDIT_ID, 15, 1) = ''7'' AND SUBSTR(AUDIT_ID, 20, 1) IN (''8'',''9'',''a'',''b'')),
    CONSTRAINT CK_INX_AUDIT_CORR_V7 CHECK (CORRELATION_ID IS NULL OR (SUBSTR(CORRELATION_ID, 15, 1) = ''7'' AND SUBSTR(CORRELATION_ID, 20, 1) IN (''8'',''9'',''a'',''b''))),
    CONSTRAINT CK_INX_AUDIT_SCOPE_TYPE CHECK (REGEXP_LIKE(SCOPE_TYPE, ''^[A-Z][A-Z0-9_]{1,31}$'')),
    CONSTRAINT CK_INX_AUDIT_DECISION CHECK (REGEXP_LIKE(AUTHORIZATION_DECISION, ''^[A-Z][A-Z0-9_]{1,31}$'')),
    CONSTRAINT CK_INX_AUDIT_RESULT CHECK (REGEXP_LIKE(RESULT_NAME, ''^[A-Z][A-Z0-9_]{1,31}$'')),
    CONSTRAINT CK_INX_AUDIT_SENS CHECK (REGEXP_LIKE(SENSITIVITY, ''^[A-Z][A-Z0-9_]{1,31}$'')),
    CONSTRAINT CK_INX_AUDIT_HASHES CHECK (REGEXP_LIKE(PREVIOUS_HASH, ''^[0-9a-f]{64}$'') AND REGEXP_LIKE(ENTRY_HASH, ''^[0-9a-f]{64}$'')),
    CONSTRAINT CK_INX_AUDIT_IMM CHECK (IMMUTABLE_FLAG = ''Y''),
    CONSTRAINT CK_INX_AUDIT_METADATA_JSON CHECK (METADATA_JSON IS JSON)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_AUDIT_TIME ON INFRANEXUM_CORE_AUDIT_ENTRY (SCOPE_TYPE, SCOPE_ID, OCCURRED_AT DESC, SEQUENCE_NO DESC)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_AUDIT_ACTOR ON INFRANEXUM_CORE_AUDIT_ENTRY (SCOPE_TYPE, SCOPE_ID, ACTOR_ID, OCCURRED_AT DESC)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_AUDIT_ACTION ON INFRANEXUM_CORE_AUDIT_ENTRY (SCOPE_TYPE, SCOPE_ID, ACTION_NAME, OCCURRED_AT DESC)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_AUDIT_TARGET ON INFRANEXUM_CORE_AUDIT_ENTRY (SCOPE_TYPE, SCOPE_ID, TARGET_TYPE, TARGET_ID, OCCURRED_AT DESC)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_AUDIT_CORRELATION ON INFRANEXUM_CORE_AUDIT_ENTRY (CORRELATION_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_AUDIT_PURGE_TOMBSTONE (
    TOMBSTONE_ID VARCHAR2(36 CHAR) PRIMARY KEY,
    SCOPE_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SCOPE_ID VARCHAR2(160 CHAR) NOT NULL,
    POLICY_ID VARCHAR2(160 CHAR) NOT NULL,
    APPROVED_BY_FIRST VARCHAR2(36 CHAR) NOT NULL,
    APPROVED_BY_SECOND VARCHAR2(36 CHAR) NOT NULL,
    PURGED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PROOF_SHA256 CHAR(64 CHAR) NOT NULL,
    REASON_TEXT VARCHAR2(1024 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_INX_AUDIT_TOMB_ID CHECK (SUBSTR(TOMBSTONE_ID, 15, 1) = ''7'' AND SUBSTR(TOMBSTONE_ID, 20, 1) IN (''8'',''9'',''a'',''b'')),
    CONSTRAINT CK_INX_AUDIT_TOMB_APPROVERS CHECK (APPROVED_BY_FIRST <> APPROVED_BY_SECOND),
    CONSTRAINT CK_INX_AUDIT_TOMB_SHA CHECK (REGEXP_LIKE(PROOF_SHA256, ''^[0-9a-f]{64}$''))
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_INX_AUDIT_ENTRY_IMMUTABLE
BEFORE UPDATE OR DELETE ON INFRANEXUM_CORE_AUDIT_ENTRY
BEGIN
  RAISE_APPLICATION_ERROR(-20005, 'InfraNexum Core Audit is append-only');
END;
/
CREATE OR REPLACE TRIGGER TRG_INX_AUDIT_TOMB_IMMUTABLE
BEFORE UPDATE OR DELETE ON INFRANEXUM_CORE_AUDIT_PURGE_TOMBSTONE
BEGIN
  RAISE_APPLICATION_ERROR(-20005, 'InfraNexum Core Audit tombstones are append-only');
END;
/
