package io.infranexum.server.dcim.cli;

import io.infranexum.core.contracts.DomainIdentifier;
import io.infranexum.core.contracts.UuidV7Generator;
import io.infranexum.dcim.physical.application.*;
import io.infranexum.dcim.physical.domain.*;
import io.infranexum.identity.access.application.AuthorizationDecision;
import io.infranexum.identity.access.application.PolicyDecisionService;
import io.infranexum.identity.access.application.RbacAuthorizationService;
import io.infranexum.identity.access.domain.*;
import io.infranexum.identity.access.ports.IdentityAccessFeaturePolicy;
import io.infranexum.identity.local.application.*;
import io.infranexum.server.platform.PlatformCapabilityService;
import java.io.*;import java.math.BigDecimal;import java.nio.*;import java.nio.charset.*;import java.nio.file.*;import java.util.*;
import tools.jackson.databind.JsonNode;import tools.jackson.databind.json.JsonMapper;

/** Server-owned PGM-07-E05 CLI. Structured commands use absolute JSON input files; secrets never appear in argv. */
public final class DcimPhysicalCli {
 public static final int EXIT_OK=0,EXIT_USAGE=2,EXIT_AUTHENTICATION=3,EXIT_AUTHORIZATION=4,EXIT_BUSINESS=5,EXIT_INTERNAL=70;
 private final LocalAuthenticationService authentication;private final RbacAuthorizationService authorization;private final PolicyDecisionService policy;private final IdentityAccessFeaturePolicy features;private final PlatformCapabilityService capabilities;private final DcimPhysicalApplicationService service;private final UuidV7Generator ids;private final JsonMapper json=JsonMapper.builder().build();
 public DcimPhysicalCli(LocalAuthenticationService a,RbacAuthorizationService z,PolicyDecisionService p,IdentityAccessFeaturePolicy f,PlatformCapabilityService c,DcimPhysicalApplicationService s,UuidV7Generator i){authentication=Objects.requireNonNull(a);authorization=Objects.requireNonNull(z);policy=Objects.requireNonNull(p);features=Objects.requireNonNull(f);capabilities=Objects.requireNonNull(c);service=Objects.requireNonNull(s);ids=Objects.requireNonNull(i);}
 public int run(String[] argv,PrintWriter out,PrintWriter err){if(argv.length==0||has(argv,"--help")||has(argv,"-h")){out.print(help());out.flush();return EXIT_OK;}AuthenticatedSession session=null;try{Args a=Args.parse(argv);char[] secret=readSecret(a.required("password-file"));try{session=authentication.authenticate(a.required("username"),secret);}finally{Arrays.fill(secret,'\0');}Object result=execute(a,session.account().id(),ids.next());out.println(a.json()?json.writeValueAsString(result):String.valueOf(result));out.flush();return EXIT_OK;}catch(CliAuthorizationException e){err.println("authorization denied: "+safe(e.getMessage()));return EXIT_AUTHORIZATION;}catch(IllegalArgumentException e){err.println("usage error: "+safe(e.getMessage()));return EXIT_USAGE;}catch(DcimPhysicalConflictException|DcimPhysicalNotFoundException e){err.println(e.getClass().getSimpleName()+": "+safe(e.getMessage()));return EXIT_BUSINESS;}catch(Exception e){if(session==null){err.println("authentication failed");return EXIT_AUTHENTICATION;}err.println("internal CLI failure: "+e.getClass().getSimpleName());return EXIT_INTERNAL;}finally{if(session!=null)try{authentication.logout(new ValidatedSession(session.account(),session.session()));}catch(RuntimeException ignored){}}}
 private Object execute(Args a,DomainIdentifier actor,DomainIdentifier correlation){if(!"dcim".equals(a.namespace)||!"physical".equals(a.resource))throw new IllegalArgumentException("command must start with 'dcim physical'");return switch(a.operation){case "models"->listModels(a,actor,correlation);case "model-create"->createModel(a,actor,correlation);case "model-status"->modelStatus(a,actor,correlation);case "racks"->listRacks(a,actor,correlation);case "rack-create"->createRack(a,actor,correlation);case "rack-status"->rackStatus(a,actor,correlation);case "equipment"->listEquipment(a,actor,correlation);case "install"->install(a,actor,correlation);case "move"->move(a,actor,correlation);case "equipment-status"->equipmentStatus(a,actor,correlation);case "ports"->ports(a,actor,correlation);case "cables"->cables(a,actor,correlation);case "connect"->connect(a,actor,correlation);case "disconnect"->disconnect(a,actor,correlation);default->throw new IllegalArgumentException("unknown physical operation: "+a.operation);};}
 private Object listModels(Args a,DomainIdentifier actor,DomainIdentifier corr){DomainIdentifier org=a.id("organization-id");require(actor,PermissionCodes.DCIM_MODEL_READ,org,corr,"dcim-model","collection",null);return service.models(org,a.limit());}
 private Object createModel(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DCIM_MODEL_CREATE,org,corr,"dcim-model","collection",reason);List<PortTemplate> ports=new ArrayList<>();JsonNode portNodes=n.get("portTemplates");if(portNodes!=null&&!portNodes.isNull()){if(!portNodes.isArray())throw new IllegalArgumentException("portTemplates must be an array");for(JsonNode x:portNodes){ports.add(new PortTemplate(text(x,"namePrefix"),x.required("count").asInt(),PortKind.valueOf(text(x,"kind").toUpperCase(Locale.ROOT)),text(x,"media"),text(x,"connector")));}}EquipmentCategory category=EquipmentCategory.parse(optional(n,"category"));EquipmentType equipmentType=EquipmentType.parse(optional(n,"equipmentType"));var cmd=new CreateEquipmentModelCommand(org,id(n,"manufacturerPartnerId"),optional(n,"code"),text(n,"displayName"),category,equipmentType,optional(n,"manufacturerReference"),text(n,"formFactor"),integer(n,"rackUnits",0),integer(n,"widthMm",0),integer(n,"depthMm",0),decimalOrDefault(n,"weightKg",BigDecimal.ZERO),List.copyOf(ports),optional(n,"description"));if(a.dry())return Map.of("dryRun",true,"operation","model-create","code",cmd.code()==null?"auto":cmd.code(),"category",category.wireValue(),"equipmentType",equipmentType.wireValue());return service.createModel(cmd,a.required("idempotency-key"),context(actor,corr,reason));}
 private Object modelStatus(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.model(a.id("id"));String reason=a.required("reason");require(actor,PermissionCodes.DCIM_MODEL_UPDATE,x.organizationId(),corr,"dcim-model",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.changeModelStatus(x.id(),a.version(),PhysicalStatus.parse(a.required("target")),a.required("idempotency-key"),context(actor,corr,reason));}
 private Object listRacks(Args a,DomainIdentifier actor,DomainIdentifier corr){DomainIdentifier org=a.id("organization-id");require(actor,PermissionCodes.DCIM_RACK_READ,org,corr,"dcim-rack","collection",null);return service.racks(org,a.optionalId("room-id"),a.limit());}
 private Object createRack(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DCIM_RACK_CREATE,org,corr,"dcim-rack","collection",reason);var cmd=new CreateRackCommand(org,id(n,"subdivisionId"),id(n,"roomId"),optional(n,"code"),text(n,"displayName"),n.required("heightU").asInt(),n.required("widthMm").asInt(),n.required("depthMm").asInt());if(a.dry())return Map.of("dryRun",true,"operation","rack-create","code",cmd.code()==null?"auto":cmd.code());return service.createRack(cmd,a.required("idempotency-key"),context(actor,corr,reason));}
 private Object rackStatus(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.rack(a.id("id"));var target=PhysicalStatus.parse(a.required("target"));String perm=target==PhysicalStatus.DECOMMISSIONED?PermissionCodes.DCIM_RACK_DECOMMISSION:PermissionCodes.DCIM_RACK_UPDATE;String reason=a.required("reason");require(actor,perm,x.organizationId(),corr,"dcim-rack",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.changeRackStatus(x.id(),a.version(),target,a.required("idempotency-key"),context(actor,corr,reason));}
 private Object listEquipment(Args a,DomainIdentifier actor,DomainIdentifier corr){DomainIdentifier org=a.id("organization-id");require(actor,PermissionCodes.DCIM_EQUIPMENT_READ,org,corr,"dcim-equipment","collection",null);return service.equipment(org,a.optionalId("rack-id"),a.limit());}
 private Object install(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DCIM_EQUIPMENT_CREATE,org,corr,"dcim-equipment","collection",reason);var cmd=new InstallEquipmentCommand(org,id(n,"subdivisionId"),id(n,"rackId"),id(n,"modelId"),id(n,"rsotObjectId"),optionalId(n,"itamAssetId"),optional(n,"serialNumber"),optional(n,"assetTag"),n.required("startU").asInt(),text(n,"face"));if(a.dry())return Map.of("dryRun",true,"operation","install");return service.install(cmd,a.required("idempotency-key"),context(actor,corr,reason));}
 private Object move(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.equipment(a.id("id"));JsonNode n=input(a);String reason=reason(n,a);require(actor,PermissionCodes.DCIM_EQUIPMENT_MOVE,x.organizationId(),corr,"dcim-equipment",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.moveEquipment(x.id(),a.version(),id(n,"rackId"),n.required("startU").asInt(),text(n,"face"),a.required("idempotency-key"),context(actor,corr,reason));}
 private Object equipmentStatus(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.equipment(a.id("id"));var target=PhysicalStatus.parse(a.required("target"));String perm=(target==PhysicalStatus.DECOMMISSIONED||target==PhysicalStatus.ARCHIVED)?PermissionCodes.DCIM_EQUIPMENT_DECOMMISSION:PermissionCodes.DCIM_EQUIPMENT_UPDATE;String reason=a.required("reason");require(actor,perm,x.organizationId(),corr,"dcim-equipment",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.changeEquipmentStatus(x.id(),a.version(),target,a.required("idempotency-key"),context(actor,corr,reason));}
 private Object ports(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.equipment(a.id("id"));require(actor,PermissionCodes.DCIM_PORT_READ,x.organizationId(),corr,"dcim-port",x.id().toString(),null);return service.ports(x.id());}
 private Object cables(Args a,DomainIdentifier actor,DomainIdentifier corr){DomainIdentifier org=a.id("organization-id");require(actor,PermissionCodes.DCIM_CABLE_READ,org,corr,"dcim-cable","collection",null);return service.cables(org,a.limit());}
 private Object connect(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DCIM_CABLE_CREATE,org,corr,"dcim-cable","collection",reason);var cmd=new ConnectPortsCommand(org,id(n,"subdivisionId"),id(n,"portAId"),id(n,"portBId"),text(n,"label"),CableType.parse(optional(n,"cableType")),decimalOrDefault(n,"lengthMeters",BigDecimal.ONE),optionalId(n,"manufacturerPartnerId"),optional(n,"manufacturerReference"));if(a.dry())return Map.of("dryRun",true,"operation","connect","cableType",cmd.cableType().wireValue(),"lengthMeters",cmd.lengthMeters());return service.connect(cmd,a.required("idempotency-key"),context(actor,corr,reason));}
 private Object disconnect(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.cable(a.id("id"));String reason=a.required("reason");require(actor,PermissionCodes.DCIM_CABLE_DISCONNECT,x.organizationId(),corr,"dcim-cable",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.disconnect(x.id(),a.version(),a.required("idempotency-key"),context(actor,corr,reason));}
 private PhysicalCommandContext context(DomainIdentifier actor,DomainIdentifier corr,String reason){return new PhysicalCommandContext(actor,corr,reason);}private void require(DomainIdentifier actor,String perm,DomainIdentifier org,DomainIdentifier corr,String type,String target,String justification){AuthorizationDecision d=authorization.decide(actor,perm,AuthorizationScope.organization(org),corr,type,target,"CLI");if(!d.allowed())throw new CliAuthorizationException(d.explanation());if(!features.supportsAdvancedAuthorization())return;boolean present=justification!=null&&justification.strip().length()>=8;String cv=capabilities.snapshot().catalogVersion()+":"+capabilities.snapshot().profileVersion();var req=new PolicyEvaluationRequest(actor,perm,type,target,AuthorizationScope.organization(org),Map.of("channel","CLI","justification_present",Boolean.toString(present)),"LOCAL_SESSION",cv,null,true);var adv=policy.decide(req,corr,"CLI");if(!adv.permitted())throw new CliAuthorizationException(adv.reasonCode());for(var o:adv.obligations())if(!(o==PolicyObligation.REQUIRE_JUSTIFICATION&&present))throw new CliAuthorizationException("required authorization obligation is not satisfied: "+o.name());}
 private JsonNode input(Args a){Path p=Path.of(a.required("input-file"));if(!p.isAbsolute())throw new IllegalArgumentException("--input-file must be absolute");try{JsonNode n=json.readTree(Files.readString(p,StandardCharsets.UTF_8));if(n==null||!n.isObject())throw new IllegalArgumentException("input root must be a JSON object");return n;}catch(IOException e){throw new IllegalArgumentException("input file is unreadable or invalid JSON",e);}}
 private static String reason(JsonNode n,Args a){JsonNode x=n.get("reason");return x==null?a.required("reason"):text(n,"reason");}private static DomainIdentifier id(JsonNode n,String k){return DomainIdentifier.parse(text(n,k));}private static DomainIdentifier optionalId(JsonNode n,String k){String v=optional(n,k);return v==null?null:DomainIdentifier.parse(v);}private static String text(JsonNode n,String k){JsonNode v=n.get(k);if(v==null||!v.isTextual()||v.textValue().isBlank())throw new IllegalArgumentException(k+" is required");return v.textValue().strip();}private static String optional(JsonNode n,String k){JsonNode v=n.get(k);return v==null||v.isNull()?null:text(n,k);}private static BigDecimal decimal(JsonNode n,String k){JsonNode v=n.get(k);return v==null||v.isNull()?null:v.decimalValue();}private static BigDecimal decimalOrDefault(JsonNode n,String k,BigDecimal fallback){BigDecimal value=decimal(n,k);return value==null?fallback:value;}private static int integer(JsonNode n,String k,int fallback){JsonNode v=n.get(k);return v==null||v.isNull()?fallback:v.asInt();}
 private static char[] readSecret(String value){Path p=Path.of(value);if(!p.isAbsolute())throw new IllegalArgumentException("--password-file must be absolute");try{byte[] b=Files.readAllBytes(p);try{CharBuffer c=StandardCharsets.UTF_8.newDecoder().decode(ByteBuffer.wrap(b));String x=c.toString().stripTrailing();if(x.isEmpty())throw new IllegalArgumentException("password file is empty");return x.toCharArray();}finally{Arrays.fill(b,(byte)0);}}catch(IOException e){throw new IllegalArgumentException("password file is unreadable",e);}}
 private static boolean has(String[] a,String x){return Arrays.asList(a).contains(x);}private static String safe(String x){if(x==null)return "request failed";return x.replaceAll("[\\r\\n\\t]+"," ").strip();}private static String help(){return """
InfraNexum DCIM Physical CLI
  dcim physical models|racks|equipment|cables --organization-id UUID --username USER --password-file ABS [--output json]
  dcim physical ports --id UUID --username USER --password-file ABS [--output json]
  dcim physical model-create|rack-create|install|move|connect --input-file ABS --idempotency-key KEY --username USER --password-file ABS [--id UUID --version N] [--dry-run] [--output json]
  dcim physical model-status|rack-status|equipment-status|disconnect --id UUID --version N --target STATUS --reason TEXT --idempotency-key KEY --username USER --password-file ABS [--dry-run] [--output json]
Secrets are accepted only through --password-file.
""";}
 private static final class CliAuthorizationException extends RuntimeException{private static final long serialVersionUID=1L;CliAuthorizationException(String m){super(m);}}
 private record Args(String namespace,String resource,String operation,Map<String,String> values,Set<String> flags){static Args parse(String[] in){if(in.length<3)throw new IllegalArgumentException("namespace, resource and operation required");Map<String,String> v=new LinkedHashMap<>();Set<String> f=new LinkedHashSet<>();for(int i=3;i<in.length;i++){if(!in[i].startsWith("--"))throw new IllegalArgumentException("unexpected argument: "+in[i]);String k=in[i].substring(2);if(Set.of("dry-run","json").contains(k)){f.add(k);continue;}if(i+1>=in.length||in[i+1].startsWith("--"))throw new IllegalArgumentException("--"+k+" requires a value");v.put(k,in[++i]);}if("json".equalsIgnoreCase(v.get("output")))f.add("json");return new Args(in[0],in[1],in[2],Map.copyOf(v),Set.copyOf(f));}String required(String k){String x=values.get(k);if(x==null||x.isBlank())throw new IllegalArgumentException("--"+k+" is required");return x.strip();}DomainIdentifier id(String k){return DomainIdentifier.parse(required(k));}DomainIdentifier optionalId(String k){String x=values.get(k);return x==null?null:DomainIdentifier.parse(x);}long version(){long x=Long.parseLong(required("version"));if(x<1)throw new IllegalArgumentException("version must be positive");return x;}int limit(){int x=Integer.parseInt(values.getOrDefault("limit","100"));if(x<1||x>200)throw new IllegalArgumentException("limit must be 1..200");return x;}boolean dry(){return flags.contains("dry-run");}boolean json(){return flags.contains("json");}}
}
