package io.infranexum.adapters.persistence.jdbc;

import io.infranexum.core.contracts.DomainIdentifier;
import io.infranexum.itam.compliance.domain.*;
import io.infranexum.itam.compliance.ports.ComplianceRepository;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import javax.sql.DataSource;

/** PostgreSQL/Oracle persistence for versioned ITAM warranties, support coverage and software-license contracts. */
public final class JdbcComplianceRepository implements ComplianceRepository {
    private final DataSource dataSource;
    private final JdbcConnectionAccess transaction;
    private final JdbcDatabaseDialect dialect;

    public JdbcComplianceRepository(DataSource dataSource, JdbcConnectionAccess transaction, JdbcDatabaseDialect dialect) {
        this.dataSource=Objects.requireNonNull(dataSource,"dataSource");this.transaction=Objects.requireNonNull(transaction,"transaction");
        this.dialect=Objects.requireNonNull(dialect,"dialect");
    }

    @Override public long contractRecordCount(){
        Connection c=transaction.requireCurrentConnection();
        String sql="SELECT (SELECT COUNT(*) FROM "+licenseTable()+")+(SELECT COUNT(*) FROM "+coverageTable()+")";
        try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){if(!r.next())throw new SQLException("contract count returned no row");return r.getLong(1);}catch(SQLException e){throw fail("count ITAM contractual records",e);}
    }

    @Override public Optional<Warranty> findWarranty(DomainIdentifier id){return findOne("SELECT "+warrantyColumns()+" FROM "+warrantyTable()+" WHERE id=?",id,this::readWarranty);}
    @Override public List<Warranty> warrantiesForAsset(DomainIdentifier assetId){return findMany("SELECT "+warrantyColumns()+" FROM "+warrantyTable()+" WHERE asset_id=? ORDER BY warranty_start_date,id",assetId,this::readWarranty);}
    @Override public List<Warranty> warrantyPage(DomainIdentifier assetId,DomainIdentifier afterId,int limit){return paged("SELECT "+warrantyColumns()+" FROM "+warrantyTable()+" WHERE asset_id=?",assetId,afterId,limit,this::readWarranty);}
    @Override public void insertWarranty(Warranty w){insertWarrantyRow(w);try{insertRevision("warranty",w.id(),w.version(),w.status(),w.proofReference(),w.lastReason(),w.updatedAt(),w.updatedBy(),warrantySnapshot(w));}catch(SQLException e){throw fail("insert warranty revision",e);}}
    @Override public void updateWarranty(Warranty w,long expected){
        String sql="UPDATE "+warrantyTable()+" SET manufacturer_partner_id=?,warranty_type_id=?,coverage_level=?,warranty_start_date=?,warranty_end_date=?,manufacturer_support_end_date=?,contract_certificate_number=?,proof_reference=?,source=?,status=?,verified_at=?,verified_by=?,version=?,updated_at=?,updated_by=?,last_reason=? WHERE id=? AND version=?";
        try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,w.manufacturerPartnerId());dialect.bindIdentifier(s,i++,w.warrantyTypeId());s.setString(i++,w.coverageLevel());s.setDate(i++,Date.valueOf(w.warrantyStartDate()));s.setDate(i++,Date.valueOf(w.warrantyEndDate()));s.setDate(i++,Date.valueOf(w.manufacturerSupportEndDate()));setNullableString(s,i++,w.contractOrCertificateNumber());s.setString(i++,w.proofReference());s.setString(i++,w.source().name());s.setString(i++,w.status().name());JdbcTemporal.bindInstant(s,i++,w.verifiedAt());dialect.bindNullableIdentifier(s,i++,w.verifiedBy());s.setLong(i++,w.version());JdbcTemporal.bindInstant(s,i++,w.updatedAt());dialect.bindIdentifier(s,i++,w.updatedBy());s.setString(i++,w.lastReason());dialect.bindIdentifier(s,i++,w.id());s.setLong(i,expected);requireUpdated(s,"warranty");insertRevision("warranty",w.id(),w.version(),w.status(),w.proofReference(),w.lastReason(),w.updatedAt(),w.updatedBy(),warrantySnapshot(w));}catch(SQLException e){throw fail("update ITAM warranty",e);}}

    @Override public Optional<SoftwareLicenseContract> findLicense(DomainIdentifier id){return findOne("SELECT "+licenseColumns()+" FROM "+licenseTable()+" WHERE id=?",id,this::readLicense);}
    @Override public List<SoftwareLicenseContract> licensesForAsset(DomainIdentifier assetId){return findMany("SELECT "+licenseColumns()+" FROM "+licenseTable()+" WHERE asset_id=? ORDER BY starts_on,id",assetId,this::readLicense);}
    @Override public List<SoftwareLicenseContract> licensePage(DomainIdentifier assetId,DomainIdentifier afterId,int limit){return paged("SELECT "+licenseColumns()+" FROM "+licenseTable()+" WHERE asset_id=?",assetId,afterId,limit,this::readLicense);}
    @Override public void insertLicense(SoftwareLicenseContract l){insertLicenseRow(l);try{insertRevision("license",l.id(),l.version(),l.status(),l.proofReference(),l.lastReason(),l.updatedAt(),l.updatedBy(),licenseSnapshot(l));}catch(SQLException e){throw fail("insert license revision",e);}}
    @Override public void updateLicense(SoftwareLicenseContract l,long expected){
        String sql="UPDATE "+licenseTable()+" SET publisher_partner_id=?,contract_number=?,license_model=?,usage_rights=?,entitlement_quantity=?,starts_on=?,ends_on=?,publisher_support_end_date=?,proof_reference=?,source=?,status=?,verified_at=?,verified_by=?,version=?,updated_at=?,updated_by=?,last_reason=? WHERE id=? AND version=?";
        try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,l.publisherPartnerId());s.setString(i++,l.contractNumber());s.setString(i++,l.licenseModel());s.setString(i++,l.usageRights());s.setLong(i++,l.entitlementQuantity());s.setDate(i++,Date.valueOf(l.startsOn()));setNullableDate(s,i++,l.endsOn());s.setDate(i++,Date.valueOf(l.publisherSupportEndDate()));s.setString(i++,l.proofReference());s.setString(i++,l.source().name());s.setString(i++,l.status().name());JdbcTemporal.bindInstant(s,i++,l.verifiedAt());dialect.bindNullableIdentifier(s,i++,l.verifiedBy());s.setLong(i++,l.version());JdbcTemporal.bindInstant(s,i++,l.updatedAt());dialect.bindIdentifier(s,i++,l.updatedBy());s.setString(i++,l.lastReason());dialect.bindIdentifier(s,i++,l.id());s.setLong(i,expected);requireUpdated(s,"license");insertRevision("license",l.id(),l.version(),l.status(),l.proofReference(),l.lastReason(),l.updatedAt(),l.updatedBy(),licenseSnapshot(l));}catch(SQLException e){throw fail("update ITAM software license",e);}}

    @Override public Optional<SupportProviderAuthorization> findSupportAuthorization(DomainIdentifier id){Connection c=currentOrNew();boolean close=currentConnectionOrNull()==null;try{return findAuthorization(c,id);}finally{close(c,close);}}
    @Override public List<SupportProviderAuthorization> supportAuthorizations(DomainIdentifier organizationId){
        Objects.requireNonNull(organizationId,"organizationId");Connection c=currentOrNew();boolean close=currentConnectionOrNull()==null;
        String sql="SELECT "+authColumns()+" FROM "+authTable()+" WHERE organization_id=? ORDER BY updated_at DESC,id";
        try(PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,organizationId);try(ResultSet r=s.executeQuery()){List<SupportProviderAuthorization> out=new ArrayList<>();while(r.next())out.add(hydrateAuthorization(c,readAuthorizationCore(r)));return List.copyOf(out);}}
        catch(SQLException e){throw fail("list support authorizations",e);}finally{close(c,close);}
    }
    @Override public Optional<SupportProviderAuthorization> findActiveSupportAuthorization(DomainIdentifier provider,DomainIdentifier org,LocalDate on){
        String sql="SELECT "+authColumns()+" FROM "+authTable()+" WHERE provider_partner_id=? AND organization_id=? AND status='ACTIVE' AND valid_from<=? AND (valid_until IS NULL OR valid_until>=?) ORDER BY valid_from DESC";
        Connection c=currentOrNew();boolean close=currentConnectionOrNull()==null;try(PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,provider);dialect.bindIdentifier(s,2,org);s.setDate(3,Date.valueOf(on));s.setDate(4,Date.valueOf(on));try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(hydrateAuthorization(c,readAuthorizationCore(r))):Optional.empty();}}catch(SQLException e){throw fail("find active support authorization",e);}finally{close(c,close);}}
    @Override public void insertSupportAuthorization(SupportProviderAuthorization a){insertAuthorizationRow(a);try{replaceAuthorizationChildren(a);insertRevision("support_authorization",a.id(),a.version(),a.status(),null,a.lastReason(),a.updatedAt(),a.updatedBy(),authorizationSnapshot(a));}catch(SQLException e){throw fail("insert support authorization revision",e);}}
    @Override public void updateSupportAuthorization(SupportProviderAuthorization a,long expected){
        String sql="UPDATE "+authTable()+" SET service_hours=?,time_zone_id=?,valid_from=?,valid_until=?,status=?,version=?,updated_at=?,updated_by=?,last_reason=? WHERE id=? AND version=?";
        try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){int i=1;s.setString(i++,a.serviceHours());s.setString(i++,a.timeZoneId());s.setDate(i++,Date.valueOf(a.validFrom()));setNullableDate(s,i++,a.validUntil());s.setString(i++,a.status().name());s.setLong(i++,a.version());JdbcTemporal.bindInstant(s,i++,a.updatedAt());dialect.bindIdentifier(s,i++,a.updatedBy());s.setString(i++,a.lastReason());dialect.bindIdentifier(s,i++,a.id());s.setLong(i,expected);requireUpdated(s,"support authorization");replaceAuthorizationChildren(a);insertRevision("support_authorization",a.id(),a.version(),a.status(),null,a.lastReason(),a.updatedAt(),a.updatedBy(),authorizationSnapshot(a));}catch(SQLException e){throw fail("update support authorization",e);}}

    @Override public Optional<SupportCoverage> findSupportCoverage(DomainIdentifier id){return findOne("SELECT "+coverageColumns()+" FROM "+coverageTable()+" WHERE id=?",id,this::readCoverage);}
    @Override public List<SupportCoverage> supportCoveragesForAsset(DomainIdentifier assetId){return findMany("SELECT "+coverageColumns()+" FROM "+coverageTable()+" WHERE asset_id=? ORDER BY starts_on,id",assetId,this::readCoverage);}
    @Override public List<SupportCoverage> supportCoveragePage(DomainIdentifier assetId,DomainIdentifier afterId,int limit){return paged("SELECT "+coverageColumns()+" FROM "+coverageTable()+" WHERE asset_id=?",assetId,afterId,limit,this::readCoverage);}
    @Override public List<SupportCoverage> supportCoveragesForAuthorization(DomainIdentifier authorizationId){return findMany("SELECT "+coverageColumns()+" FROM "+coverageTable()+" WHERE authorization_id=? ORDER BY starts_on,id",authorizationId,this::readCoverage);}
    @Override public void insertSupportCoverage(SupportCoverage c){insertCoverageRow(c);try{insertRevision("support_coverage",c.id(),c.version(),c.status(),c.proofReference(),c.lastReason(),c.updatedAt(),c.updatedBy(),coverageSnapshot(c));}catch(SQLException e){throw fail("insert support coverage revision",e);}}
    @Override public void updateSupportCoverage(SupportCoverage c,long expected){
        String sql="UPDATE "+coverageTable()+" SET status=?,version=?,updated_at=?,updated_by=?,last_reason=? WHERE id=? AND version=?";
        try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){s.setString(1,c.status().name());s.setLong(2,c.version());JdbcTemporal.bindInstant(s,3,c.updatedAt());dialect.bindIdentifier(s,4,c.updatedBy());s.setString(5,c.lastReason());dialect.bindIdentifier(s,6,c.id());s.setLong(7,expected);requireUpdated(s,"support coverage");insertRevision("support_coverage",c.id(),c.version(),c.status(),c.proofReference(),c.lastReason(),c.updatedAt(),c.updatedBy(),coverageSnapshot(c));}catch(SQLException e){throw fail("update support coverage",e);}}

    @Override public Optional<WarrantyType> findWarrantyType(DomainIdentifier id){return findOne("SELECT id,code,display_name,active,created_at,created_by FROM "+warrantyTypeTable()+" WHERE id=?",id,this::readWarrantyType);}
    @Override public List<WarrantyType> warrantyTypes(boolean activeOnly){String sql="SELECT id,code,display_name,active,created_at,created_by FROM "+warrantyTypeTable()+(activeOnly?" WHERE active="+booleanTrue():"")+" ORDER BY code";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<WarrantyType> out=new ArrayList<>();while(r.next())out.add(readWarrantyType(r));return List.copyOf(out);}catch(SQLException e){throw fail("list warranty types",e);}}
    @Override public void insertWarrantyType(WarrantyType t){String sql="INSERT INTO "+warrantyTypeTable()+" (id,code,display_name,active,created_at,created_by) VALUES (?,?,?,?,?,?)";try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){dialect.bindIdentifier(s,1,t.id());s.setString(2,t.code());s.setString(3,t.displayName());bindBoolean(s,4,t.active());JdbcTemporal.bindInstant(s,5,t.createdAt());dialect.bindIdentifier(s,6,t.createdBy());if(s.executeUpdate()!=1)throw new SQLException("warranty type insert affected unexpected rows");}catch(SQLException e){throw fail("insert warranty type",e);}}

    @Override public List<Warranty> warrantiesDueBetween(LocalDate start,LocalDate end){String sql="SELECT DISTINCT "+warrantyColumns()+" FROM "+warrantyTable()+" WHERE status='ACTIVE' AND ((warranty_end_date BETWEEN ? AND ?) OR (manufacturer_support_end_date BETWEEN ? AND ?))";return dueWarranties(sql,start,end);}
    @Override public List<SoftwareLicenseContract> licensesDueBetween(LocalDate start,LocalDate end){String sql="SELECT DISTINCT "+licenseColumns()+" FROM "+licenseTable()+" WHERE status='ACTIVE' AND ((ends_on BETWEEN ? AND ?) OR (publisher_support_end_date BETWEEN ? AND ?))";return dueLicenses(sql,start,end);}
    @Override public List<SupportCoverage> supportCoveragesDueBetween(LocalDate start,LocalDate end){String sql="SELECT "+coverageColumns()+" FROM "+coverageTable()+" WHERE status IN ('ACTIVE','REVIEW_REQUIRED') AND ends_on BETWEEN ? AND ?";return dueCoverages(sql,start,end);}
    @Override public boolean reserveAlert(ComplianceAlert a,LocalDate emittedOn){String sql="INSERT INTO "+alertTable()+" (alert_kind,record_id,due_date,threshold_days,emitted_on) VALUES (?,?,?,?,?)";try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){s.setString(1,a.kind().name());dialect.bindIdentifier(s,2,a.recordId());s.setDate(3,Date.valueOf(a.dueDate()));s.setInt(4,a.thresholdDays());s.setDate(5,Date.valueOf(emittedOn));return s.executeUpdate()==1;}catch(SQLException e){if(dialect.isUniqueViolation(e))return false;throw fail("reserve compliance alert",e);}}
    @Override public List<ComplianceRevision> revisions(String recordType,DomainIdentifier recordId,long afterVersion,int limit){
        if(!Set.of("warranty","license","support_authorization","support_coverage").contains(recordType))throw new IllegalArgumentException("unsupported compliance recordType");
        if(afterVersion<0||limit<1||limit>200)throw new IllegalArgumentException("invalid compliance revision page");
        String sql="SELECT record_type,record_id,version,status,proof_reference,reason,snapshot_json,recorded_at,recorded_by FROM "+revisionTable()+" WHERE record_type=? AND record_id=? AND version>? ORDER BY version"+(dialect==JdbcDatabaseDialect.POSTGRESQL?" LIMIT ?":" FETCH NEXT ? ROWS ONLY");
        try(Connection c=dataSource.getConnection();PreparedStatement st=c.prepareStatement(sql)){st.setString(1,recordType);dialect.bindIdentifier(st,2,recordId);st.setLong(3,afterVersion);st.setInt(4,limit);try(ResultSet r=st.executeQuery()){List<ComplianceRevision> out=new ArrayList<>();while(r.next())out.add(new ComplianceRevision(r.getString("record_type"),dialect.readIdentifier(r,"record_id"),r.getLong("version"),ComplianceStatus.valueOf(r.getString("status")),r.getString("proof_reference"),r.getString("reason"),r.getString("snapshot_json"),JdbcTemporal.readRequired(r,"recorded_at"),dialect.readIdentifier(r,"recorded_by")));return List.copyOf(out);}}catch(SQLException e){throw fail("read compliance revision history",e);}
    }

    private void insertWarrantyRow(Warranty w){String sql="INSERT INTO "+warrantyTable()+" ("+warrantyColumns()+") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,w.id());dialect.bindIdentifier(s,i++,w.assetId());dialect.bindIdentifier(s,i++,w.manufacturerPartnerId());dialect.bindIdentifier(s,i++,w.warrantyTypeId());s.setString(i++,w.coverageLevel());s.setDate(i++,Date.valueOf(w.warrantyStartDate()));s.setDate(i++,Date.valueOf(w.warrantyEndDate()));s.setDate(i++,Date.valueOf(w.manufacturerSupportEndDate()));setNullableString(s,i++,w.contractOrCertificateNumber());s.setString(i++,w.proofReference());s.setString(i++,w.source().name());s.setString(i++,w.status().name());JdbcTemporal.bindInstant(s,i++,w.verifiedAt());dialect.bindNullableIdentifier(s,i++,w.verifiedBy());s.setLong(i++,w.version());JdbcTemporal.bindInstant(s,i++,w.createdAt());JdbcTemporal.bindInstant(s,i++,w.updatedAt());dialect.bindIdentifier(s,i++,w.createdBy());dialect.bindIdentifier(s,i++,w.updatedBy());s.setString(i,w.lastReason());requireInserted(s,"warranty");}catch(SQLException e){throw fail("insert ITAM warranty",e);}}
    private void insertLicenseRow(SoftwareLicenseContract l){String sql="INSERT INTO "+licenseTable()+" ("+licenseColumns()+") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,l.id());dialect.bindIdentifier(s,i++,l.assetId());dialect.bindIdentifier(s,i++,l.publisherPartnerId());s.setString(i++,l.contractNumber());s.setString(i++,l.licenseModel());s.setString(i++,l.usageRights());s.setLong(i++,l.entitlementQuantity());s.setDate(i++,Date.valueOf(l.startsOn()));setNullableDate(s,i++,l.endsOn());s.setDate(i++,Date.valueOf(l.publisherSupportEndDate()));s.setString(i++,l.proofReference());s.setString(i++,l.source().name());s.setString(i++,l.status().name());JdbcTemporal.bindInstant(s,i++,l.verifiedAt());dialect.bindNullableIdentifier(s,i++,l.verifiedBy());s.setLong(i++,l.version());JdbcTemporal.bindInstant(s,i++,l.createdAt());JdbcTemporal.bindInstant(s,i++,l.updatedAt());dialect.bindIdentifier(s,i++,l.createdBy());dialect.bindIdentifier(s,i++,l.updatedBy());s.setString(i,l.lastReason());requireInserted(s,"license");}catch(SQLException e){throw fail("insert software license",e);}}
    private void insertAuthorizationRow(SupportProviderAuthorization a){String sql="INSERT INTO "+authTable()+" ("+authColumns()+") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,a.id());dialect.bindIdentifier(s,i++,a.providerPartnerId());dialect.bindIdentifier(s,i++,a.organizationId());s.setString(i++,a.serviceHours());s.setString(i++,a.timeZoneId());s.setDate(i++,Date.valueOf(a.validFrom()));setNullableDate(s,i++,a.validUntil());s.setString(i++,a.status().name());s.setLong(i++,a.version());JdbcTemporal.bindInstant(s,i++,a.createdAt());JdbcTemporal.bindInstant(s,i++,a.updatedAt());dialect.bindIdentifier(s,i++,a.createdBy());dialect.bindIdentifier(s,i++,a.updatedBy());s.setString(i,a.lastReason());requireInserted(s,"support authorization");}catch(SQLException e){throw fail("insert support authorization",e);}}
    private void insertCoverageRow(SupportCoverage c){String sql="INSERT INTO "+coverageTable()+" ("+coverageColumns()+") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,c.id());dialect.bindIdentifier(s,i++,c.assetId());dialect.bindIdentifier(s,i++,c.providerPartnerId());dialect.bindIdentifier(s,i++,c.authorizationId());setNullableString(s,i++,c.contractReference());s.setString(i++,c.coverageType());s.setString(i++,c.serviceLevel());s.setDate(i++,Date.valueOf(c.startsOn()));s.setDate(i++,Date.valueOf(c.endsOn()));dialect.bindIdentifier(s,i++,c.supportedManufacturerId());s.setString(i++,c.supportedObjectType());dialect.bindIdentifier(s,i++,c.organizationId());dialect.bindNullableIdentifier(s,i++,c.subdivisionId());s.setString(i++,c.proofReference());s.setString(i++,c.status().name());s.setLong(i++,c.version());JdbcTemporal.bindInstant(s,i++,c.createdAt());JdbcTemporal.bindInstant(s,i++,c.updatedAt());dialect.bindIdentifier(s,i++,c.createdBy());dialect.bindIdentifier(s,i++,c.updatedBy());s.setString(i,c.lastReason());requireInserted(s,"support coverage");}catch(SQLException e){throw fail("insert support coverage",e);}}

    private Warranty readWarranty(ResultSet r)throws SQLException{return Warranty.restore(dialect.readIdentifier(r,"id"),dialect.readIdentifier(r,"asset_id"),dialect.readIdentifier(r,"manufacturer_partner_id"),dialect.readIdentifier(r,"warranty_type_id"),r.getString("coverage_level"),r.getDate("warranty_start_date").toLocalDate(),r.getDate("warranty_end_date").toLocalDate(),r.getDate("manufacturer_support_end_date").toLocalDate(),r.getString("contract_certificate_number"),r.getString("proof_reference"),EvidenceSource.valueOf(r.getString("source")),ComplianceStatus.valueOf(r.getString("status")),JdbcTemporal.readNullable(r,"verified_at"),nullableIdentifier(r,"verified_by"),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"),dialect.readIdentifier(r,"created_by"),dialect.readIdentifier(r,"updated_by"),r.getString("last_reason"));}
    private SoftwareLicenseContract readLicense(ResultSet r)throws SQLException{return SoftwareLicenseContract.restore(dialect.readIdentifier(r,"id"),dialect.readIdentifier(r,"asset_id"),dialect.readIdentifier(r,"publisher_partner_id"),r.getString("contract_number"),r.getString("license_model"),r.getString("usage_rights"),r.getLong("entitlement_quantity"),r.getDate("starts_on").toLocalDate(),nullableDate(r,"ends_on"),r.getDate("publisher_support_end_date").toLocalDate(),r.getString("proof_reference"),EvidenceSource.valueOf(r.getString("source")),ComplianceStatus.valueOf(r.getString("status")),JdbcTemporal.readNullable(r,"verified_at"),nullableIdentifier(r,"verified_by"),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"),dialect.readIdentifier(r,"created_by"),dialect.readIdentifier(r,"updated_by"),r.getString("last_reason"));}
    private SupportCoverage readCoverage(ResultSet r)throws SQLException{return SupportCoverage.restore(dialect.readIdentifier(r,"id"),dialect.readIdentifier(r,"asset_id"),dialect.readIdentifier(r,"provider_partner_id"),dialect.readIdentifier(r,"authorization_id"),r.getString("contract_reference"),r.getString("coverage_type"),r.getString("service_level"),r.getDate("starts_on").toLocalDate(),r.getDate("ends_on").toLocalDate(),dialect.readIdentifier(r,"supported_manufacturer_id"),r.getString("supported_object_type"),dialect.readIdentifier(r,"organization_id"),nullableIdentifier(r,"subdivision_id"),r.getString("proof_reference"),ComplianceStatus.valueOf(r.getString("status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"),dialect.readIdentifier(r,"created_by"),dialect.readIdentifier(r,"updated_by"),r.getString("last_reason"));}
    private WarrantyType readWarrantyType(ResultSet r)throws SQLException{return new WarrantyType(dialect.readIdentifier(r,"id"),r.getString("code"),r.getString("display_name"),readBoolean(r,"active"),JdbcTemporal.readRequired(r,"created_at"),dialect.readIdentifier(r,"created_by"));}

    private Optional<SupportProviderAuthorization> findAuthorization(Connection c,DomainIdentifier id){try(PreparedStatement s=c.prepareStatement("SELECT "+authColumns()+" FROM "+authTable()+" WHERE id=?")){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(hydrateAuthorization(c,readAuthorizationCore(r))):Optional.empty();}}catch(SQLException e){throw fail("find support authorization",e);}}
    private AuthorizationCore readAuthorizationCore(ResultSet r)throws SQLException{return new AuthorizationCore(dialect.readIdentifier(r,"id"),dialect.readIdentifier(r,"provider_partner_id"),dialect.readIdentifier(r,"organization_id"),r.getString("service_hours"),r.getString("time_zone_id"),r.getDate("valid_from").toLocalDate(),nullableDate(r,"valid_until"),ComplianceStatus.valueOf(r.getString("status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"),dialect.readIdentifier(r,"created_by"),dialect.readIdentifier(r,"updated_by"),r.getString("last_reason"));}
    private SupportProviderAuthorization hydrateAuthorization(Connection c,AuthorizationCore a)throws SQLException{return SupportProviderAuthorization.restore(a.id,a.provider,a.org,loadIds(c,authMfrTable(),"manufacturer_partner_id",a.id),loadStrings(c,authObjTable(),"object_type",a.id),loadIds(c,authSubTable(),"subdivision_id",a.id),a.hours,a.tz,loadStrings(c,authSvcTable(),"service_level",a.id),loadStrings(c,authEscTable(),"contact_type",a.id),a.from,a.until,a.status,a.version,a.created,a.updated,a.createdBy,a.updatedBy,a.reason);}
    private void replaceAuthorizationChildren(SupportProviderAuthorization a)throws SQLException{Connection c=transaction.requireCurrentConnection();deleteChildren(c,a.id());insertIds(c,authMfrTable(),"manufacturer_partner_id",a.id(),a.supportedManufacturerIds());insertStrings(c,authObjTable(),"object_type",a.id(),a.supportedObjectTypes());insertIds(c,authSubTable(),"subdivision_id",a.id(),a.subdivisionScopes());insertStrings(c,authSvcTable(),"service_level",a.id(),a.serviceLevels());insertStrings(c,authEscTable(),"contact_type",a.id(),a.escalationContactTypes());}
    private void deleteChildren(Connection c,DomainIdentifier id)throws SQLException{for(String table:List.of(authMfrTable(),authObjTable(),authSubTable(),authSvcTable(),authEscTable()))try(PreparedStatement s=c.prepareStatement("DELETE FROM "+table+" WHERE authorization_id=?")){dialect.bindIdentifier(s,1,id);s.executeUpdate();}}
    private Set<DomainIdentifier> loadIds(Connection c,String table,String column,DomainIdentifier id)throws SQLException{Set<DomainIdentifier> out=new LinkedHashSet<>();try(PreparedStatement s=c.prepareStatement("SELECT "+column+" FROM "+table+" WHERE authorization_id=? ORDER BY "+column)){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){while(r.next())out.add(dialect.readIdentifier(r,column));}}return Set.copyOf(out);}
    private Set<String> loadStrings(Connection c,String table,String column,DomainIdentifier id)throws SQLException{Set<String> out=new LinkedHashSet<>();try(PreparedStatement s=c.prepareStatement("SELECT "+column+" FROM "+table+" WHERE authorization_id=? ORDER BY "+column)){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){while(r.next())out.add(r.getString(column));}}return Set.copyOf(out);}
    private void insertIds(Connection c,String table,String column,DomainIdentifier id,Set<DomainIdentifier> values)throws SQLException{for(DomainIdentifier value:values)try(PreparedStatement s=c.prepareStatement("INSERT INTO "+table+" (authorization_id,"+column+") VALUES (?,?)")){dialect.bindIdentifier(s,1,id);dialect.bindIdentifier(s,2,value);s.executeUpdate();}}
    private void insertStrings(Connection c,String table,String column,DomainIdentifier id,Set<String> values)throws SQLException{for(String value:values)try(PreparedStatement s=c.prepareStatement("INSERT INTO "+table+" (authorization_id,"+column+") VALUES (?,?)")){dialect.bindIdentifier(s,1,id);s.setString(2,value);s.executeUpdate();}}

    private void insertRevision(String type,DomainIdentifier id,long version,ComplianceStatus status,String proof,String reason,java.time.Instant at,DomainIdentifier actor,String json)throws SQLException{String sql="INSERT INTO "+revisionTable()+" (record_type,record_id,version,status,proof_reference,reason,snapshot_json,recorded_at,recorded_by) VALUES (?,?,?,?,?,?,?,?,?)";try(PreparedStatement s=transaction.requireCurrentConnection().prepareStatement(sql)){s.setString(1,type);dialect.bindIdentifier(s,2,id);s.setLong(3,version);s.setString(4,status.name());setNullableString(s,5,proof);s.setString(6,reason);if(dialect==JdbcDatabaseDialect.POSTGRESQL)s.setString(7,json);else dialect.bindJson(s,7,json);JdbcTemporal.bindInstant(s,8,at);dialect.bindIdentifier(s,9,actor);if(s.executeUpdate()!=1)throw new SQLException("compliance revision insert affected unexpected rows");}}

    private <T>List<T> paged(String baseSql,DomainIdentifier assetId,DomainIdentifier afterId,int limit,Reader<T> reader){String sql=baseSql+(afterId==null?"":" AND id>?")+" ORDER BY id"+(dialect==JdbcDatabaseDialect.POSTGRESQL?" LIMIT ?":" FETCH NEXT ? ROWS ONLY");try(Connection c=dataSource.getConnection();PreparedStatement st=c.prepareStatement(sql)){int i=1;dialect.bindIdentifier(st,i++,assetId);if(afterId!=null)dialect.bindIdentifier(st,i++,afterId);st.setInt(i,limit+1);try(ResultSet r=st.executeQuery()){List<T> out=new ArrayList<>();while(r.next())out.add(reader.read(r));return List.copyOf(out);}}catch(SQLException e){throw fail("page ITAM compliance records",e);}}

    private <T>Optional<T> findOne(String sql,DomainIdentifier id,Reader<T> reader){Connection c=currentConnectionOrNull();boolean close=false;try{if(c==null){c=dataSource.getConnection();close=true;}try(PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(reader.read(r)):Optional.empty();}}}catch(SQLException e){throw fail("find ITAM compliance record",e);}finally{close(c,close);}}
    private <T>List<T> findMany(String sql,DomainIdentifier id,Reader<T> reader){Connection c=currentConnectionOrNull();boolean close=false;try{if(c==null){c=dataSource.getConnection();close=true;}try(PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){List<T> out=new ArrayList<>();while(r.next())out.add(reader.read(r));return List.copyOf(out);}}}catch(SQLException e){throw fail("list ITAM compliance records",e);}finally{close(c,close);}}
    private List<Warranty> dueWarranties(String sql,LocalDate start,LocalDate end){return dueFour(sql,start,end,this::readWarranty);}
    private List<SoftwareLicenseContract> dueLicenses(String sql,LocalDate start,LocalDate end){return dueFour(sql,start,end,this::readLicense);}
    private List<SupportCoverage> dueCoverages(String sql,LocalDate start,LocalDate end){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setDate(1,Date.valueOf(start));s.setDate(2,Date.valueOf(end));try(ResultSet r=s.executeQuery()){List<SupportCoverage> out=new ArrayList<>();while(r.next())out.add(readCoverage(r));return List.copyOf(out);}}catch(SQLException e){throw fail("read due support coverages",e);}}
    private <T>List<T> dueFour(String sql,LocalDate start,LocalDate end,Reader<T> reader){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setDate(1,Date.valueOf(start));s.setDate(2,Date.valueOf(end));s.setDate(3,Date.valueOf(start));s.setDate(4,Date.valueOf(end));try(ResultSet r=s.executeQuery()){List<T> out=new ArrayList<>();while(r.next())out.add(reader.read(r));return List.copyOf(out);}}catch(SQLException e){throw fail("read due compliance records",e);}}

    private Connection currentConnectionOrNull(){try{return transaction.requireCurrentConnection();}catch(IllegalStateException e){return null;}}
    private Connection currentOrNew(){Connection c=currentConnectionOrNull();if(c!=null)return c;try{return dataSource.getConnection();}catch(SQLException e){throw fail("open compliance connection",e);}}
    private static void close(Connection c,boolean close){if(close)try{c.close();}catch(SQLException e){throw fail("close compliance connection",e);}}
    private static void requireInserted(PreparedStatement s,String name)throws SQLException{if(s.executeUpdate()!=1)throw new SQLException(name+" insert affected unexpected rows");}
    private static void requireUpdated(PreparedStatement s,String name)throws SQLException{if(s.executeUpdate()!=1)throw new ComplianceConflictException("VERSION_CONFLICT",name+" version changed");}
    private DomainIdentifier nullableIdentifier(ResultSet r,String c)throws SQLException{return r.getObject(c)==null?null:dialect.readIdentifier(r,c);}
    private static LocalDate nullableDate(ResultSet r,String c)throws SQLException{Date d=r.getDate(c);return d==null?null:d.toLocalDate();}
    private static void setNullableDate(PreparedStatement s,int i,LocalDate d)throws SQLException{if(d==null)s.setNull(i,Types.DATE);else s.setDate(i,Date.valueOf(d));}
    private static void setNullableString(PreparedStatement s,int i,String v)throws SQLException{if(v==null)s.setNull(i,Types.VARCHAR);else s.setString(i,v);}
    private void bindBoolean(PreparedStatement s,int i,boolean v)throws SQLException{if(dialect==JdbcDatabaseDialect.POSTGRESQL)s.setBoolean(i,v);else s.setInt(i,v?1:0);}
    private boolean readBoolean(ResultSet r,String c)throws SQLException{return dialect==JdbcDatabaseDialect.POSTGRESQL?r.getBoolean(c):r.getInt(c)==1;}
    private String booleanTrue(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"TRUE":"1";}

    private static String esc(String s){if(s==null)return "null";return "\""+s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r")+"\"";}
    private static String warrantySnapshot(Warranty w){return "{\"manufacturer_partner_id\":"+esc(w.manufacturerPartnerId().toString())+",\"warranty_type_id\":"+esc(w.warrantyTypeId().toString())+",\"coverage_level\":"+esc(w.coverageLevel())+",\"warranty_start_date\":"+esc(w.warrantyStartDate().toString())+",\"warranty_end_date\":"+esc(w.warrantyEndDate().toString())+",\"manufacturer_support_end_date\":"+esc(w.manufacturerSupportEndDate().toString())+",\"proof_reference\":"+esc(w.proofReference())+",\"status\":"+esc(w.status().wireValue())+"}";}
    private static String licenseSnapshot(SoftwareLicenseContract l){return "{\"publisher_partner_id\":"+esc(l.publisherPartnerId().toString())+",\"contract_number\":"+esc(l.contractNumber())+",\"license_model\":"+esc(l.licenseModel())+",\"usage_rights\":"+esc(l.usageRights())+",\"entitlement_quantity\":"+l.entitlementQuantity()+",\"starts_on\":"+esc(l.startsOn().toString())+",\"ends_on\":"+esc(l.endsOn()==null?null:l.endsOn().toString())+",\"publisher_support_end_date\":"+esc(l.publisherSupportEndDate().toString())+",\"proof_reference\":"+esc(l.proofReference())+",\"status\":"+esc(l.status().wireValue())+"}";}
    private static String authorizationSnapshot(SupportProviderAuthorization a){return "{\"provider_partner_id\":"+esc(a.providerPartnerId().toString())+",\"organization_id\":"+esc(a.organizationId().toString())+",\"service_hours\":"+esc(a.serviceHours())+",\"time_zone_id\":"+esc(a.timeZoneId())+",\"valid_from\":"+esc(a.validFrom().toString())+",\"valid_until\":"+esc(a.validUntil()==null?null:a.validUntil().toString())+",\"status\":"+esc(a.status().wireValue())+"}";}
    private static String coverageSnapshot(SupportCoverage c){return "{\"asset_id\":"+esc(c.assetId().toString())+",\"provider_partner_id\":"+esc(c.providerPartnerId().toString())+",\"authorization_id\":"+esc(c.authorizationId().toString())+",\"coverage_type\":"+esc(c.coverageType())+",\"service_level\":"+esc(c.serviceLevel())+",\"starts_on\":"+esc(c.startsOn().toString())+",\"ends_on\":"+esc(c.endsOn().toString())+",\"proof_reference\":"+esc(c.proofReference())+",\"status\":"+esc(c.status().wireValue())+"}";}

    private static String warrantyColumns(){return "id,asset_id,manufacturer_partner_id,warranty_type_id,coverage_level,warranty_start_date,warranty_end_date,manufacturer_support_end_date,contract_certificate_number,proof_reference,source,status,verified_at,verified_by,version,created_at,updated_at,created_by,updated_by,last_reason";}
    private static String licenseColumns(){return "id,asset_id,publisher_partner_id,contract_number,license_model,usage_rights,entitlement_quantity,starts_on,ends_on,publisher_support_end_date,proof_reference,source,status,verified_at,verified_by,version,created_at,updated_at,created_by,updated_by,last_reason";}
    private static String authColumns(){return "id,provider_partner_id,organization_id,service_hours,time_zone_id,valid_from,valid_until,status,version,created_at,updated_at,created_by,updated_by,last_reason";}
    private static String coverageColumns(){return "id,asset_id,provider_partner_id,authorization_id,contract_reference,coverage_type,service_level,starts_on,ends_on,supported_manufacturer_id,supported_object_type,organization_id,subdivision_id,proof_reference,status,version,created_at,updated_at,created_by,updated_by,last_reason";}
    private String warrantyTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.warranty":"INX_ITAM_WARRANTY";}
    private String warrantyTypeTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.warranty_type":"INX_ITAM_WARRANTY_TYPE";}
    private String licenseTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.software_license_contract":"INX_ITAM_SW_LICENSE";}
    private String authTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.support_provider_authorization":"INX_ITAM_SUPPORT_AUTH";}
    private String authMfrTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.support_authorization_manufacturer":"INX_ITAM_AUTH_MFR";}
    private String authObjTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.support_authorization_object_type":"INX_ITAM_AUTH_OBJ";}
    private String authSubTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.support_authorization_subdivision":"INX_ITAM_AUTH_SUB";}
    private String authSvcTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.support_authorization_service_level":"INX_ITAM_AUTH_SVC";}
    private String authEscTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.support_authorization_escalation_contact":"INX_ITAM_AUTH_ESC";}
    private String coverageTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.support_coverage":"INX_ITAM_SUPPORT_COVERAGE";}
    private String revisionTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.compliance_revision":"INX_ITAM_COMP_REVISION";}
    private String alertTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_itam.compliance_alert_dedup":"INX_ITAM_ALERT_DEDUP";}
    private record AuthorizationCore(DomainIdentifier id,DomainIdentifier provider,DomainIdentifier org,String hours,String tz,LocalDate from,LocalDate until,ComplianceStatus status,long version,java.time.Instant created,java.time.Instant updated,DomainIdentifier createdBy,DomainIdentifier updatedBy,String reason){}
    @FunctionalInterface private interface Reader<T>{T read(ResultSet resultSet)throws SQLException;}
    private static JdbcPersistenceException fail(String operation,SQLException failure){return new JdbcPersistenceException(operation,failure);}
}
