package io.infranexum.adapters.persistence.jdbc;

import io.infranexum.core.contracts.DomainIdentifier;
import io.infranexum.dcim.physical.domain.*;
import io.infranexum.dcim.physical.ports.DcimPhysicalRepository;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.sql.DataSource;

/** PostgreSQL/Oracle adapter for PGM-07-E05 rack occupancy and physical connectivity. */
public final class JdbcDcimPhysicalRepository implements DcimPhysicalRepository {
    private final DataSource dataSource; private final JdbcConnectionAccess tx; private final JdbcDatabaseDialect dialect;
    public JdbcDcimPhysicalRepository(DataSource dataSource,JdbcConnectionAccess tx,JdbcDatabaseDialect dialect){this.dataSource=Objects.requireNonNull(dataSource,"dataSource");this.tx=Objects.requireNonNull(tx,"tx");this.dialect=Objects.requireNonNull(dialect,"dialect");}
    @Override public long rackCount(){return count("SELECT COUNT(*) FROM "+rackTable());}
    @Override public long portCount(){return count("SELECT COUNT(*) FROM "+portTable());}
    @Override public long activeConnectionCount(){return count("SELECT COUNT(*) FROM "+cableTable()+" WHERE lifecycle_status='ACTIVE'");}
    @Override public boolean modelCodeExists(DomainIdentifier org,DomainIdentifier manufacturer,String code){return exists("SELECT 1 FROM "+modelTable()+" WHERE organization_id=? AND manufacturer_partner_id=? AND code=?",s->{dialect.bindIdentifier(s,1,org);dialect.bindIdentifier(s,2,manufacturer);s.setString(3,code.strip());});}
    @Override public boolean rackCodeExists(DomainIdentifier room,String code){return exists("SELECT 1 FROM "+rackTable()+" WHERE room_id=? AND code=?",s->{dialect.bindIdentifier(s,1,room);s.setString(2,code.strip());});}
    @Override public boolean serialExists(String serial){if(serial==null||serial.isBlank())return false;return exists("SELECT 1 FROM "+equipmentTable()+" WHERE serial_number=?",s->s.setString(1,serial.strip()));}
    @Override public Optional<EquipmentModel> model(DomainIdentifier id){return withRead(c->readModel(c,id));}
    @Override public Optional<Rack> rack(DomainIdentifier id){return withRead(c->readRack(c,id));}
    @Override public Optional<Equipment> equipment(DomainIdentifier id){return withRead(c->readEquipment(c,id));}
    @Override public Optional<PhysicalPort> port(DomainIdentifier id){return withRead(c->readPort(c,id));}
    @Override public Optional<CableConnection> cable(DomainIdentifier id){return withRead(c->readCable(c,id));}
    @Override public List<EquipmentModel> models(DomainIdentifier org,int offset,int limit){return withConnection(c->{List<EquipmentModel> out=new ArrayList<>();String sql="SELECT * FROM "+modelTable()+" WHERE organization_id=? ORDER BY id"+offsetSql();try(PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,org);bindOffsetLimit(s,2,offset,limit);try(ResultSet r=s.executeQuery()){while(r.next())out.add(readModelRow(c,r));}}return out;});}
    @Override public List<Rack> racks(DomainIdentifier org,DomainIdentifier room,DomainIdentifier afterId,int limit){return withConnection(c->{String sql="SELECT * FROM "+rackTable()+" WHERE organization_id=?"+(room==null?"":" AND room_id=?")+(afterId==null?"":" AND id>?")+" ORDER BY id"+limitSql();List<Rack> out=new ArrayList<>();try(PreparedStatement s=c.prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,org);if(room!=null)dialect.bindIdentifier(s,i++,room);if(afterId!=null)dialect.bindIdentifier(s,i++,afterId);s.setInt(i,limit);try(ResultSet r=s.executeQuery()){while(r.next())out.add(readRackRow(r));}}return out;});}
    @Override public List<Equipment> equipment(DomainIdentifier org,DomainIdentifier rack,DomainIdentifier afterId,int limit){return withConnection(c->{String sql="SELECT * FROM "+equipmentTable()+" WHERE organization_id=?"+(rack==null?"":" AND rack_id=?")+(afterId==null?"":" AND id>?")+" ORDER BY id"+limitSql();List<Equipment> out=new ArrayList<>();try(PreparedStatement s=c.prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,org);if(rack!=null)dialect.bindIdentifier(s,i++,rack);if(afterId!=null)dialect.bindIdentifier(s,i++,afterId);s.setInt(i,limit);try(ResultSet r=s.executeQuery()){while(r.next())out.add(readEquipmentRow(r));}}return out;});}
    @Override public List<PhysicalPort> ports(DomainIdentifier equipmentId,int offset,int limit){return withConnection(c->{List<PhysicalPort> out=new ArrayList<>();String sql="SELECT p.* FROM "+portTable()+" p WHERE p.equipment_id=? ORDER BY p.port_name,p.id"+offsetSql();try(PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,equipmentId);bindOffsetLimit(s,2,offset,limit);try(ResultSet r=s.executeQuery()){while(r.next())out.add(readPortRow(c,r));}}return out;});}
    @Override public List<CableConnection> cables(DomainIdentifier org,DomainIdentifier afterId,int limit){return withConnection(c->{List<CableConnection> out=new ArrayList<>();String sql="SELECT * FROM "+cableTable()+" WHERE organization_id=?"+(afterId==null?"":" AND id>?")+" ORDER BY id"+limitSql();try(PreparedStatement s=c.prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,org);if(afterId!=null)dialect.bindIdentifier(s,i++,afterId);s.setInt(i,limit);try(ResultSet r=s.executeQuery()){while(r.next())out.add(readCableRow(r));}}return out;});}
    @Override public void lockRackForOccupancy(DomainIdentifier rackId){
        lockIdentifierRow(rackTable(),rackId,"rack occupancy");
    }
    @Override public void lockPortsForConnection(DomainIdentifier portAId,DomainIdentifier portBId){
        DomainIdentifier first=portAId.toString().compareTo(portBId.toString())<=0?portAId:portBId;
        DomainIdentifier second=first.equals(portAId)?portBId:portAId;
        lockIdentifierRow(portTable(),first,"physical port");
        lockIdentifierRow(portTable(),second,"physical port");
    }
    @Override public boolean footprintOccupied(DomainIdentifier rack,int startU,int endU,DomainIdentifier excluding){String sql="SELECT 1 FROM "+equipmentTable()+" e JOIN "+modelTable()+" m ON m.id=e.model_id WHERE e.rack_id=? AND e.lifecycle_status IN ('ACTIVE','MAINTENANCE') AND e.start_u<=? AND (e.start_u+m.rack_units-1)>=?"+(excluding==null?"":" AND e.id<>?");return exists(sql,s->{int i=1;dialect.bindIdentifier(s,i++,rack);s.setInt(i++,endU);s.setInt(i++,startU);if(excluding!=null)dialect.bindIdentifier(s,i,excluding);});}
    @Override public boolean equipmentHasActiveCable(DomainIdentifier equipmentId){String sql="SELECT 1 FROM "+cableTable()+" c JOIN "+portTable()+" a ON a.id=c.port_a_id JOIN "+portTable()+" b ON b.id=c.port_b_id WHERE c.lifecycle_status='ACTIVE' AND (a.equipment_id=? OR b.equipment_id=?)";return exists(sql,s->{dialect.bindIdentifier(s,1,equipmentId);dialect.bindIdentifier(s,2,equipmentId);});}
    @Override public boolean portConnected(DomainIdentifier portId){return exists("SELECT 1 FROM "+cableTable()+" WHERE lifecycle_status='ACTIVE' AND (port_a_id=? OR port_b_id=?)",s->{dialect.bindIdentifier(s,1,portId);dialect.bindIdentifier(s,2,portId);});}
    @Override public void insertModel(EquipmentModel m){try{Connection c=tx.requireCurrentConnection();try(PreparedStatement s=c.prepareStatement("INSERT INTO "+modelTable()+" (id,organization_id,manufacturer_partner_id,code,display_name,form_factor,rack_units,width_mm,depth_mm,weight_kg,lifecycle_status,description,version,created_at,updated_at,created_by,updated_by,last_reason) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){int i=1;dialect.bindIdentifier(s,i++,m.id());dialect.bindIdentifier(s,i++,m.organizationId());dialect.bindIdentifier(s,i++,m.manufacturerPartnerId());s.setString(i++,m.code());s.setString(i++,m.displayName());s.setString(i++,m.formFactor());s.setInt(i++,m.rackUnits());s.setInt(i++,m.widthMm());s.setInt(i++,m.depthMm());s.setBigDecimal(i++,m.weightKg());s.setString(i++,m.status().name());setString(s,i++,m.description());s.setLong(i++,m.version());JdbcTemporal.bindInstant(s,i++,m.createdAt());JdbcTemporal.bindInstant(s,i++,m.updatedAt());dialect.bindIdentifier(s,i++,m.createdBy());dialect.bindIdentifier(s,i++,m.updatedBy());s.setString(i,m.lastReason());one(s,"model insert");}int ordinal=1;for(PortTemplate t:m.portTemplates()){try(PreparedStatement s=c.prepareStatement("INSERT INTO "+templateTable()+" (model_id,ordinal,name_prefix,port_count,port_kind,media,connector) VALUES (?,?,?,?,?,?,?)")){dialect.bindIdentifier(s,1,m.id());s.setInt(2,ordinal++);s.setString(3,t.namePrefix());s.setInt(4,t.count());s.setString(5,t.kind().name());s.setString(6,t.media());s.setString(7,t.connector());one(s,"port template insert");}}}catch(SQLException e){throw uniqueOrFail("insert equipment model",e,"DCIM_MODEL_DUPLICATE");}}
    @Override public void updateModel(EquipmentModel m,long expected){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("UPDATE "+modelTable()+" SET lifecycle_status=?,version=?,updated_at=?,updated_by=?,last_reason=? WHERE id=? AND version=?")){s.setString(1,m.status().name());s.setLong(2,m.version());JdbcTemporal.bindInstant(s,3,m.updatedAt());dialect.bindIdentifier(s,4,m.updatedBy());s.setString(5,m.lastReason());dialect.bindIdentifier(s,6,m.id());s.setLong(7,expected);versioned(s,"equipment model");}catch(SQLException e){throw fail("update equipment model",e);}}
    @Override public void insertRack(Rack r){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("INSERT INTO "+rackTable()+" (id,organization_id,subdivision_id,room_id,code,display_name,height_u,width_mm,depth_mm,lifecycle_status,version,created_at,updated_at,created_by,updated_by,last_reason) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){int i=1;dialect.bindIdentifier(s,i++,r.id());dialect.bindIdentifier(s,i++,r.organizationId());dialect.bindIdentifier(s,i++,r.subdivisionId());dialect.bindIdentifier(s,i++,r.roomId());s.setString(i++,r.code());s.setString(i++,r.displayName());s.setInt(i++,r.heightU());s.setInt(i++,r.widthMm());s.setInt(i++,r.depthMm());s.setString(i++,r.status().name());s.setLong(i++,r.version());JdbcTemporal.bindInstant(s,i++,r.createdAt());JdbcTemporal.bindInstant(s,i++,r.updatedAt());dialect.bindIdentifier(s,i++,r.createdBy());dialect.bindIdentifier(s,i++,r.updatedBy());s.setString(i,r.lastReason());one(s,"rack insert");}catch(SQLException e){throw uniqueOrFail("insert rack",e,"DCIM_RACK_DUPLICATE");}}
    @Override public void updateRack(Rack r,long expected){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("UPDATE "+rackTable()+" SET lifecycle_status=?,version=?,updated_at=?,updated_by=?,last_reason=? WHERE id=? AND version=?")){s.setString(1,r.status().name());s.setLong(2,r.version());JdbcTemporal.bindInstant(s,3,r.updatedAt());dialect.bindIdentifier(s,4,r.updatedBy());s.setString(5,r.lastReason());dialect.bindIdentifier(s,6,r.id());s.setLong(7,expected);versioned(s,"rack");}catch(SQLException e){throw fail("update rack",e);}}
    @Override public void insertEquipment(Equipment e,List<PhysicalPort> ports){try{Connection c=tx.requireCurrentConnection();try(PreparedStatement s=c.prepareStatement("INSERT INTO "+equipmentTable()+" (id,organization_id,subdivision_id,rack_id,model_id,rsot_object_id,itam_asset_id,serial_number,asset_tag,start_u,face,lifecycle_status,version,created_at,updated_at,created_by,updated_by,last_reason) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){int i=1;dialect.bindIdentifier(s,i++,e.id());dialect.bindIdentifier(s,i++,e.organizationId());dialect.bindIdentifier(s,i++,e.subdivisionId());dialect.bindIdentifier(s,i++,e.rackId());dialect.bindIdentifier(s,i++,e.modelId());dialect.bindIdentifier(s,i++,e.rsotObjectId());dialect.bindNullableIdentifier(s,i++,e.itamAssetId());setString(s,i++,e.serialNumber());setString(s,i++,e.assetTag());s.setInt(i++,e.startU());s.setString(i++,e.face());s.setString(i++,e.status().name());s.setLong(i++,e.version());JdbcTemporal.bindInstant(s,i++,e.createdAt());JdbcTemporal.bindInstant(s,i++,e.updatedAt());dialect.bindIdentifier(s,i++,e.createdBy());dialect.bindIdentifier(s,i++,e.updatedBy());s.setString(i,e.lastReason());one(s,"equipment insert");}for(PhysicalPort port:ports){try(PreparedStatement s=c.prepareStatement("INSERT INTO "+portTable()+" (id,organization_id,equipment_id,port_name,port_kind,media,connector) VALUES (?,?,?,?,?,?,?)")){dialect.bindIdentifier(s,1,port.id());dialect.bindIdentifier(s,2,port.organizationId());dialect.bindIdentifier(s,3,port.equipmentId());s.setString(4,port.name());s.setString(5,port.kind().name());s.setString(6,port.media());s.setString(7,port.connector());one(s,"physical port insert");}}}catch(SQLException x){throw uniqueOrFail("insert equipment",x,"DCIM_EQUIPMENT_DUPLICATE");}}
    @Override public void updateEquipment(Equipment e,long expected){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("UPDATE "+equipmentTable()+" SET rack_id=?,start_u=?,face=?,lifecycle_status=?,version=?,updated_at=?,updated_by=?,last_reason=? WHERE id=? AND version=?")){int i=1;dialect.bindIdentifier(s,i++,e.rackId());s.setInt(i++,e.startU());s.setString(i++,e.face());s.setString(i++,e.status().name());s.setLong(i++,e.version());JdbcTemporal.bindInstant(s,i++,e.updatedAt());dialect.bindIdentifier(s,i++,e.updatedBy());s.setString(i++,e.lastReason());dialect.bindIdentifier(s,i++,e.id());s.setLong(i,expected);versioned(s,"equipment");}catch(SQLException x){throw fail("update equipment",x);}}
    @Override public void insertCable(CableConnection c){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("INSERT INTO "+cableTable()+" (id,organization_id,subdivision_id,port_a_id,port_b_id,label,media,connector,lifecycle_status,version,created_at,updated_at,created_by,updated_by,last_reason) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){int i=1;dialect.bindIdentifier(s,i++,c.id());dialect.bindIdentifier(s,i++,c.organizationId());dialect.bindIdentifier(s,i++,c.subdivisionId());dialect.bindIdentifier(s,i++,c.portAId());dialect.bindIdentifier(s,i++,c.portBId());s.setString(i++,c.label());s.setString(i++,c.media());s.setString(i++,c.connector());s.setString(i++,c.status().name());s.setLong(i++,c.version());JdbcTemporal.bindInstant(s,i++,c.createdAt());JdbcTemporal.bindInstant(s,i++,c.updatedAt());dialect.bindIdentifier(s,i++,c.createdBy());dialect.bindIdentifier(s,i++,c.updatedBy());s.setString(i,c.lastReason());one(s,"cable insert");}catch(SQLException e){throw uniqueOrFail("insert cable",e,"DCIM_PORT_ALREADY_CONNECTED");}}
    @Override public void updateCable(CableConnection c,long expected){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("UPDATE "+cableTable()+" SET lifecycle_status=?,version=?,updated_at=?,updated_by=?,last_reason=? WHERE id=? AND version=?")){s.setString(1,c.status().name());s.setLong(2,c.version());JdbcTemporal.bindInstant(s,3,c.updatedAt());dialect.bindIdentifier(s,4,c.updatedBy());s.setString(5,c.lastReason());dialect.bindIdentifier(s,6,c.id());s.setLong(7,expected);versioned(s,"cable");}catch(SQLException e){throw fail("update cable",e);}}

    private Optional<EquipmentModel> readModel(Connection c,DomainIdentifier id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM "+modelTable()+" WHERE id=?")){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(readModelRow(c,r)):Optional.empty();}}}
    private void lockIdentifierRow(String table,DomainIdentifier id,String subject){
        try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("SELECT id FROM "+table+" WHERE id=? FOR UPDATE")){
            dialect.bindIdentifier(s,1,id);
            try(ResultSet r=s.executeQuery()){if(!r.next())throw new DcimPhysicalNotFoundException(subject);}
        }catch(SQLException e){throw fail("lock "+subject,e);}
    }
    private EquipmentModel readModelRow(Connection c,ResultSet r)throws SQLException{DomainIdentifier id=dialect.readIdentifier(r,"id");List<PortTemplate> templates=new ArrayList<>();try(PreparedStatement s=c.prepareStatement("SELECT * FROM "+templateTable()+" WHERE model_id=? ORDER BY ordinal")){dialect.bindIdentifier(s,1,id);try(ResultSet t=s.executeQuery()){while(t.next())templates.add(new PortTemplate(t.getString("name_prefix"),t.getInt("port_count"),PortKind.valueOf(t.getString("port_kind")),t.getString("media"),t.getString("connector")));}}return EquipmentModel.restore(id,dialect.readIdentifier(r,"organization_id"),dialect.readIdentifier(r,"manufacturer_partner_id"),r.getString("code"),r.getString("display_name"),r.getString("form_factor"),r.getInt("rack_units"),r.getInt("width_mm"),r.getInt("depth_mm"),r.getBigDecimal("weight_kg"),templates,PhysicalStatus.valueOf(r.getString("lifecycle_status")),r.getString("description"),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"),dialect.readIdentifier(r,"created_by"),dialect.readIdentifier(r,"updated_by"),r.getString("last_reason"));}
    private Optional<Rack> readRack(Connection c,DomainIdentifier id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM "+rackTable()+" WHERE id=?")){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(readRackRow(r)):Optional.empty();}}}
    private Rack readRackRow(ResultSet r)throws SQLException{return Rack.restore(dialect.readIdentifier(r,"id"),dialect.readIdentifier(r,"organization_id"),dialect.readIdentifier(r,"subdivision_id"),dialect.readIdentifier(r,"room_id"),r.getString("code"),r.getString("display_name"),r.getInt("height_u"),r.getInt("width_mm"),r.getInt("depth_mm"),PhysicalStatus.valueOf(r.getString("lifecycle_status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"),dialect.readIdentifier(r,"created_by"),dialect.readIdentifier(r,"updated_by"),r.getString("last_reason"));}
    private Optional<Equipment> readEquipment(Connection c,DomainIdentifier id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM "+equipmentTable()+" WHERE id=?")){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(readEquipmentRow(r)):Optional.empty();}}}
    private Equipment readEquipmentRow(ResultSet r)throws SQLException{return Equipment.restore(dialect.readIdentifier(r,"id"),dialect.readIdentifier(r,"organization_id"),dialect.readIdentifier(r,"subdivision_id"),dialect.readIdentifier(r,"rack_id"),dialect.readIdentifier(r,"model_id"),dialect.readIdentifier(r,"rsot_object_id"),nullableId(r,"itam_asset_id"),r.getString("serial_number"),r.getString("asset_tag"),r.getInt("start_u"),r.getString("face"),PhysicalStatus.valueOf(r.getString("lifecycle_status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"),dialect.readIdentifier(r,"created_by"),dialect.readIdentifier(r,"updated_by"),r.getString("last_reason"));}
    private Optional<PhysicalPort> readPort(Connection c,DomainIdentifier id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM "+portTable()+" WHERE id=?")){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(readPortRow(c,r)):Optional.empty();}}}
    private PhysicalPort readPortRow(Connection c,ResultSet r)throws SQLException{DomainIdentifier id=dialect.readIdentifier(r,"id");return new PhysicalPort(id,dialect.readIdentifier(r,"organization_id"),dialect.readIdentifier(r,"equipment_id"),r.getString("port_name"),PortKind.valueOf(r.getString("port_kind")),r.getString("media"),r.getString("connector"),portConnected(c,id));}
    private Optional<CableConnection> readCable(Connection c,DomainIdentifier id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM "+cableTable()+" WHERE id=?")){dialect.bindIdentifier(s,1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(readCableRow(r)):Optional.empty();}}}
    private CableConnection readCableRow(ResultSet r)throws SQLException{return CableConnection.restore(dialect.readIdentifier(r,"id"),dialect.readIdentifier(r,"organization_id"),dialect.readIdentifier(r,"subdivision_id"),dialect.readIdentifier(r,"port_a_id"),dialect.readIdentifier(r,"port_b_id"),r.getString("label"),r.getString("media"),r.getString("connector"),PhysicalStatus.valueOf(r.getString("lifecycle_status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"),dialect.readIdentifier(r,"created_by"),dialect.readIdentifier(r,"updated_by"),r.getString("last_reason"));}
    private boolean portConnected(Connection c,DomainIdentifier id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT 1 FROM "+cableTable()+" WHERE lifecycle_status='ACTIVE' AND (port_a_id=? OR port_b_id=?)")){dialect.bindIdentifier(s,1,id);dialect.bindIdentifier(s,2,id);try(ResultSet r=s.executeQuery()){return r.next();}}}
    private long count(String sql){return withConnection(c->{try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){if(!r.next())throw new SQLException("count returned no row");return r.getLong(1);}});}
    private boolean exists(String sql,Binder binder){return withConnection(c->{try(PreparedStatement s=c.prepareStatement(sql)){binder.bind(s);try(ResultSet r=s.executeQuery()){return r.next();}}});}
    private DomainIdentifier nullableId(ResultSet r,String column)throws SQLException{Object v=r.getObject(column);return v==null?null:dialect.readIdentifier(r,column);}
    private String offsetSql(){return dialect==JdbcDatabaseDialect.POSTGRESQL?" LIMIT ? OFFSET ?":" OFFSET ? ROWS FETCH NEXT ? ROWS ONLY";}
    private void bindOffsetLimit(PreparedStatement s,int index,int offset,int limit)throws SQLException{if(dialect==JdbcDatabaseDialect.POSTGRESQL){s.setInt(index,limit);s.setInt(index+1,offset);}else{s.setInt(index,offset);s.setInt(index+1,limit);}}
    private String limitSql(){return dialect==JdbcDatabaseDialect.POSTGRESQL?" LIMIT ?":" FETCH NEXT ? ROWS ONLY";} private String modelTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_dcim.equipment_model":"INFRANEXUM_DCIM_MODEL";} private String templateTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_dcim.model_port_template":"INFRANEXUM_DCIM_MODEL_PORT";} private String rackTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_dcim.rack":"INFRANEXUM_DCIM_RACK";} private String equipmentTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_dcim.equipment":"INFRANEXUM_DCIM_EQUIP";} private String portTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_dcim.physical_port":"INFRANEXUM_DCIM_PORT";} private String cableTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_dcim.cable_connection":"INFRANEXUM_DCIM_CABLE";}
    private <T>Optional<T> withRead(SqlOptional<T> work){Connection current=current();if(current!=null){try{return work.run(current);}catch(SQLException e){throw fail("read DCIM physical object",e);}}try(Connection c=dataSource.getConnection()){return work.run(c);}catch(SQLException e){throw fail("read DCIM physical object",e);}}
    private <T>T withConnection(SqlWork<T> work){Connection current=current();if(current!=null){try{return work.run(current);}catch(SQLException e){throw fail("query DCIM physical objects",e);}}try(Connection c=dataSource.getConnection()){return work.run(c);}catch(SQLException e){throw fail("query DCIM physical objects",e);}}
    private Connection current(){try{return tx.requireCurrentConnection();}catch(IllegalStateException none){return null;}} private void one(PreparedStatement s,String what)throws SQLException{if(s.executeUpdate()!=1)throw new SQLException(what+" affected unexpected rows");} private void versioned(PreparedStatement s,String what)throws SQLException{if(s.executeUpdate()!=1)throw new DcimPhysicalConflictException("VERSION_CONFLICT",what+" version changed");} private void setString(PreparedStatement s,int i,String v)throws SQLException{if(v==null)s.setNull(i,Types.VARCHAR);else s.setString(i,v);} private RuntimeException uniqueOrFail(String op,SQLException e,String code){return dialect.isUniqueViolation(e)?new DcimPhysicalConflictException(code,op+" violates a uniqueness constraint"):fail(op,e);} private static JdbcPersistenceException fail(String op,SQLException e){return new JdbcPersistenceException(op,e);}
    @FunctionalInterface private interface Binder{void bind(PreparedStatement s)throws SQLException;} @FunctionalInterface private interface SqlWork<T>{T run(Connection c)throws SQLException;} @FunctionalInterface private interface SqlOptional<T>{Optional<T> run(Connection c)throws SQLException;}
}
