package io.infranexum.adapters.persistence.jdbc;

import io.infranexum.core.contracts.DomainIdentifier;
import io.infranexum.ddi.ipam.domain.*;
import io.infranexum.ddi.ipam.ports.IpamRepository;
import java.sql.*;
import java.util.*;
import javax.sql.DataSource;

/** PostgreSQL/Oracle repository for PGM-08-E01 DDI/IPAM. */
public final class JdbcIpamRepository implements IpamRepository {
 private final DataSource dataSource;private final JdbcConnectionAccess tx;private final JdbcDatabaseDialect dialect;public JdbcIpamRepository(DataSource ds,JdbcConnectionAccess tx,JdbcDatabaseDialect d){dataSource=Objects.requireNonNull(ds);this.tx=Objects.requireNonNull(tx);dialect=Objects.requireNonNull(d);}
 @Override public long countVrfs(){return count(vrfTable());}@Override public long countVlans(){return count(vlanTable());}@Override public long countNetworks(){return count(netTable());}@Override public long countAddresses(){return count(addrTable());}
 private long count(String table){return withConn(c->{try(PreparedStatement s=c.prepareStatement("SELECT COUNT(*) FROM "+table);ResultSet r=s.executeQuery()){r.next();return r.getLong(1);}});}
 @Override public void lockRoutingEnvironment(DomainIdentifier org,DomainIdentifier vrf){String sql="SELECT id FROM "+vrfTable()+" WHERE id=? AND organization_id=? FOR UPDATE";try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement(sql)){dialect.bindIdentifier(s,1,vrf);dialect.bindIdentifier(s,2,org);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IpamNotFoundException("VRF");}}catch(SQLException e){throw fail("lock IPAM routing environment",e);}}
 @Override public void lockPool(DomainIdentifier pool){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("SELECT id FROM "+poolTable()+" WHERE id=? FOR UPDATE")){dialect.bindIdentifier(s,1,pool);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IpamNotFoundException("pool");}}catch(SQLException e){throw fail("lock IPAM pool",e);}}
 @Override public boolean hasActiveNetworks(DomainIdentifier vrf){return exists("SELECT 1 FROM "+netTable()+" WHERE vrf_id=? AND lifecycle_status<>'RETIRED'",s->dialect.bindIdentifier(s,1,vrf));}
 @Override public boolean hasActiveNetworksForVlan(DomainIdentifier vlan){return exists("SELECT 1 FROM "+netTable()+" WHERE vlan_id=? AND lifecycle_status<>'RETIRED'",s->dialect.bindIdentifier(s,1,vlan));}
 @Override public boolean vrfCodeExists(DomainIdentifier org,String code){return exists("SELECT 1 FROM "+vrfTable()+" WHERE organization_id=? AND code=?",s->{dialect.bindIdentifier(s,1,org);s.setString(2,code.strip());});}
 @Override public boolean vlanExists(DomainIdentifier org,Integer vlan,Long vni){String sql="SELECT 1 FROM "+vlanTable()+" WHERE organization_id=? AND lifecycle_status<>'RETIRED' AND ((? IS NOT NULL AND vlan_id=?) OR (? IS NOT NULL AND vni=?))";return exists(sql,s->{dialect.bindIdentifier(s,1,org);if(vlan==null){s.setNull(2,Types.INTEGER);s.setNull(3,Types.INTEGER);}else{s.setInt(2,vlan);s.setInt(3,vlan);}if(vni==null){s.setNull(4,Types.BIGINT);s.setNull(5,Types.BIGINT);}else{s.setLong(4,vni);s.setLong(5,vni);}});}
 @Override public boolean networkOverlaps(DomainIdentifier org,DomainIdentifier vrf,IpCidr cidr,DomainIdentifier excluding){String sql="SELECT 1 FROM "+netTable()+" WHERE organization_id=? AND vrf_id=? AND address_family=? AND lifecycle_status<>'RETIRED' AND first_key<=? AND last_key>=?"+(excluding==null?"":" AND id<>?");return exists(sql,s->{int i=1;dialect.bindIdentifier(s,i++,org);dialect.bindIdentifier(s,i++,vrf);s.setInt(i++,cidr.addressBits()==32?4:6);s.setString(i++,cidr.lastSortKey());s.setString(i++,cidr.firstSortKey());if(excluding!=null)dialect.bindIdentifier(s,i,excluding);});}
 @Override public boolean addressInUse(DomainIdentifier vrf,String address){return exists("SELECT 1 FROM "+addrTable()+" WHERE vrf_id=? AND address_value=? AND lifecycle_status IN ('ALLOCATED','RESERVED','DEPRECATED')",s->{dialect.bindIdentifier(s,1,vrf);s.setString(2,IpCidr.canonicalAddress(address));});}
 @Override public boolean poolOverlaps(DomainIdentifier network,String start,String end){IpCidr net=requireNetwork(network).cidr();String a=IpCidr.canonicalAddress(start),b=IpCidr.canonicalAddress(end);if(!net.containsAddress(a)||!net.containsAddress(b))return true;String ak=IpCidr.sortKey(a),bk=IpCidr.sortKey(b);if(ak.compareTo(bk)>0)throw new IllegalArgumentException("pool start must not exceed end");return exists("SELECT 1 FROM "+poolTable()+" WHERE network_id=? AND lifecycle_status<>'RETIRED' AND start_key<=? AND end_key>=?",s->{dialect.bindIdentifier(s,1,network);s.setString(2,bk);s.setString(3,ak);});}
 @Override public Optional<IpamVrf> vrf(DomainIdentifier id){return one("SELECT id,organization_id,code,display_name,route_distinguisher,lifecycle_status,version,created_at,updated_at FROM "+vrfTable()+" WHERE id=?",id,this::readVrf);}
 @Override public Optional<IpamVlan> vlan(DomainIdentifier id){return one("SELECT id,organization_id,site_id,vlan_id,vni,name,lifecycle_status,version,created_at,updated_at FROM "+vlanTable()+" WHERE id=?",id,this::readVlan);}
 @Override public Optional<IpamNetwork> network(DomainIdentifier id){return one("SELECT id,organization_id,subdivision_id,site_id,vrf_id,vlan_id,parent_network_id,network_kind,cidr_value,usage_text,trust_level,lifecycle_status,version,created_at,updated_at FROM "+netTable()+" WHERE id=?",id,this::readNetwork);}
 @Override public Optional<IpamPool> pool(DomainIdentifier id){return one("SELECT id,organization_id,network_id,start_address,end_address,allocation_cursor,name,lifecycle_status,version,created_at,updated_at FROM "+poolTable()+" WHERE id=?",id,this::readPool);}
 @Override public Optional<IpamAddress> address(DomainIdentifier id){return one("SELECT id,organization_id,vrf_id,network_id,pool_id,address_value,lifecycle_status,hostname,rsot_object_id,dcim_equipment_id,purpose,version,created_at,updated_at FROM "+addrTable()+" WHERE id=?",id,this::readAddress);}
 @Override public List<IpamVrf> vrfs(DomainIdentifier org,int limit){return list("SELECT id,organization_id,code,display_name,route_distinguisher,lifecycle_status,version,created_at,updated_at FROM "+vrfTable()+" WHERE organization_id=? ORDER BY id"+lim(),s->{dialect.bindIdentifier(s,1,org);return 2;},limit,this::readVrf);}
 @Override public List<IpamVlan> vlans(DomainIdentifier org,int limit){return list("SELECT id,organization_id,site_id,vlan_id,vni,name,lifecycle_status,version,created_at,updated_at FROM "+vlanTable()+" WHERE organization_id=? ORDER BY id"+lim(),s->{dialect.bindIdentifier(s,1,org);return 2;},limit,this::readVlan);}
 @Override public List<IpamNetwork> networks(DomainIdentifier org,DomainIdentifier vrf,int limit){String sql="SELECT id,organization_id,subdivision_id,site_id,vrf_id,vlan_id,parent_network_id,network_kind,cidr_value,usage_text,trust_level,lifecycle_status,version,created_at,updated_at FROM "+netTable()+" WHERE organization_id=?"+(vrf==null?"":" AND vrf_id=?")+" ORDER BY id"+lim();return list(sql,s->{int i=1;dialect.bindIdentifier(s,i++,org);if(vrf!=null)dialect.bindIdentifier(s,i++,vrf);return i;},limit,this::readNetwork);}
 @Override public List<IpamPool> pools(DomainIdentifier network,int limit){return list("SELECT id,organization_id,network_id,start_address,end_address,allocation_cursor,name,lifecycle_status,version,created_at,updated_at FROM "+poolTable()+" WHERE network_id=? ORDER BY id"+lim(),s->{dialect.bindIdentifier(s,1,network);return 2;},limit,this::readPool);}
 @Override public List<IpamAddress> addresses(DomainIdentifier org,DomainIdentifier vrf,DomainIdentifier network,int limit){StringBuilder q=new StringBuilder("SELECT id,organization_id,vrf_id,network_id,pool_id,address_value,lifecycle_status,hostname,rsot_object_id,dcim_equipment_id,purpose,version,created_at,updated_at FROM ").append(addrTable()).append(" WHERE organization_id=?");if(vrf!=null)q.append(" AND vrf_id=?");if(network!=null)q.append(" AND network_id=?");q.append(" ORDER BY id").append(lim());return list(q.toString(),s->{int i=1;dialect.bindIdentifier(s,i++,org);if(vrf!=null)dialect.bindIdentifier(s,i++,vrf);if(network!=null)dialect.bindIdentifier(s,i++,network);return i;},limit,this::readAddress);}
 @Override public void insertVrf(IpamVrf v){execInsert("INSERT INTO "+vrfTable()+" (id,organization_id,code,display_name,route_distinguisher,lifecycle_status,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)",s->{int i=1;id(s,i++,v.id());id(s,i++,v.organizationId());s.setString(i++,v.code());s.setString(i++,v.displayName());str(s,i++,v.routeDistinguisher());s.setString(i++,v.status().name());s.setLong(i++,v.version());time(s,i++,v.createdAt());time(s,i,v.updatedAt());},"insert VRF");}
 @Override public void updateVrf(IpamVrf v,long expected){execUpdate("UPDATE "+vrfTable()+" SET lifecycle_status=?,version=?,updated_at=? WHERE id=? AND version=?",s->{s.setString(1,v.status().name());s.setLong(2,v.version());time(s,3,v.updatedAt());id(s,4,v.id());s.setLong(5,expected);},"update VRF");}
 @Override public void insertVlan(IpamVlan v){execInsert("INSERT INTO "+vlanTable()+" (id,organization_id,site_id,vlan_id,vni,name,lifecycle_status,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)",s->{int i=1;id(s,i++,v.id());id(s,i++,v.organizationId());nid(s,i++,v.siteId());integer(s,i++,v.vlanId());big(s,i++,v.vni());s.setString(i++,v.name());s.setString(i++,v.status().name());s.setLong(i++,v.version());time(s,i++,v.createdAt());time(s,i,v.updatedAt());},"insert VLAN");}
 @Override public void updateVlan(IpamVlan v,long expected){execUpdate("UPDATE "+vlanTable()+" SET lifecycle_status=?,version=?,updated_at=? WHERE id=? AND version=?",s->{s.setString(1,v.status().name());s.setLong(2,v.version());time(s,3,v.updatedAt());id(s,4,v.id());s.setLong(5,expected);},"update VLAN");}
 @Override public void insertNetwork(IpamNetwork n){execInsert("INSERT INTO "+netTable()+" (id,organization_id,subdivision_id,site_id,vrf_id,vlan_id,parent_network_id,network_kind,cidr_value,address_family,prefix_length,first_address,last_address,first_key,last_key,usage_text,trust_level,lifecycle_status,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",s->{int i=1;id(s,i++,n.id());id(s,i++,n.organizationId());nid(s,i++,n.subdivisionId());nid(s,i++,n.siteId());id(s,i++,n.vrfId());nid(s,i++,n.vlanId());nid(s,i++,n.parentNetworkId());s.setString(i++,n.kind().name());s.setString(i++,n.cidr().value());s.setInt(i++,n.cidr().addressBits()==32?4:6);s.setInt(i++,n.cidr().prefixLength());s.setString(i++,n.cidr().firstAddress());s.setString(i++,n.cidr().lastAddress());s.setString(i++,n.cidr().firstSortKey());s.setString(i++,n.cidr().lastSortKey());str(s,i++,n.usage());str(s,i++,n.trustLevel());s.setString(i++,n.status().name());s.setLong(i++,n.version());time(s,i++,n.createdAt());time(s,i,n.updatedAt());},"insert IP network");}
 @Override public void updateNetwork(IpamNetwork n,long expected){execUpdate("UPDATE "+netTable()+" SET vlan_id=?,usage_text=?,trust_level=?,lifecycle_status=?,version=?,updated_at=? WHERE id=? AND version=?",s->{nid(s,1,n.vlanId());str(s,2,n.usage());str(s,3,n.trustLevel());s.setString(4,n.status().name());s.setLong(5,n.version());time(s,6,n.updatedAt());id(s,7,n.id());s.setLong(8,expected);},"update IP network");}
 @Override public void insertPool(IpamPool p){execInsert("INSERT INTO "+poolTable()+" (id,organization_id,network_id,start_address,end_address,allocation_cursor,start_key,end_key,name,lifecycle_status,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",s->{int i=1;id(s,i++,p.id());id(s,i++,p.organizationId());id(s,i++,p.networkId());s.setString(i++,p.startAddress());s.setString(i++,p.endAddress());s.setString(i++,p.allocationCursor());s.setString(i++,IpCidr.sortKey(p.startAddress()));s.setString(i++,IpCidr.sortKey(p.endAddress()));s.setString(i++,p.name());s.setString(i++,p.status().name());s.setLong(i++,p.version());time(s,i++,p.createdAt());time(s,i,p.updatedAt());},"insert IP pool");}
 @Override public void updatePool(IpamPool p,long expected){execUpdate("UPDATE "+poolTable()+" SET allocation_cursor=?,version=?,updated_at=? WHERE id=? AND version=?",s->{s.setString(1,p.allocationCursor());s.setLong(2,p.version());time(s,3,p.updatedAt());id(s,4,p.id());s.setLong(5,expected);},"update IP pool");}
 @Override public void insertAddress(IpamAddress a){execInsert("INSERT INTO "+addrTable()+" (id,organization_id,vrf_id,network_id,pool_id,address_value,lifecycle_status,hostname,rsot_object_id,dcim_equipment_id,purpose,allocation_token,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",s->{int i=1;id(s,i++,a.id());id(s,i++,a.organizationId());id(s,i++,a.vrfId());id(s,i++,a.networkId());nid(s,i++,a.poolId());s.setString(i++,a.address());s.setString(i++,a.status().name());str(s,i++,a.hostname());nid(s,i++,a.rsotObjectId());nid(s,i++,a.dcimEquipmentId());str(s,i++,a.purpose());s.setString(i++,token(a));s.setLong(i++,a.version());time(s,i++,a.createdAt());time(s,i,a.updatedAt());},"insert IP address");}
 @Override public void updateAddress(IpamAddress a,long expected){execUpdate("UPDATE "+addrTable()+" SET lifecycle_status=?,allocation_token=?,version=?,updated_at=? WHERE id=? AND version=?",s->{s.setString(1,a.status().name());s.setString(2,token(a));s.setLong(3,a.version());time(s,4,a.updatedAt());id(s,5,a.id());s.setLong(6,expected);},"update IP address");}
 private String token(IpamAddress a){return a.status()==AddressStatus.RELEASED?a.id().toString():"ACTIVE";}private IpamNetwork requireNetwork(DomainIdentifier id){return network(id).orElseThrow(()->new IpamNotFoundException("network"));}
 private IpamVrf readVrf(ResultSet r)throws SQLException{return new IpamVrf(id(r,"id"),id(r,"organization_id"),r.getString("code"),r.getString("display_name"),r.getString("route_distinguisher"),IpamStatus.valueOf(r.getString("lifecycle_status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"));}
 private IpamVlan readVlan(ResultSet r)throws SQLException{return new IpamVlan(id(r,"id"),id(r,"organization_id"),nid(r,"site_id"),nullableInt(r,"vlan_id"),nullableLong(r,"vni"),r.getString("name"),IpamStatus.valueOf(r.getString("lifecycle_status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"));}
 private IpamNetwork readNetwork(ResultSet r)throws SQLException{return new IpamNetwork(id(r,"id"),id(r,"organization_id"),nid(r,"subdivision_id"),nid(r,"site_id"),id(r,"vrf_id"),nid(r,"vlan_id"),nid(r,"parent_network_id"),NetworkKind.valueOf(r.getString("network_kind")),new IpCidr(r.getString("cidr_value")),r.getString("usage_text"),r.getString("trust_level"),IpamStatus.valueOf(r.getString("lifecycle_status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"));}
 private IpamPool readPool(ResultSet r)throws SQLException{return new IpamPool(id(r,"id"),id(r,"organization_id"),id(r,"network_id"),r.getString("start_address"),r.getString("end_address"),r.getString("allocation_cursor"),r.getString("name"),IpamStatus.valueOf(r.getString("lifecycle_status")),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"));}
 private IpamAddress readAddress(ResultSet r)throws SQLException{return new IpamAddress(id(r,"id"),id(r,"organization_id"),id(r,"vrf_id"),id(r,"network_id"),nid(r,"pool_id"),r.getString("address_value"),AddressStatus.valueOf(r.getString("lifecycle_status")),r.getString("hostname"),nid(r,"rsot_object_id"),nid(r,"dcim_equipment_id"),r.getString("purpose"),r.getLong("version"),JdbcTemporal.readRequired(r,"created_at"),JdbcTemporal.readRequired(r,"updated_at"));}
 private <T>Optional<T> one(String sql,DomainIdentifier key,Reader<T> reader){return withConn(c->{try(PreparedStatement s=c.prepareStatement(sql)){id(s,1,key);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(reader.read(r)):Optional.empty();}}});}private <T>List<T> list(String sql,IndexedBinder binder,int limit,Reader<T> reader){return withConn(c->{try(PreparedStatement s=c.prepareStatement(sql)){int next=binder.bind(s);s.setInt(next,limit);List<T> out=new ArrayList<>();try(ResultSet r=s.executeQuery()){while(r.next())out.add(reader.read(r));}return out;}});}
 private boolean exists(String sql,Binder b){return withConn(c->{try(PreparedStatement s=c.prepareStatement(sql)){b.bind(s);try(ResultSet r=s.executeQuery()){return r.next();}}});}private void execInsert(String sql,Binder b,String op){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement(sql)){b.bind(s);if(s.executeUpdate()!=1)throw new SQLException("unexpected insert count");}catch(SQLException e){if(dialect.isUniqueViolation(e))throw new IpamConflictException("DDI_CONCURRENT_CONFLICT",op+" conflicted with concurrent mutation");throw fail(op,e);}}private void execUpdate(String sql,Binder b,String op){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement(sql)){b.bind(s);if(s.executeUpdate()!=1)throw new IpamConflictException("VERSION_CONFLICT",op+" version changed");}catch(SQLException e){throw fail(op,e);}}
 private <T>T withConn(Sql<T> work){try{Connection c;try{c=tx.requireCurrentConnection();return work.run(c);}catch(IllegalStateException noTx){try(Connection x=dataSource.getConnection()){return work.run(x);}}}catch(SQLException e){throw fail("query IPAM",e);}}private String lim(){return dialect==JdbcDatabaseDialect.POSTGRESQL?" LIMIT ?":" FETCH NEXT ? ROWS ONLY";}private String vrfTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_ddi.ipam_vrf":"INFRANEXUM_DDI_VRF";}private String vlanTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_ddi.ipam_vlan":"INFRANEXUM_DDI_VLAN";}private String netTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_ddi.ipam_network":"INFRANEXUM_DDI_NETWORK";}private String poolTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_ddi.ipam_pool":"INFRANEXUM_DDI_POOL";}private String addrTable(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_ddi.ipam_address":"INFRANEXUM_DDI_ADDRESS";}
 private DomainIdentifier id(ResultSet r,String c)throws SQLException{return dialect.readIdentifier(r,c);}private DomainIdentifier nid(ResultSet r,String c)throws SQLException{Object v=r.getObject(c);return v==null?null:id(r,c);}private void id(PreparedStatement s,int i,DomainIdentifier v)throws SQLException{dialect.bindIdentifier(s,i,v);}private void nid(PreparedStatement s,int i,DomainIdentifier v)throws SQLException{dialect.bindNullableIdentifier(s,i,v);}private static void str(PreparedStatement s,int i,String v)throws SQLException{if(v==null)s.setNull(i,Types.VARCHAR);else s.setString(i,v);}private static void integer(PreparedStatement s,int i,Integer v)throws SQLException{if(v==null)s.setNull(i,Types.INTEGER);else s.setInt(i,v);}private static void big(PreparedStatement s,int i,Long v)throws SQLException{if(v==null)s.setNull(i,Types.BIGINT);else s.setLong(i,v);}private static void time(PreparedStatement s,int i,java.time.Instant v)throws SQLException{JdbcTemporal.bindInstant(s,i,v);}private static Integer nullableInt(ResultSet r,String c)throws SQLException{int v=r.getInt(c);return r.wasNull()?null:v;}private static Long nullableLong(ResultSet r,String c)throws SQLException{long v=r.getLong(c);return r.wasNull()?null:v;}private static JdbcPersistenceException fail(String op,SQLException e){return new JdbcPersistenceException(op,e);}@FunctionalInterface private interface Binder{void bind(PreparedStatement s)throws SQLException;}@FunctionalInterface private interface IndexedBinder{int bind(PreparedStatement s)throws SQLException;}@FunctionalInterface private interface Reader<T>{T read(ResultSet r)throws SQLException;}@FunctionalInterface private interface Sql<T>{T run(Connection c)throws SQLException;}
}
