package io.infranexum.adapters.persistence.jdbc;

import io.infranexum.ddi.ipam.domain.IpamConflictException;
import io.infranexum.ddi.ipam.ports.IpamIdempotencyRepository;
import java.sql.*;
import java.util.*;

/** Transaction-bound DDI/IPAM command deduplication store. */
public final class JdbcIpamIdempotencyRepository implements IpamIdempotencyRepository {private final JdbcConnectionAccess tx;private final JdbcDatabaseDialect dialect;public JdbcIpamIdempotencyRepository(JdbcConnectionAccess tx,JdbcDatabaseDialect dialect){this.tx=Objects.requireNonNull(tx);this.dialect=Objects.requireNonNull(dialect);}@Override public Optional<Record> find(String key){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("SELECT idempotency_key,payload_sha256,operation_name,result_id,created_at FROM "+table()+" WHERE idempotency_key=?")){s.setString(1,key);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(new Record(r.getString(1),r.getString(2),r.getString(3),dialect.readIdentifier(r,"result_id"),JdbcTemporal.readRequired(r,"created_at"))):Optional.empty();}}catch(SQLException e){throw fail("read IPAM idempotency",e);}}@Override public void insert(Record r){try(PreparedStatement s=tx.requireCurrentConnection().prepareStatement("INSERT INTO "+table()+" (idempotency_key,payload_sha256,operation_name,result_id,created_at) VALUES (?,?,?,?,?)")){s.setString(1,r.key());s.setString(2,r.payloadSha256());s.setString(3,r.operation());dialect.bindIdentifier(s,4,r.resultId());JdbcTemporal.bindInstant(s,5,r.createdAt());s.executeUpdate();}catch(SQLException e){if(dialect.isUniqueViolation(e))throw new IpamConflictException("IDEMPOTENCY_CONFLICT","idempotency key was committed concurrently");throw fail("write IPAM idempotency",e);}}private String table(){return dialect==JdbcDatabaseDialect.POSTGRESQL?"infranexum_ddi.ipam_command_dedup":"INFRANEXUM_DDI_DEDUP";}private static JdbcPersistenceException fail(String o,SQLException e){return new JdbcPersistenceException(o,e);}}
