BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_CORE_INBOX_RECEIPT PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_CORE_OUTBOX_EVENT PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
