BEGIN EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_SCHEMA_REGISTRY (
 ID VARCHAR2(36 CHAR) PRIMARY KEY, SCHEMA_KEY VARCHAR2(160 CHAR) NOT NULL, SCHEMA_KIND VARCHAR2(32 CHAR) NOT NULL,
 OWNER_CODE VARCHAR2(160 CHAR) NOT NULL, SCHEMA_VERSION VARCHAR2(64 CHAR) NOT NULL, STATUS VARCHAR2(16 CHAR) NOT NULL,
 DEFINITION_JSON CLOB NOT NULL, CHECKSUM_SHA256 CHAR(64 CHAR) NOT NULL, REVISION NUMBER(19) DEFAULT 1 NOT NULL,
 EFFECTIVE_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE, DEPRECATED_AT TIMESTAMP(6) WITH TIME ZONE, SUNSET_AT TIMESTAMP(6) WITH TIME ZONE,
 DEPRECATION_REASON VARCHAR2(500 CHAR), COMPATIBILITY_EVIDENCE VARCHAR2(4000 CHAR), BREAKING_APPROVAL_REF VARCHAR2(240 CHAR),
 CONSTRAINT UQ_INX_CORE_SCHEMA_KV UNIQUE(SCHEMA_KEY,SCHEMA_VERSION),
 CONSTRAINT CK_INX_CORE_SCHEMA_UUID CHECK (REGEXP_LIKE(ID,''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')),
 CONSTRAINT CK_INX_CORE_SCHEMA_KEY CHECK (REGEXP_LIKE(SCHEMA_KEY,''^[a-z][a-z0-9.-]{2,159}$'')),
 CONSTRAINT CK_INX_CORE_SCHEMA_OWNER CHECK (REGEXP_LIKE(OWNER_CODE,''^[a-z][a-z0-9._-]{2,159}$'')),
 CONSTRAINT CK_INX_CORE_SCHEMA_KIND CHECK (SCHEMA_KIND IN (''API'',''EVENT'',''COMMAND'',''IMPORT'',''EXPORT'',''RSOT_CANONICAL'',''RSOT_EXTENSION'',''CUSTOM_FIELD'',''PROJECTION'')),
 CONSTRAINT CK_INX_CORE_SCHEMA_STATUS CHECK (STATUS IN (''DRAFT'',''PUBLISHED'',''DEPRECATED'')),
 CONSTRAINT CK_INX_CORE_SCHEMA_JSON CHECK (DEFINITION_JSON IS JSON),
 CONSTRAINT CK_INX_CORE_SCHEMA_HASH CHECK (REGEXP_LIKE(CHECKSUM_SHA256,''^[0-9a-f]{64}$'')),
 CONSTRAINT CK_INX_CORE_SCHEMA_REV CHECK (REVISION>=1), CONSTRAINT CK_INX_CORE_SCHEMA_TIME CHECK (UPDATED_AT>=CREATED_AT),
 CONSTRAINT CK_INX_CORE_SCHEMA_LIFE CHECK ((STATUS=''DRAFT'' AND PUBLISHED_AT IS NULL AND DEPRECATED_AT IS NULL AND SUNSET_AT IS NULL AND DEPRECATION_REASON IS NULL) OR (STATUS=''PUBLISHED'' AND PUBLISHED_AT IS NOT NULL AND DEPRECATED_AT IS NULL AND SUNSET_AT IS NULL AND DEPRECATION_REASON IS NULL) OR (STATUS=''DEPRECATED'' AND PUBLISHED_AT IS NOT NULL AND DEPRECATED_AT IS NOT NULL AND SUNSET_AT>DEPRECATED_AT AND DEPRECATION_REASON IS NOT NULL)))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_CORE_SCHEMA_LOOKUP ON INFRANEXUM_CORE_SCHEMA_REGISTRY(SCHEMA_KEY,STATUS,PUBLISHED_AT)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_CORE_SCHEMA_KIND ON INFRANEXUM_CORE_SCHEMA_REGISTRY(SCHEMA_KIND,STATUS,EFFECTIVE_AT)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/

BEGIN EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_SCHEMA_PROFILE (
 ID VARCHAR2(36 CHAR) PRIMARY KEY, PROFILE_CODE VARCHAR2(160 CHAR) NOT NULL, OWNER_CODE VARCHAR2(160 CHAR) NOT NULL,
 PROFILE_VERSION VARCHAR2(64 CHAR) NOT NULL, STATUS VARCHAR2(16 CHAR) NOT NULL, CHECKSUM_SHA256 CHAR(64 CHAR) NOT NULL,
 REVISION NUMBER(19) DEFAULT 1 NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE, DEPRECATED_AT TIMESTAMP(6) WITH TIME ZONE, SUNSET_AT TIMESTAMP(6) WITH TIME ZONE, DEPRECATION_REASON VARCHAR2(500 CHAR),
 CONSTRAINT UQ_INX_CORE_PROFILE_CV UNIQUE(PROFILE_CODE,PROFILE_VERSION),
 CONSTRAINT CK_INX_CORE_PROFILE_UUID CHECK (REGEXP_LIKE(ID,''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')),
 CONSTRAINT CK_INX_CORE_PROFILE_CODE CHECK (REGEXP_LIKE(PROFILE_CODE,''^[a-z][a-z0-9.-]{2,159}$'')),
 CONSTRAINT CK_INX_CORE_PROFILE_OWNER CHECK (REGEXP_LIKE(OWNER_CODE,''^[a-z][a-z0-9._-]{2,159}$'')),
 CONSTRAINT CK_INX_CORE_PROFILE_STATUS CHECK (STATUS IN (''DRAFT'',''PUBLISHED'',''DEPRECATED'')),
 CONSTRAINT CK_INX_CORE_PROFILE_HASH CHECK (REGEXP_LIKE(CHECKSUM_SHA256,''^[0-9a-f]{64}$'')), CONSTRAINT CK_INX_CORE_PROFILE_REV CHECK (REVISION>=1),
 CONSTRAINT CK_INX_CORE_PROFILE_TIME CHECK (UPDATED_AT>=CREATED_AT),
 CONSTRAINT CK_INX_CORE_PROFILE_LIFE CHECK ((STATUS=''DRAFT'' AND PUBLISHED_AT IS NULL AND DEPRECATED_AT IS NULL AND SUNSET_AT IS NULL AND DEPRECATION_REASON IS NULL) OR (STATUS=''PUBLISHED'' AND PUBLISHED_AT IS NOT NULL AND DEPRECATED_AT IS NULL AND SUNSET_AT IS NULL AND DEPRECATION_REASON IS NULL) OR (STATUS=''DEPRECATED'' AND PUBLISHED_AT IS NOT NULL AND DEPRECATED_AT IS NOT NULL AND SUNSET_AT>DEPRECATED_AT AND DEPRECATION_REASON IS NOT NULL)))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_CORE_PROFILE_LOOKUP ON INFRANEXUM_CORE_SCHEMA_PROFILE(PROFILE_CODE,STATUS,PUBLISHED_AT)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/

BEGIN EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_SCHEMA_PROFILE_MEMBER (
 PROFILE_ID VARCHAR2(36 CHAR) NOT NULL, POSITION_NO NUMBER(3) NOT NULL, SCHEMA_ID VARCHAR2(36 CHAR) NOT NULL, REQUIRED_MEMBER NUMBER(1) DEFAULT 1 NOT NULL,
 CONSTRAINT PK_INX_CORE_PROFILE_MEMBER PRIMARY KEY(PROFILE_ID,POSITION_NO), CONSTRAINT UQ_INX_CORE_PROFILE_SCHEMA UNIQUE(PROFILE_ID,SCHEMA_ID),
 CONSTRAINT FK_INX_CORE_PROFILE_MEMBER FOREIGN KEY(PROFILE_ID) REFERENCES INFRANEXUM_CORE_SCHEMA_PROFILE(ID) ON DELETE CASCADE,
 CONSTRAINT FK_INX_CORE_PROFILE_SCHEMA FOREIGN KEY(SCHEMA_ID) REFERENCES INFRANEXUM_CORE_SCHEMA_REGISTRY(ID),
 CONSTRAINT CK_INX_CORE_PROFILE_POS CHECK (POSITION_NO BETWEEN 1 AND 128), CONSTRAINT CK_INX_CORE_PROFILE_REQ CHECK (REQUIRED_MEMBER IN (0,1)))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_CORE_PROFILE_MEMBER_SCHEMA ON INFRANEXUM_CORE_SCHEMA_PROFILE_MEMBER(SCHEMA_ID,PROFILE_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
