package io.infranexum.adapters.persistence.jdbc;

import io.infranexum.core.contracts.DomainIdentifier;
import io.infranexum.core.entitlements.*;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import javax.sql.DataSource;

/** JDBC implementation that atomically accepts manifest, entitlement state and database proof. */
public final class JdbcActivationOperationalRepository implements ActivationOperationalRepository {
    private final DataSource dataSource; private final JdbcDatabaseDialect dialect;
    public JdbcActivationOperationalRepository(DataSource dataSource, JdbcDatabaseDialect dialect){this.dataSource=Objects.requireNonNull(dataSource,"dataSource");this.dialect=Objects.requireNonNull(dialect,"dialect");}
    @Override public Optional<InstallationIdentity> installationIdentity(){
        String sql=dialect==JdbcDatabaseDialect.POSTGRESQL?"SELECT installation_id,fingerprint_version,fingerprint,created_at FROM core_installation_identity":"SELECT INSTALLATION_ID,FINGERPRINT_VERSION,FINGERPRINT,CREATED_AT FROM CORE_INSTALLATION_IDENTITY";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){if(!r.next())return Optional.empty();InstallationIdentity v=new InstallationIdentity(dialect.readIdentifier(r,"installation_id"),r.getString("fingerprint_version"),r.getString("fingerprint"),JdbcTemporal.readRequired(r,"created_at"));if(r.next())throw new SQLException("multiple installation identities");return Optional.of(v);}catch(SQLException e){throw new JdbcPersistenceException("load installation identity",e);}
    }
    @Override public AcceptedSequence acceptedSequence(InstallationIdentity identity){
        String t=dialect==JdbcDatabaseDialect.POSTGRESQL?"core_entitlement_state":"CORE_ENTITLEMENT_STATE";String sql="SELECT max_activation_sequence,accepted_activation_id FROM "+t+" WHERE installation_id=?";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,identity.installationId());try(ResultSet r=s.executeQuery()){if(!r.next())return AcceptedSequence.none();long value=r.getLong(1);Object raw=r.getObject(2);DomainIdentifier id=raw==null?null:(raw instanceof java.util.UUID u?new DomainIdentifier(u):DomainIdentifier.parse(raw.toString()));return new AcceptedSequence(value,id);}}catch(SQLException e){throw new JdbcPersistenceException("load accepted activation sequence",e);}
    }
    @Override public Optional<IntegrityProof> databaseProof(InstallationIdentity identity){
        String t=dialect==JdbcDatabaseDialect.POSTGRESQL?"core_entitlement_integrity_proof":"CORE_ENTITLEMENT_INTEGRITY_PROOF";String sql="SELECT installation_id,fingerprint,evaluation_started_at,last_reliable_at,generation,mac_base64 FROM "+t+" WHERE installation_id=?";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,identity.installationId());try(ResultSet r=s.executeQuery()){if(!r.next())return Optional.empty();return Optional.of(new IntegrityProof(dialect.readIdentifier(r,"installation_id"),r.getString("fingerprint"),JdbcTemporal.readRequired(r,"evaluation_started_at"),JdbcTemporal.readRequired(r,"last_reliable_at"),r.getLong("generation"),r.getString("mac_base64")));}}catch(SQLException e){throw new JdbcPersistenceException("load database integrity proof",e);}
    }
    @Override public void accept(InstallationIdentity identity, ActivationManifest manifest, ActivationVerificationResult result, IntegrityProof proof, Instant acceptedAt){
        try(Connection c=dataSource.getConnection()){boolean ac=c.getAutoCommit();c.setAutoCommit(false);try{insertManifest(c,identity,manifest,acceptedAt);upsertProof(c,proof,acceptedAt);upsertState(c,identity,result,proof,acceptedAt);c.commit();}catch(SQLException|RuntimeException e){c.rollback();throw e;}finally{c.setAutoCommit(ac);}}catch(SQLException e){throw new JdbcPersistenceException("accept activation manifest",e);}
    }
    private void insertManifest(Connection c,InstallationIdentity identity,ActivationManifest manifest,Instant acceptedAt)throws SQLException{ActivationManifestPayload p=manifest.payload();String table=dialect==JdbcDatabaseDialect.POSTGRESQL?"core_activation_manifest":"CORE_ACTIVATION_MANIFEST";String sql="INSERT INTO "+table+" (activation_id,installation_id,customer_id,customer_legal_name,profile,allocation_tier,catalog_version,host_limit,capabilities_json,quotas_json,valid_from,valid_until,grace_period_days,issued_at,issuer,sequence,key_id,signature_base64,manifest_sha256,accepted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";try(PreparedStatement s=c.prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,p.activationId());dialect.bindIdentifier(s,i++,identity.installationId());s.setString(i++,p.customer().customerId());s.setString(i++,p.customer().legalName());s.setString(i++,p.profile().name());s.setString(i++,p.allocationTier().name());s.setString(i++,p.catalogVersion());s.setLong(i++,p.hostLimit());s.setString(i++,CanonicalJson.string(p.capabilities().stream().sorted().toList()));s.setString(i++,CanonicalJson.string(new TreeMap<>(p.quotas())));JdbcTemporal.bindInstant(s,i++,p.validFrom());JdbcTemporal.bindInstant(s,i++,p.validUntil());s.setInt(i++,p.gracePeriodDays());JdbcTemporal.bindInstant(s,i++,p.issuedAt());s.setString(i++,p.issuer());s.setLong(i++,p.sequence());s.setString(i++,p.keyId());s.setString(i++,manifest.signature());s.setString(i++,sha256(manifest.payload().canonicalBytes()));JdbcTemporal.bindInstant(s,i,acceptedAt);s.executeUpdate();}}
    private void upsertProof(Connection c,IntegrityProof p,Instant now)throws SQLException{String sql=dialect==JdbcDatabaseDialect.POSTGRESQL?"INSERT INTO core_entitlement_integrity_proof (installation_id,fingerprint,evaluation_started_at,last_reliable_at,generation,mac_base64,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT (installation_id) DO UPDATE SET fingerprint=EXCLUDED.fingerprint,evaluation_started_at=EXCLUDED.evaluation_started_at,last_reliable_at=EXCLUDED.last_reliable_at,generation=EXCLUDED.generation,mac_base64=EXCLUDED.mac_base64,updated_at=EXCLUDED.updated_at":"MERGE INTO CORE_ENTITLEMENT_INTEGRITY_PROOF t USING (SELECT ? INSTALLATION_ID,? FINGERPRINT,? EVALUATION_STARTED_AT,? LAST_RELIABLE_AT,? GENERATION,? MAC_BASE64,? UPDATED_AT FROM dual) s ON (t.INSTALLATION_ID=s.INSTALLATION_ID) WHEN MATCHED THEN UPDATE SET t.FINGERPRINT=s.FINGERPRINT,t.EVALUATION_STARTED_AT=s.EVALUATION_STARTED_AT,t.LAST_RELIABLE_AT=s.LAST_RELIABLE_AT,t.GENERATION=s.GENERATION,t.MAC_BASE64=s.MAC_BASE64,t.UPDATED_AT=s.UPDATED_AT WHEN NOT MATCHED THEN INSERT (INSTALLATION_ID,FINGERPRINT,EVALUATION_STARTED_AT,LAST_RELIABLE_AT,GENERATION,MAC_BASE64,UPDATED_AT) VALUES (s.INSTALLATION_ID,s.FINGERPRINT,s.EVALUATION_STARTED_AT,s.LAST_RELIABLE_AT,s.GENERATION,s.MAC_BASE64,s.UPDATED_AT)";try(PreparedStatement s=c.prepareStatement(sql)){dialect.bindIdentifier(s,1,p.installationId());s.setString(2,p.fingerprint());JdbcTemporal.bindInstant(s,3,p.evaluationStartedAt());JdbcTemporal.bindInstant(s,4,p.lastReliableAt());s.setLong(5,p.generation());s.setString(6,p.mac());JdbcTemporal.bindInstant(s,7,now);s.executeUpdate();}}
    private void upsertState(Connection c,InstallationIdentity identity,ActivationVerificationResult r,IntegrityProof p,Instant now)throws SQLException{ActivationManifestPayload m=r.payload();String sql=dialect==JdbcDatabaseDialect.POSTGRESQL?"INSERT INTO core_entitlement_state (installation_id,profile,allocation_tier,evaluation_started_at,last_reliable_at,time_generation,max_activation_sequence,accepted_activation_id,activation_state,valid_until,grace_until,updated_at) VALUES (?,?,?,NULL,?,?,?,?,?,?,?,?) ON CONFLICT (installation_id) DO UPDATE SET profile=EXCLUDED.profile,allocation_tier=EXCLUDED.allocation_tier,last_reliable_at=EXCLUDED.last_reliable_at,time_generation=EXCLUDED.time_generation,max_activation_sequence=EXCLUDED.max_activation_sequence,accepted_activation_id=EXCLUDED.accepted_activation_id,activation_state=EXCLUDED.activation_state,valid_until=EXCLUDED.valid_until,grace_until=EXCLUDED.grace_until,updated_at=EXCLUDED.updated_at":"MERGE INTO CORE_ENTITLEMENT_STATE t USING (SELECT ? INSTALLATION_ID,? PROFILE,? ALLOCATION_TIER,? LAST_RELIABLE_AT,? TIME_GENERATION,? MAX_ACTIVATION_SEQUENCE,? ACCEPTED_ACTIVATION_ID,? ACTIVATION_STATE,? VALID_UNTIL,? GRACE_UNTIL,? UPDATED_AT FROM dual) s ON (t.INSTALLATION_ID=s.INSTALLATION_ID) WHEN MATCHED THEN UPDATE SET t.PROFILE=s.PROFILE,t.ALLOCATION_TIER=s.ALLOCATION_TIER,t.LAST_RELIABLE_AT=s.LAST_RELIABLE_AT,t.TIME_GENERATION=s.TIME_GENERATION,t.MAX_ACTIVATION_SEQUENCE=s.MAX_ACTIVATION_SEQUENCE,t.ACCEPTED_ACTIVATION_ID=s.ACCEPTED_ACTIVATION_ID,t.ACTIVATION_STATE=s.ACTIVATION_STATE,t.VALID_UNTIL=s.VALID_UNTIL,t.GRACE_UNTIL=s.GRACE_UNTIL,t.UPDATED_AT=s.UPDATED_AT WHEN NOT MATCHED THEN INSERT (INSTALLATION_ID,PROFILE,ALLOCATION_TIER,EVALUATION_STARTED_AT,LAST_RELIABLE_AT,TIME_GENERATION,MAX_ACTIVATION_SEQUENCE,ACCEPTED_ACTIVATION_ID,ACTIVATION_STATE,VALID_UNTIL,GRACE_UNTIL,UPDATED_AT) VALUES (s.INSTALLATION_ID,s.PROFILE,s.ALLOCATION_TIER,NULL,s.LAST_RELIABLE_AT,s.TIME_GENERATION,s.MAX_ACTIVATION_SEQUENCE,s.ACCEPTED_ACTIVATION_ID,s.ACTIVATION_STATE,s.VALID_UNTIL,s.GRACE_UNTIL,s.UPDATED_AT)";try(PreparedStatement s=c.prepareStatement(sql)){int i=1;dialect.bindIdentifier(s,i++,identity.installationId());s.setString(i++,m.profile().name());s.setString(i++,m.allocationTier().name());JdbcTemporal.bindInstant(s,i++,p.lastReliableAt());s.setLong(i++,p.generation());s.setLong(i++,m.sequence());dialect.bindIdentifier(s,i++,m.activationId());s.setString(i++,r.state().name());JdbcTemporal.bindInstant(s,i++,m.validUntil());JdbcTemporal.bindInstant(s,i++,r.graceUntil());JdbcTemporal.bindInstant(s,i,now);s.executeUpdate();}}
    private static String sha256(byte[] value){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value));}catch(NoSuchAlgorithmException e){throw new IllegalStateException("SHA-256 is required",e);}}
}
