BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_RSOT_CONTEXT_RELATIONSHIP CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_RSOT_AUTHORITY_MATRIX CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_RSOT_ATTRIBUTE_AUTHORITY_POLICY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_RSOT_CANONICAL_OBJECT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
