package io.infranexum.ddi.ipam.domain;

import io.infranexum.core.contracts.DomainIdentifier;
import java.math.BigInteger;
import java.time.Instant;
import java.util.Objects;

/** Governed address block/prefix/subnet. */
public record IpamNetwork(DomainIdentifier id,DomainIdentifier organizationId,DomainIdentifier subdivisionId,DomainIdentifier siteId,DomainIdentifier vrfId,DomainIdentifier vlanId,DomainIdentifier parentNetworkId,NetworkKind kind,IpCidr cidr,String usage,String trustLevel,IpamStatus status,long version,Instant createdAt,Instant updatedAt){public IpamNetwork{Objects.requireNonNull(id);Objects.requireNonNull(organizationId);Objects.requireNonNull(vrfId);Objects.requireNonNull(kind);Objects.requireNonNull(cidr);usage=optional(usage,160);trustLevel=optional(trustLevel,64);Objects.requireNonNull(status);if(version<1)throw new IllegalArgumentException("version must be positive");}public static IpamNetwork draft(DomainIdentifier id,DomainIdentifier org,DomainIdentifier sub,DomainIdentifier site,DomainIdentifier vrf,DomainIdentifier vlan,DomainIdentifier parent,NetworkKind kind,IpCidr cidr,String usage,String trust,Instant now){return new IpamNetwork(id,org,sub,site,vrf,vlan,parent,kind,cidr,usage,trust,IpamStatus.DRAFT,1,now,now);}public BigInteger addressCount(){return cidr.size();}public IpamNetwork metadata(DomainIdentifier vlan,String usageValue,String trust,Instant now){if(status==IpamStatus.RETIRED)throw new IpamConflictException("DDI_NETWORK_TERMINAL","retired network is terminal");return new IpamNetwork(id,organizationId,subdivisionId,siteId,vrfId,vlan,parentNetworkId,kind,cidr,usageValue,trust,status,version+1,createdAt,now);}public IpamNetwork status(IpamStatus target,Instant now){if(status==IpamStatus.RETIRED)throw new IpamConflictException("DDI_NETWORK_TERMINAL","retired network is terminal");return new IpamNetwork(id,organizationId,subdivisionId,siteId,vrfId,vlanId,parentNetworkId,kind,cidr,usage,trustLevel,target,version+1,createdAt,now);}private static String optional(String v,int max){if(v==null)return null;String x=v.strip();if(x.isEmpty())return null;if(x.length()>max)throw new IllegalArgumentException("value too long");return x;}}
