package io.infranexum.ddi.ipam.domain;

import java.math.BigInteger;
import java.net.*;
import java.util.*;

/** Canonical IPv4/IPv6 CIDR value object with containment/overlap arithmetic. */
public final class IpCidr {
 private final String canonical; private final int bits; private final int prefix; private final BigInteger first; private final BigInteger last;
 public IpCidr(String value){Objects.requireNonNull(value,"value");String[] p=value.strip().split("/",-1);if(p.length!=2)throw new IllegalArgumentException("CIDR must contain address/prefix");try{InetAddress a=InetAddress.getByName(p[0]);byte[] raw=a.getAddress();bits=raw.length*8;prefix=Integer.parseInt(p[1]);if(prefix<0||prefix>bits)throw new IllegalArgumentException("CIDR prefix out of range");BigInteger n=new BigInteger(1,raw);int host=bits-prefix;first=n.shiftRight(host).shiftLeft(host);last=first.add(BigInteger.ONE.shiftLeft(host).subtract(BigInteger.ONE));canonical=toAddress(first,bits)+"/"+prefix;}catch(UnknownHostException|NumberFormatException e){throw new IllegalArgumentException("invalid CIDR",e);}}
 public String value(){return canonical;} public int prefixLength(){return prefix;} public int addressBits(){return bits;} public BigInteger first(){return first;} public BigInteger last(){return last;} public BigInteger size(){return last.subtract(first).add(BigInteger.ONE);} public boolean overlaps(IpCidr other){return bits==other.bits&&first.compareTo(other.last)<=0&&other.first.compareTo(last)<=0;} public boolean contains(IpCidr other){return bits==other.bits&&first.compareTo(other.first)<=0&&last.compareTo(other.last)>=0;} public boolean containsAddress(String ip){BigInteger n=parseAddress(ip,bits);return n.compareTo(first)>=0&&n.compareTo(last)<=0;} public String firstAddress(){return toAddress(first,bits);} public String lastAddress(){return toAddress(last,bits);} public String firstSortKey(){return sortKey(first);} public String lastSortKey(){return sortKey(last);} @Override public String toString(){return canonical;} @Override public boolean equals(Object o){return o instanceof IpCidr c&&canonical.equals(c.canonical);} @Override public int hashCode(){return canonical.hashCode();}
 public static String canonicalAddress(String ip){Objects.requireNonNull(ip,"ip");try{return InetAddress.getByName(ip.strip()).getHostAddress();}catch(UnknownHostException e){throw new IllegalArgumentException("invalid IP address",e);}} public static String sortKey(String ip){Objects.requireNonNull(ip,"ip");try{return sortKey(new BigInteger(1,InetAddress.getByName(ip.strip()).getAddress()));}catch(UnknownHostException e){throw new IllegalArgumentException("invalid IP address",e);}} private static String sortKey(BigInteger value){return String.format(Locale.ROOT,"%032x",value);}
 private static BigInteger parseAddress(String ip,int bits){try{byte[] raw=InetAddress.getByName(ip.strip()).getAddress();if(raw.length*8!=bits)throw new IllegalArgumentException("address family mismatch");return new BigInteger(1,raw);}catch(UnknownHostException e){throw new IllegalArgumentException("invalid IP address",e);}}
 private static String toAddress(BigInteger value,int bits){byte[] src=value.toByteArray(),dst=new byte[bits/8];int copy=Math.min(src.length,dst.length);System.arraycopy(src,src.length-copy,dst,dst.length-copy,copy);try{return InetAddress.getByAddress(dst).getHostAddress();}catch(UnknownHostException e){throw new IllegalStateException(e);}}
}
