DELETE FROM INFRANEXUM_IAM_ROLE_PERMISSION WHERE PERMISSION_ID IN (SELECT ID FROM INFRANEXUM_IAM_PERMISSION WHERE ORGANIZATION_ID IS NULL AND CODE LIKE 'dcim.%');
DELETE FROM INFRANEXUM_IAM_PERMISSION WHERE ORGANIZATION_ID IS NULL AND CODE LIKE 'dcim.%';
