package io.infranexum.integrations;

import io.infranexum.core.events.RetryPolicy;
import java.time.Clock;
import java.time.Duration;
import java.util.Objects;

/** Claims and processes one finite connector inbox batch with bounded retries and automatic suspension. */
public final class ConnectorInboxDispatcher {
    private final ConnectorInboxRepository inbox; private final ConnectorEndpointRegistry endpoints; private final ConnectorHandlerRegistry handlers; private final ConnectorRuntimeObserver observer; private final RetryPolicy retries; private final Clock clock; private final String workerId; private final int batchSize; private final Duration leaseDuration; private final int suspendAfterDeadLetters; private final Duration suspensionDuration;
    public ConnectorInboxDispatcher(ConnectorInboxRepository inbox,ConnectorEndpointRegistry endpoints,ConnectorHandlerRegistry handlers,ConnectorRuntimeObserver observer,RetryPolicy retries,Clock clock,String workerId,int batchSize,Duration leaseDuration,int suspendAfterDeadLetters,Duration suspensionDuration){this.inbox=Objects.requireNonNull(inbox,"inbox");this.endpoints=Objects.requireNonNull(endpoints,"endpoints");this.handlers=Objects.requireNonNull(handlers,"handlers");this.observer=Objects.requireNonNull(observer,"observer");this.retries=Objects.requireNonNull(retries,"retries");this.clock=Objects.requireNonNull(clock,"clock");this.workerId=Objects.requireNonNull(workerId,"workerId").strip();if(this.workerId.isEmpty())throw new IllegalArgumentException("workerId must not be blank");if(batchSize<1||batchSize>1000)throw new IllegalArgumentException("batchSize must be between 1 and 1000");this.batchSize=batchSize;this.leaseDuration=positive(leaseDuration,"leaseDuration");if(suspendAfterDeadLetters<1||suspendAfterDeadLetters>100)throw new IllegalArgumentException("suspendAfterDeadLetters must be between 1 and 100");this.suspendAfterDeadLetters=suspendAfterDeadLetters;this.suspensionDuration=positive(suspensionDuration,"suspensionDuration");}
    public ConnectorDispatchReport dispatchOnce(){var batch=inbox.claimBatch(workerId,batchSize,clock.instant(),leaseDuration);int processed=0,retried=0,dead=0;for(var delivery:batch){try{var endpoint=endpoints.find(delivery.connectorKey()).filter(ConnectorWebhookEndpoint::enabled).orElseThrow(() -> new IllegalStateException("connector endpoint is disabled or missing"));handlers.require(endpoint.handlerName()).handle(delivery);var now=clock.instant();inbox.markProcessed(delivery.deliveryId(),workerId,now);observer.processed(delivery.connectorKey(),Duration.between(delivery.receivedAt(),now));processed++;}catch(Exception failure){var status=inbox.markFailed(delivery.deliveryId(),workerId,clock.instant(),retries,failure,suspendAfterDeadLetters,suspensionDuration);if(status==ConnectorDeliveryStatus.DEAD_LETTER){dead++;observer.deadLettered(delivery.connectorKey());if(inbox.runtimeState(delivery.connectorKey()).suspendedAt(clock.instant()))observer.suspended(delivery.connectorKey());}else{retried++;observer.retried(delivery.connectorKey());}}}return new ConnectorDispatchReport(batch.size(),processed,retried,dead);}
    private static Duration positive(Duration value,String field){Objects.requireNonNull(value,field);if(value.isNegative()||value.isZero())throw new IllegalArgumentException(field+" must be positive");return value;}
}
