BEGIN EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_ITAM_ASSET (
 ID VARCHAR2(36 CHAR) PRIMARY KEY, RSOT_OBJECT_ID VARCHAR2(36 CHAR) NOT NULL, ASSET_TYPE VARCHAR2(16 CHAR) NOT NULL,
 OWNING_ORGANIZATION_ID VARCHAR2(36 CHAR) NOT NULL, OWNING_SUBDIVISION_ID VARCHAR2(36 CHAR), ACQUISITION_DATE DATE NOT NULL,
 ACQUISITION_VALUE NUMBER(19,4) NOT NULL, CURRENCY_CODE CHAR(3 CHAR) NOT NULL, ACQUIRED_FROM_PARTNER_ID VARCHAR2(36 CHAR),
 LIFECYCLE_STATUS VARCHAR2(24 CHAR) NOT NULL, CURRENT_CUSTODIAN_KIND VARCHAR2(20 CHAR) NOT NULL, CURRENT_CUSTODIAN_ID VARCHAR2(36 CHAR),
 VERSION NUMBER(19) DEFAULT 1 NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, UPDATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 CREATED_BY VARCHAR2(36 CHAR) NOT NULL, UPDATED_BY VARCHAR2(36 CHAR) NOT NULL, LAST_REASON VARCHAR2(1024 CHAR) NOT NULL,
 CONSTRAINT UQ_INX_ITAM_ASSET_RSOT UNIQUE(RSOT_OBJECT_ID),
 CONSTRAINT CK_INX_ITAM_ASSET_UUID CHECK (REGEXP_LIKE(ID,''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')),
 CONSTRAINT CK_INX_ITAM_ASSET_RSOT CHECK (REGEXP_LIKE(RSOT_OBJECT_ID,''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')),
 CONSTRAINT CK_INX_ITAM_ASSET_TYPE CHECK (ASSET_TYPE IN (''HARDWARE'',''SOFTWARE'')),
 CONSTRAINT CK_INX_ITAM_ASSET_STATUS CHECK (LIFECYCLE_STATUS IN (''ACQUIRED'',''RECEIVED'',''IN_STOCK'',''ASSIGNED'',''DEPLOYED'',''MAINTENANCE'',''RETURNED'',''RETIRED'',''DISPOSED'')),
 CONSTRAINT CK_INX_ITAM_ASSET_CKIND CHECK (CURRENT_CUSTODIAN_KIND IN (''NONE'',''ORGANIZATION'',''SUBDIVISION'',''ACTOR'',''PARTNER'')),
 CONSTRAINT CK_INX_ITAM_ASSET_CREF CHECK ((CURRENT_CUSTODIAN_KIND=''NONE'' AND CURRENT_CUSTODIAN_ID IS NULL) OR (CURRENT_CUSTODIAN_KIND<>''NONE'' AND CURRENT_CUSTODIAN_ID IS NOT NULL)),
 CONSTRAINT CK_INX_ITAM_ASSET_VALUE CHECK (ACQUISITION_VALUE>=0), CONSTRAINT CK_INX_ITAM_ASSET_CUR CHECK (REGEXP_LIKE(CURRENCY_CODE,''^[A-Z]{3}$'')),
 CONSTRAINT CK_INX_ITAM_ASSET_VER CHECK (VERSION>=1), CONSTRAINT CK_INX_ITAM_ASSET_TIME CHECK (UPDATED_AT>=CREATED_AT))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_ITAM_ASSET_PORT ON INFRANEXUM_ITAM_ASSET(OWNING_ORGANIZATION_ID,LIFECYCLE_STATUS,ASSET_TYPE,ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_ITAM_ASSET_PARTNER ON INFRANEXUM_ITAM_ASSET(ACQUIRED_FROM_PARTNER_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/

BEGIN EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_ITAM_ASSET_CUSTODY (
 EVENT_ID VARCHAR2(36 CHAR) NOT NULL, ASSET_ID VARCHAR2(36 CHAR) NOT NULL, SEQUENCE_NO NUMBER(19) NOT NULL, EVENT_TYPE VARCHAR2(40 CHAR) NOT NULL,
 FROM_STATUS VARCHAR2(24 CHAR), TO_STATUS VARCHAR2(24 CHAR) NOT NULL, CUSTODIAN_KIND VARCHAR2(20 CHAR) NOT NULL, CUSTODIAN_ID VARCHAR2(36 CHAR),
 OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, ACTOR_ID VARCHAR2(36 CHAR) NOT NULL, CORRELATION_ID VARCHAR2(36 CHAR) NOT NULL,
 REASON VARCHAR2(1024 CHAR) NOT NULL, EVIDENCE_REFERENCE VARCHAR2(240 CHAR),
 CONSTRAINT PK_INX_ITAM_ASSET_CUST PRIMARY KEY(ASSET_ID,SEQUENCE_NO), CONSTRAINT UQ_INX_ITAM_ASSET_EVT UNIQUE(EVENT_ID),
 CONSTRAINT FK_INX_ITAM_ASSET_CUST FOREIGN KEY(ASSET_ID) REFERENCES INFRANEXUM_ITAM_ASSET(ID),
 CONSTRAINT CK_INX_ITAM_ASSET_SEQ CHECK (SEQUENCE_NO>=1),
 CONSTRAINT CK_INX_ITAM_ASSET_ETYPE CHECK (EVENT_TYPE IN (''ACQUIRED'',''RECEIVED'',''STOCKED'',''ASSIGNED'',''DEPLOYED'',''TRANSFERRED'',''MAINTENANCE_STARTED'',''RETURNED'',''RETIRED'',''DISPOSED'')),
 CONSTRAINT CK_INX_ITAM_ASSET_EKIND CHECK (CUSTODIAN_KIND IN (''NONE'',''ORGANIZATION'',''SUBDIVISION'',''ACTOR'',''PARTNER'')),
 CONSTRAINT CK_INX_ITAM_ASSET_EREF CHECK ((CUSTODIAN_KIND=''NONE'' AND CUSTODIAN_ID IS NULL) OR (CUSTODIAN_KIND<>''NONE'' AND CUSTODIAN_ID IS NOT NULL)),
 CONSTRAINT CK_INX_ITAM_ASSET_EVID CHECK (EVENT_TYPE<>''DISPOSED'' OR EVIDENCE_REFERENCE IS NOT NULL))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_ITAM_ASSET_CTIME ON INFRANEXUM_ITAM_ASSET_CUSTODY(ASSET_ID,OCCURRED_AT,SEQUENCE_NO)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_ITAM_ASSET_COWN ON INFRANEXUM_ITAM_ASSET_CUSTODY(CUSTODIAN_KIND,CUSTODIAN_ID,OCCURRED_AT)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/

BEGIN EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_ITAM_ASSET_DEDUP (IDEMPOTENCY_KEY VARCHAR2(200 CHAR) PRIMARY KEY, PAYLOAD_SHA256 CHAR(64 CHAR) NOT NULL, OPERATION_NAME VARCHAR2(40 CHAR) NOT NULL, ASSET_ID VARCHAR2(36 CHAR) NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, CONSTRAINT CK_INX_ITAM_ASSET_HASH CHECK (REGEXP_LIKE(PAYLOAD_SHA256,''^[0-9a-f]{64}$'')))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_ITAM_ASSET_DEDUP ON INFRANEXUM_ITAM_ASSET_DEDUP(CREATED_AT)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;/
