-- Rollback is safe only before an inbox handler has an active PROCESSING reservation.
DECLARE
    processing_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO processing_count
    FROM INFRANEXUM_CORE_INBOX_RECEIPT
    WHERE STATUS = 'PROCESSING';
    IF processing_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'cannot roll back migration 0003 while inbox reservations are processing');
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IX_INX_INBOX_PROCESSING';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT DROP CONSTRAINT CK_INX_INBOX_COMPLETED';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT DROP CONSTRAINT CK_INX_INBOX_STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT
    MODIFY (COMPLETED_AT NOT NULL);

ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT
    ADD CONSTRAINT CK_INX_INBOX_COMPLETED CHECK (COMPLETED_AT >= RECEIVED_AT);

ALTER TABLE INFRANEXUM_CORE_INBOX_RECEIPT DROP COLUMN STATUS;
