DECLARE
  manifest_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO manifest_count FROM core_activation_manifest;
  IF manifest_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20004, 'rollback 0004 refused: accepted activation manifests exist');
  END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE core_activation_revocation'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE core_activation_manifest'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE core_entitlement_integrity_proof'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE core_entitlement_state'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE core_installation_identity'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
