BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_PHYS_DEDUP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_CABLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_PORT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_EQUIP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_RACK'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_MODEL_PORT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_DCIM_MODEL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
