-- InfraNexum migration 0006: durable Core Workers task store for Oracle.
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_WORKER_TASK (
    TASK_ID VARCHAR2(36 CHAR) PRIMARY KEY,
    TASK_TYPE VARCHAR2(160 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(256 CHAR) NOT NULL,
    RETRY_SAFETY VARCHAR2(32 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
    REQUESTED_NOT_BEFORE TIMESTAMP WITH TIME ZONE NOT NULL,
    AVAILABLE_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    LEASE_OWNER VARCHAR2(160 CHAR),
    LEASE_VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    LEASE_UNTIL TIMESTAMP WITH TIME ZONE,
    CHECKPOINT_SEQUENCE NUMBER(19),
    CHECKPOINT_TOKEN CLOB,
    CHECKPOINT_AT TIMESTAMP WITH TIME ZONE,
    CANCELLATION_REQUESTED CHAR(1 CHAR) DEFAULT ''N'' NOT NULL,
    LAST_FAILURE VARCHAR2(1024 CHAR),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UQ_INX_WORKER_TASK_IDEM UNIQUE (TASK_TYPE, IDEMPOTENCY_KEY),
    CONSTRAINT CK_INX_WORKER_TASK_ID_V7 CHECK (
      REGEXP_LIKE(TASK_ID, ''^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'')
    ),
    CONSTRAINT CK_INX_WORKER_TASK_TYPE CHECK (
      REGEXP_LIKE(TASK_TYPE, ''^[a-z][a-z0-9]*([.-][a-z0-9]+)*$'')
    ),
    CONSTRAINT CK_INX_WORKER_RETRY CHECK (RETRY_SAFETY IN (''RETRY_SAFE'', ''AT_MOST_ONCE'')),
    CONSTRAINT CK_INX_WORKER_STATUS CHECK (STATUS IN (''PENDING'', ''RUNNING'', ''SUCCEEDED'', ''FAILED'', ''CANCELLED'')),
    CONSTRAINT CK_INX_WORKER_ATTEMPTS CHECK (ATTEMPTS >= 0),
    CONSTRAINT CK_INX_WORKER_LEASE_VER CHECK (LEASE_VERSION >= 0),
    CONSTRAINT CK_INX_WORKER_LEASE_STATE CHECK (
      (STATUS = ''RUNNING'' AND LEASE_OWNER IS NOT NULL AND LEASE_UNTIL IS NOT NULL AND LEASE_VERSION >= 1)
      OR
      (STATUS <> ''RUNNING'' AND LEASE_OWNER IS NULL AND LEASE_UNTIL IS NULL)
    ),
    CONSTRAINT CK_INX_WORKER_CHECKPOINT CHECK (
      (CHECKPOINT_SEQUENCE IS NULL AND CHECKPOINT_AT IS NULL)
      OR
      (CHECKPOINT_SEQUENCE >= 1 AND CHECKPOINT_AT IS NOT NULL)
    ),
    CONSTRAINT CK_INX_WORKER_CANCEL CHECK (CANCELLATION_REQUESTED IN (''Y'', ''N''))
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE INFRANEXUM_CORE_WORKER_TASK_PARAMETER (
    TASK_ID VARCHAR2(36 CHAR) NOT NULL,
    PARAMETER_KEY VARCHAR2(64 CHAR) NOT NULL,
    PARAMETER_VALUE CLOB NOT NULL,
    PRIMARY KEY (TASK_ID, PARAMETER_KEY),
    CONSTRAINT FK_INX_WORKER_PARAM_TASK FOREIGN KEY (TASK_ID)
      REFERENCES INFRANEXUM_CORE_WORKER_TASK(TASK_ID) ON DELETE CASCADE,
    CONSTRAINT CK_INX_WORKER_PARAM_KEY CHECK (
      REGEXP_LIKE(PARAMETER_KEY, ''^[A-Za-z][A-Za-z0-9_.-]{0,63}$'')
    )
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_WORKER_TASK_DUE
    ON INFRANEXUM_CORE_WORKER_TASK (STATUS, AVAILABLE_AT, CREATED_AT, TASK_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_INX_WORKER_TASK_LEASE
    ON INFRANEXUM_CORE_WORKER_TASK (STATUS, LEASE_UNTIL, CREATED_AT, TASK_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE TRIGGER INX_CORE_WORKER_CHECKPOINT_TRG
BEFORE INSERT OR UPDATE OF CHECKPOINT_SEQUENCE, CHECKPOINT_TOKEN, CHECKPOINT_AT
ON INFRANEXUM_CORE_WORKER_TASK
FOR EACH ROW
BEGIN
  IF :NEW.CHECKPOINT_SEQUENCE IS NULL THEN
    IF :NEW.CHECKPOINT_TOKEN IS NOT NULL OR :NEW.CHECKPOINT_AT IS NOT NULL THEN
      RAISE_APPLICATION_ERROR(-20061, 'checkpoint fields must be null together');
    END IF;
  ELSE
    IF :NEW.CHECKPOINT_SEQUENCE < 1 OR :NEW.CHECKPOINT_TOKEN IS NULL OR :NEW.CHECKPOINT_AT IS NULL THEN
      RAISE_APPLICATION_ERROR(-20062, 'checkpoint requires sequence, token and timestamp');
    END IF;
    IF DBMS_LOB.GETLENGTH(:NEW.CHECKPOINT_TOKEN) < 1
       OR DBMS_LOB.GETLENGTH(:NEW.CHECKPOINT_TOKEN) > 4096 THEN
      RAISE_APPLICATION_ERROR(-20063, 'checkpoint token length must be between 1 and 4096');
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER INX_CORE_WORKER_PARAMETER_TRG
BEFORE INSERT OR UPDATE OF PARAMETER_VALUE
ON INFRANEXUM_CORE_WORKER_TASK_PARAMETER
FOR EACH ROW
BEGIN
  IF DBMS_LOB.GETLENGTH(:NEW.PARAMETER_VALUE) > 4096 THEN
    RAISE_APPLICATION_ERROR(-20064, 'task parameter value exceeds 4096 characters');
  END IF;
END;
/
