BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_ITAM_PARTNER_DEDUP CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_ITAM_PARTNER_IDENT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_ITAM_PARTNER_CONTACT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_ITAM_PARTNER_ACCRED CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_ITAM_PARTNER_EXT_ID CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_ITAM_PARTNER_ALIAS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_ITAM_PARTNER_ROLE CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFRANEXUM_ITAM_PARTNER CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END;/
