package io.infranexum.server.ddi.cli;

import io.infranexum.core.contracts.*;
import io.infranexum.ddi.ipam.application.*;
import io.infranexum.ddi.ipam.domain.*;
import io.infranexum.identity.access.application.*;
import io.infranexum.identity.access.domain.*;
import io.infranexum.identity.access.ports.IdentityAccessFeaturePolicy;
import io.infranexum.identity.local.application.*;
import io.infranexum.server.platform.PlatformCapabilityService;
import java.io.*;
import java.nio.*;
import java.nio.charset.*;
import java.nio.file.*;
import java.util.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

/** Server-owned PGM-08-E01 CLI. Structured mutations use absolute JSON input files and secrets only through password files. */
public final class IpamCli{
 public static final int EXIT_OK=0,EXIT_USAGE=2,EXIT_AUTHENTICATION=3,EXIT_AUTHORIZATION=4,EXIT_BUSINESS=5,EXIT_INTERNAL=70;private final LocalAuthenticationService authentication;private final RbacAuthorizationService authorization;private final PolicyDecisionService policy;private final IdentityAccessFeaturePolicy features;private final PlatformCapabilityService capabilities;private final IpamApplicationService service;private final UuidV7Generator ids;private final JsonMapper json=JsonMapper.builder().build();
 public IpamCli(LocalAuthenticationService a,RbacAuthorizationService z,PolicyDecisionService p,IdentityAccessFeaturePolicy f,PlatformCapabilityService c,IpamApplicationService s,UuidV7Generator i){authentication=Objects.requireNonNull(a);authorization=Objects.requireNonNull(z);policy=Objects.requireNonNull(p);features=Objects.requireNonNull(f);capabilities=Objects.requireNonNull(c);service=Objects.requireNonNull(s);ids=Objects.requireNonNull(i);}
 public int run(String[] argv,PrintWriter out,PrintWriter err){if(argv.length==0||has(argv,"--help")||has(argv,"-h")){out.print(help());out.flush();return EXIT_OK;}AuthenticatedSession session=null;try{Args a=Args.parse(argv);char[] secret=readSecret(a.required("password-file"));try{session=authentication.authenticate(a.required("username"),secret);}finally{Arrays.fill(secret,'\0');}Object result=execute(a,session.account().id(),ids.next());out.println(a.json()?json.writeValueAsString(result):String.valueOf(result));out.flush();return EXIT_OK;}catch(CliAuthorizationException e){err.println("authorization denied: "+safe(e.getMessage()));return EXIT_AUTHORIZATION;}catch(IllegalArgumentException e){err.println("usage error: "+safe(e.getMessage()));return EXIT_USAGE;}catch(IpamConflictException|IpamNotFoundException e){err.println(e.getClass().getSimpleName()+": "+safe(e.getMessage()));return EXIT_BUSINESS;}catch(Exception e){if(session==null){err.println("authentication failed");return EXIT_AUTHENTICATION;}err.println("internal CLI failure: "+e.getClass().getSimpleName());return EXIT_INTERNAL;}finally{if(session!=null)try{authentication.logout(new ValidatedSession(session.account(),session.session()));}catch(RuntimeException ignored){}}}
 private Object execute(Args a,DomainIdentifier actor,DomainIdentifier corr){if(!"ddi".equals(a.namespace)||!"ipam".equals(a.resource))throw new IllegalArgumentException("command must start with 'ddi ipam'");return switch(a.operation){case "vrfs"->vrfs(a,actor,corr);case "vrf-create"->vrfCreate(a,actor,corr);case "vrf-status"->vrfStatus(a,actor,corr);case "vlans"->vlans(a,actor,corr);case "vlan-create"->vlanCreate(a,actor,corr);case "vlan-status"->vlanStatus(a,actor,corr);case "networks"->networks(a,actor,corr);case "network-create"->networkCreate(a,actor,corr);case "network-update"->networkUpdate(a,actor,corr);case "network-status"->networkStatus(a,actor,corr);case "pools"->pools(a,actor,corr);case "pool-create"->poolCreate(a,actor,corr);case "addresses"->addresses(a,actor,corr);case "allocate"->allocate(a,actor,corr);case "release"->release(a,actor,corr);default->throw new IllegalArgumentException("unknown IPAM operation: "+a.operation);};}
 private Object vrfs(Args a,DomainIdentifier actor,DomainIdentifier corr){DomainIdentifier org=a.id("organization-id");require(actor,PermissionCodes.DDI_IPAM_READ,org,corr,"ddi-vrf","collection",null);return service.vrfs(org,a.limit());}
 private Object vrfCreate(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DDI_IPAM_VRF_CREATE,org,corr,"ddi-vrf","collection",reason);var c=new CreateVrfCommand(org,text(n,"code"),text(n,"displayName"),optional(n,"routeDistinguisher"));if(a.dry())return Map.of("dryRun",true,"operation","vrf-create","code",c.code());return service.createVrf(c,ctx(actor,corr,reason,a));}
 private Object vrfStatus(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.vrf(a.id("id"));String reason=a.required("reason");require(actor,PermissionCodes.DDI_IPAM_VRF_UPDATE,x.organizationId(),corr,"ddi-vrf",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.changeVrfStatus(x.id(),a.version(),IpamStatus.parse(a.required("target")),ctx(actor,corr,reason,a));}
 private Object vlans(Args a,DomainIdentifier actor,DomainIdentifier corr){DomainIdentifier org=a.id("organization-id");require(actor,PermissionCodes.DDI_IPAM_READ,org,corr,"ddi-vlan","collection",null);return service.vlans(org,a.limit());}
 private Object vlanCreate(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DDI_IPAM_VLAN_CREATE,org,corr,"ddi-vlan","collection",reason);var c=new CreateVlanCommand(org,optionalId(n,"siteId"),integer(n,"vlanId"),longValue(n,"vni"),text(n,"name"));if(a.dry())return Map.of("dryRun",true,"operation","vlan-create");return service.createVlan(c,ctx(actor,corr,reason,a));}
 private Object vlanStatus(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.vlan(a.id("id"));String reason=a.required("reason");require(actor,PermissionCodes.DDI_IPAM_VLAN_UPDATE,x.organizationId(),corr,"ddi-vlan",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.changeVlanStatus(x.id(),a.version(),IpamStatus.parse(a.required("target")),ctx(actor,corr,reason,a));}
 private Object networks(Args a,DomainIdentifier actor,DomainIdentifier corr){DomainIdentifier org=a.id("organization-id");require(actor,PermissionCodes.DDI_IPAM_READ,org,corr,"ddi-network","collection",null);return service.networks(org,a.optionalId("vrf-id"),a.limit());}
 private Object networkCreate(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DDI_IPAM_NETWORK_CREATE,org,corr,"ddi-network","collection",reason);var c=new CreateNetworkCommand(org,optionalId(n,"subdivisionId"),optionalId(n,"siteId"),id(n,"vrfId"),optionalId(n,"vlanId"),optionalId(n,"parentNetworkId"),NetworkKind.parse(text(n,"kind")),text(n,"cidr"),optional(n,"usage"),optional(n,"trustLevel"));if(a.dry())return Map.of("dryRun",true,"operation","network-create","cidr",c.cidr());return service.createNetwork(c,ctx(actor,corr,reason,a));}
 private Object networkUpdate(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.network(a.id("id"));JsonNode n=input(a);String reason=reason(n,a);require(actor,PermissionCodes.DDI_IPAM_NETWORK_UPDATE,x.organizationId(),corr,"ddi-network",x.id().toString(),reason);var c=new UpdateNetworkCommand(optionalId(n,"vlanId"),optional(n,"usage"),optional(n,"trustLevel"));if(a.dry())return Map.of("dryRun",true,"operation","network-update");return service.updateNetwork(x.id(),a.version(),c,ctx(actor,corr,reason,a));}
 private Object networkStatus(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.network(a.id("id"));String reason=a.required("reason");require(actor,PermissionCodes.DDI_IPAM_NETWORK_UPDATE,x.organizationId(),corr,"ddi-network",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.changeNetworkStatus(x.id(),a.version(),IpamStatus.parse(a.required("target")),ctx(actor,corr,reason,a));}
 private Object pools(Args a,DomainIdentifier actor,DomainIdentifier corr){var n=service.network(a.id("network-id"));require(actor,PermissionCodes.DDI_IPAM_READ,n.organizationId(),corr,"ddi-pool","collection",null);return service.pools(n.id(),a.limit());}
 private Object poolCreate(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DDI_IPAM_POOL_CREATE,org,corr,"ddi-pool","collection",reason);var c=new CreatePoolCommand(org,id(n,"networkId"),text(n,"startAddress"),text(n,"endAddress"),text(n,"name"));if(a.dry())return Map.of("dryRun",true,"operation","pool-create");return service.createPool(c,ctx(actor,corr,reason,a));}
 private Object addresses(Args a,DomainIdentifier actor,DomainIdentifier corr){DomainIdentifier org=a.id("organization-id");require(actor,PermissionCodes.DDI_IPAM_ADDRESS_READ,org,corr,"ddi-address","collection",null);return service.addresses(org,a.optionalId("vrf-id"),a.optionalId("network-id"),a.limit());}
 private Object allocate(Args a,DomainIdentifier actor,DomainIdentifier corr){JsonNode n=input(a);DomainIdentifier org=id(n,"organizationId");String reason=reason(n,a);require(actor,PermissionCodes.DDI_IPAM_ADDRESS_ALLOCATE,org,corr,"ddi-address","collection",reason);var c=new AllocateAddressCommand(org,id(n,"vrfId"),id(n,"networkId"),optionalId(n,"poolId"),optional(n,"requestedAddress"),bool(n,"reservation"),optional(n,"hostname"),optionalId(n,"rsotObjectId"),optionalId(n,"dcimEquipmentId"),optional(n,"purpose"));if(a.dry())return Map.of("dryRun",true,"operation","allocate");return service.allocate(c,ctx(actor,corr,reason,a));}
 private Object release(Args a,DomainIdentifier actor,DomainIdentifier corr){var x=service.address(a.id("id"));String reason=a.required("reason");require(actor,PermissionCodes.DDI_IPAM_ADDRESS_RELEASE,x.organizationId(),corr,"ddi-address",x.id().toString(),reason);if(a.dry())return Map.of("dryRun",true);return service.release(x.id(),a.version(),ctx(actor,corr,reason,a));}
 private IpamCommandContext ctx(DomainIdentifier actor,DomainIdentifier corr,String reason,Args a){return new IpamCommandContext(actor,corr,reason,a.required("idempotency-key"));}
 private void require(DomainIdentifier actor,String perm,DomainIdentifier org,DomainIdentifier corr,String type,String target,String justification){AuthorizationDecision d=authorization.decide(actor,perm,AuthorizationScope.organization(org),corr,type,target,"CLI");if(!d.allowed())throw new CliAuthorizationException(d.explanation());if(!features.supportsAdvancedAuthorization())return;boolean present=justification!=null&&justification.strip().length()>=8;String cv=capabilities.snapshot().catalogVersion()+":"+capabilities.snapshot().profileVersion();var req=new PolicyEvaluationRequest(actor,perm,type,target,AuthorizationScope.organization(org),Map.of("channel","CLI","justification_present",Boolean.toString(present)),"LOCAL_SESSION",cv,null,true);var adv=policy.decide(req,corr,"CLI");if(!adv.permitted())throw new CliAuthorizationException(adv.reasonCode());for(var o:adv.obligations())if(!(o==PolicyObligation.REQUIRE_JUSTIFICATION&&present))throw new CliAuthorizationException("required authorization obligation is not satisfied: "+o.name());}
 private JsonNode input(Args a){Path p=Path.of(a.required("input-file"));if(!p.isAbsolute())throw new IllegalArgumentException("--input-file must be absolute");try{JsonNode n=json.readTree(Files.readString(p,StandardCharsets.UTF_8));if(n==null||!n.isObject())throw new IllegalArgumentException("input root must be a JSON object");return n;}catch(IOException e){throw new IllegalArgumentException("input file is unreadable or invalid JSON",e);}}
 private static String reason(JsonNode n,Args a){JsonNode x=n.get("reason");return x==null?a.required("reason"):text(n,"reason");}private static DomainIdentifier id(JsonNode n,String k){return DomainIdentifier.parse(text(n,k));}private static DomainIdentifier optionalId(JsonNode n,String k){String v=optional(n,k);return v==null?null:DomainIdentifier.parse(v);}private static String text(JsonNode n,String k){JsonNode v=n.get(k);if(v==null||!v.isTextual()||v.textValue().isBlank())throw new IllegalArgumentException(k+" is required");return v.textValue().strip();}private static String optional(JsonNode n,String k){JsonNode v=n.get(k);return v==null||v.isNull()?null:(v.isTextual()?v.textValue().strip():String.valueOf(v));}private static Integer integer(JsonNode n,String k){JsonNode v=n.get(k);return v==null||v.isNull()?null:v.asInt();}private static Long longValue(JsonNode n,String k){JsonNode v=n.get(k);return v==null||v.isNull()?null:v.asLong();}private static boolean bool(JsonNode n,String k){JsonNode v=n.get(k);return v!=null&&v.asBoolean(false);}
 private static char[] readSecret(String value){Path p=Path.of(value);if(!p.isAbsolute())throw new IllegalArgumentException("--password-file must be absolute");try{byte[] b=Files.readAllBytes(p);try{CharBuffer c=StandardCharsets.UTF_8.newDecoder().decode(ByteBuffer.wrap(b));String x=c.toString().stripTrailing();if(x.isEmpty())throw new IllegalArgumentException("password file is empty");return x.toCharArray();}finally{Arrays.fill(b,(byte)0);}}catch(IOException e){throw new IllegalArgumentException("password file is unreadable",e);}}
 private static boolean has(String[] a,String x){return Arrays.asList(a).contains(x);}private static String safe(String x){return x==null?"request failed":x.replaceAll("[\\r\\n\\t]+"," ").strip();}private static String help(){return """InfraNexum DDI/IPAM CLI
  ddi ipam vrfs|vlans|networks|addresses --organization-id UUID --username USER --password-file ABS [--limit N] [--output json]
  ddi ipam pools --network-id UUID --username USER --password-file ABS [--limit N] [--output json]
  ddi ipam vrf-create|vlan-create|network-create|network-update|pool-create|allocate --input-file ABS --idempotency-key KEY --username USER --password-file ABS [--id UUID --version N] [--dry-run] [--output json]
  ddi ipam vrf-status|vlan-status|network-status|release --id UUID --version N --reason TEXT --idempotency-key KEY --username USER --password-file ABS [--target STATUS] [--dry-run] [--output json]
Secrets are accepted only through --password-file.
""";}
 private static final class CliAuthorizationException extends RuntimeException{private static final long serialVersionUID=1L;CliAuthorizationException(String m){super(m);}}
 private record Args(String namespace,String resource,String operation,Map<String,String> values,Set<String> flags){static Args parse(String[] in){if(in.length<3)throw new IllegalArgumentException("namespace, resource and operation required");Map<String,String> v=new LinkedHashMap<>();Set<String> f=new LinkedHashSet<>();for(int i=3;i<in.length;i++){if(!in[i].startsWith("--"))throw new IllegalArgumentException("unexpected argument: "+in[i]);String k=in[i].substring(2);if(Set.of("dry-run","json").contains(k)){f.add(k);continue;}if(i+1>=in.length||in[i+1].startsWith("--"))throw new IllegalArgumentException("--"+k+" requires a value");v.put(k,in[++i]);}if("json".equalsIgnoreCase(v.get("output")))f.add("json");return new Args(in[0],in[1],in[2],Map.copyOf(v),Set.copyOf(f));}String required(String k){String x=values.get(k);if(x==null||x.isBlank())throw new IllegalArgumentException("--"+k+" is required");return x.strip();}DomainIdentifier id(String k){return DomainIdentifier.parse(required(k));}DomainIdentifier optionalId(String k){String x=values.get(k);return x==null?null:DomainIdentifier.parse(x);}long version(){long x=Long.parseLong(required("version"));if(x<1)throw new IllegalArgumentException("version must be positive");return x;}int limit(){int x=Integer.parseInt(values.getOrDefault("limit","100"));if(x<1||x>500)throw new IllegalArgumentException("limit must be 1..500");return x;}boolean dry(){return flags.contains("dry-run");}boolean json(){return flags.contains("json");}}
}
